// Code generated by ent, DO NOT EDIT.

package pluginanalytics

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldContainsFold(FieldID, id))
}

// PluginId applies equality check predicate on the "pluginId" field. It's identical to PluginIdEQ.
func PluginId(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldPluginId, v))
}

// Date applies equality check predicate on the "date" field. It's identical to DateEQ.
func Date(v time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldDate, v))
}

// Downloads applies equality check predicate on the "downloads" field. It's identical to DownloadsEQ.
func Downloads(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldDownloads, v))
}

// Views applies equality check predicate on the "views" field. It's identical to ViewsEQ.
func Views(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldViews, v))
}

// PluginIdEQ applies the EQ predicate on the "pluginId" field.
func PluginIdEQ(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldPluginId, v))
}

// PluginIdNEQ applies the NEQ predicate on the "pluginId" field.
func PluginIdNEQ(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNEQ(FieldPluginId, v))
}

// PluginIdIn applies the In predicate on the "pluginId" field.
func PluginIdIn(vs ...string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldIn(FieldPluginId, vs...))
}

// PluginIdNotIn applies the NotIn predicate on the "pluginId" field.
func PluginIdNotIn(vs ...string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNotIn(FieldPluginId, vs...))
}

// PluginIdGT applies the GT predicate on the "pluginId" field.
func PluginIdGT(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGT(FieldPluginId, v))
}

// PluginIdGTE applies the GTE predicate on the "pluginId" field.
func PluginIdGTE(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGTE(FieldPluginId, v))
}

// PluginIdLT applies the LT predicate on the "pluginId" field.
func PluginIdLT(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLT(FieldPluginId, v))
}

// PluginIdLTE applies the LTE predicate on the "pluginId" field.
func PluginIdLTE(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLTE(FieldPluginId, v))
}

// PluginIdContains applies the Contains predicate on the "pluginId" field.
func PluginIdContains(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldContains(FieldPluginId, v))
}

// PluginIdHasPrefix applies the HasPrefix predicate on the "pluginId" field.
func PluginIdHasPrefix(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldHasPrefix(FieldPluginId, v))
}

// PluginIdHasSuffix applies the HasSuffix predicate on the "pluginId" field.
func PluginIdHasSuffix(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldHasSuffix(FieldPluginId, v))
}

// PluginIdEqualFold applies the EqualFold predicate on the "pluginId" field.
func PluginIdEqualFold(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEqualFold(FieldPluginId, v))
}

// PluginIdContainsFold applies the ContainsFold predicate on the "pluginId" field.
func PluginIdContainsFold(v string) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldContainsFold(FieldPluginId, v))
}

// DateEQ applies the EQ predicate on the "date" field.
func DateEQ(v time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldDate, v))
}

// DateNEQ applies the NEQ predicate on the "date" field.
func DateNEQ(v time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNEQ(FieldDate, v))
}

// DateIn applies the In predicate on the "date" field.
func DateIn(vs ...time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldIn(FieldDate, vs...))
}

// DateNotIn applies the NotIn predicate on the "date" field.
func DateNotIn(vs ...time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNotIn(FieldDate, vs...))
}

// DateGT applies the GT predicate on the "date" field.
func DateGT(v time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGT(FieldDate, v))
}

// DateGTE applies the GTE predicate on the "date" field.
func DateGTE(v time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGTE(FieldDate, v))
}

// DateLT applies the LT predicate on the "date" field.
func DateLT(v time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLT(FieldDate, v))
}

// DateLTE applies the LTE predicate on the "date" field.
func DateLTE(v time.Time) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLTE(FieldDate, v))
}

// DownloadsEQ applies the EQ predicate on the "downloads" field.
func DownloadsEQ(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldDownloads, v))
}

// DownloadsNEQ applies the NEQ predicate on the "downloads" field.
func DownloadsNEQ(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNEQ(FieldDownloads, v))
}

// DownloadsIn applies the In predicate on the "downloads" field.
func DownloadsIn(vs ...int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldIn(FieldDownloads, vs...))
}

// DownloadsNotIn applies the NotIn predicate on the "downloads" field.
func DownloadsNotIn(vs ...int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNotIn(FieldDownloads, vs...))
}

// DownloadsGT applies the GT predicate on the "downloads" field.
func DownloadsGT(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGT(FieldDownloads, v))
}

// DownloadsGTE applies the GTE predicate on the "downloads" field.
func DownloadsGTE(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGTE(FieldDownloads, v))
}

// DownloadsLT applies the LT predicate on the "downloads" field.
func DownloadsLT(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLT(FieldDownloads, v))
}

// DownloadsLTE applies the LTE predicate on the "downloads" field.
func DownloadsLTE(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLTE(FieldDownloads, v))
}

// ViewsEQ applies the EQ predicate on the "views" field.
func ViewsEQ(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldEQ(FieldViews, v))
}

// ViewsNEQ applies the NEQ predicate on the "views" field.
func ViewsNEQ(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNEQ(FieldViews, v))
}

// ViewsIn applies the In predicate on the "views" field.
func ViewsIn(vs ...int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldIn(FieldViews, vs...))
}

// ViewsNotIn applies the NotIn predicate on the "views" field.
func ViewsNotIn(vs ...int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldNotIn(FieldViews, vs...))
}

// ViewsGT applies the GT predicate on the "views" field.
func ViewsGT(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGT(FieldViews, v))
}

// ViewsGTE applies the GTE predicate on the "views" field.
func ViewsGTE(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldGTE(FieldViews, v))
}

// ViewsLT applies the LT predicate on the "views" field.
func ViewsLT(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLT(FieldViews, v))
}

// ViewsLTE applies the LTE predicate on the "views" field.
func ViewsLTE(v int) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.FieldLTE(FieldViews, v))
}

// HasPlugin applies the HasEdge predicate on the "plugin" edge.
func HasPlugin() predicate.PluginAnalytics {
	return predicate.PluginAnalytics(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PluginTable, PluginColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPluginWith applies the HasEdge predicate on the "plugin" edge with a given conditions (other predicates).
func HasPluginWith(preds ...predicate.Plugin) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(func(s *sql.Selector) {
		step := newPluginStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.PluginAnalytics) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.PluginAnalytics) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.PluginAnalytics) predicate.PluginAnalytics {
	return predicate.PluginAnalytics(sql.NotPredicates(p))
}
