// Code generated by ent, DO NOT EDIT.

package autocheck

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the autocheck type in the database.
	Label = "auto_check"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldTier holds the string denoting the tier field in the database.
	FieldTier = "tier"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStructureOk holds the string denoting the structureok field in the database.
	FieldStructureOk = "structure_ok"
	// FieldDepsOk holds the string denoting the depsok field in the database.
	FieldDepsOk = "deps_ok"
	// FieldSemverOk holds the string denoting the semverok field in the database.
	FieldSemverOk = "semver_ok"
	// FieldFileSizeOk holds the string denoting the filesizeok field in the database.
	FieldFileSizeOk = "file_size_ok"
	// FieldSecurityScanOk holds the string denoting the securityscanok field in the database.
	FieldSecurityScanOk = "security_scan_ok"
	// FieldSandboxLoadOk holds the string denoting the sandboxloadok field in the database.
	FieldSandboxLoadOk = "sandbox_load_ok"
	// FieldSandboxCrashFree holds the string denoting the sandboxcrashfree field in the database.
	FieldSandboxCrashFree = "sandbox_crash_free"
	// FieldLogs holds the string denoting the logs field in the database.
	FieldLogs = "logs"
	// FieldScore holds the string denoting the score field in the database.
	FieldScore = "score"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldFinishedAt holds the string denoting the finishedat field in the database.
	FieldFinishedAt = "finished_at"
	// FieldPluginId holds the string denoting the pluginid field in the database.
	FieldPluginId = "plugin_id"
	// EdgePlugin holds the string denoting the plugin edge name in mutations.
	EdgePlugin = "plugin"
	// Table holds the table name of the autocheck in the database.
	Table = "auto_checks"
	// PluginTable is the table that holds the plugin relation/edge.
	PluginTable = "auto_checks"
	// PluginInverseTable is the table name for the Plugin entity.
	// It exists in this package in order to avoid circular dependency with the "plugin" package.
	PluginInverseTable = "plugins"
	// PluginColumn is the table column denoting the plugin relation/edge.
	PluginColumn = "plugin_id"
)

// Columns holds all SQL columns for autocheck fields.
var Columns = []string{
	FieldID,
	FieldTier,
	FieldStatus,
	FieldStructureOk,
	FieldDepsOk,
	FieldSemverOk,
	FieldFileSizeOk,
	FieldSecurityScanOk,
	FieldSandboxLoadOk,
	FieldSandboxCrashFree,
	FieldLogs,
	FieldScore,
	FieldCreatedAt,
	FieldFinishedAt,
	FieldPluginId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Tier defines the type for the "tier" enum field.
type Tier string

// Tier values.
const (
	TierTIER_1_AUTO    Tier = "TIER_1_AUTO"
	TierTIER_2_SANDBOX Tier = "TIER_2_SANDBOX"
)

func (t Tier) String() string {
	return string(t)
}

// TierValidator is a validator for the "tier" field enum values. It is called by the builders before save.
func TierValidator(t Tier) error {
	switch t {
	case TierTIER_1_AUTO, TierTIER_2_SANDBOX:
		return nil
	default:
		return fmt.Errorf("autocheck: invalid enum value for tier field: %q", t)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusRUNNING is the default value of the Status enum.
const DefaultStatus = StatusRUNNING

// Status values.
const (
	StatusRUNNING Status = "RUNNING"
	StatusPASSED  Status = "PASSED"
	StatusFAILED  Status = "FAILED"
	StatusSKIPPED Status = "SKIPPED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusRUNNING, StatusPASSED, StatusFAILED, StatusSKIPPED:
		return nil
	default:
		return fmt.Errorf("autocheck: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the AutoCheck queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByTier orders the results by the tier field.
func ByTier(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTier, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStructureOk orders the results by the structureOk field.
func ByStructureOk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStructureOk, opts...).ToFunc()
}

// ByDepsOk orders the results by the depsOk field.
func ByDepsOk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDepsOk, opts...).ToFunc()
}

// BySemverOk orders the results by the semverOk field.
func BySemverOk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSemverOk, opts...).ToFunc()
}

// ByFileSizeOk orders the results by the fileSizeOk field.
func ByFileSizeOk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSizeOk, opts...).ToFunc()
}

// BySecurityScanOk orders the results by the securityScanOk field.
func BySecurityScanOk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSecurityScanOk, opts...).ToFunc()
}

// BySandboxLoadOk orders the results by the sandboxLoadOk field.
func BySandboxLoadOk(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSandboxLoadOk, opts...).ToFunc()
}

// BySandboxCrashFree orders the results by the sandboxCrashFree field.
func BySandboxCrashFree(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSandboxCrashFree, opts...).ToFunc()
}

// ByLogs orders the results by the logs field.
func ByLogs(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLogs, opts...).ToFunc()
}

// ByScore orders the results by the score field.
func ByScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldScore, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByFinishedAt orders the results by the finishedAt field.
func ByFinishedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFinishedAt, opts...).ToFunc()
}

// ByPluginId orders the results by the pluginId field.
func ByPluginId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginId, opts...).ToFunc()
}

// ByPluginField orders the results by plugin field.
func ByPluginField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPluginStep(), sql.OrderByField(field, opts...))
	}
}
func newPluginStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PluginInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PluginTable, PluginColumn),
	)
}
