// Code generated by ent, DO NOT EDIT.

package autocheck

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldContainsFold(FieldID, id))
}

// StructureOk applies equality check predicate on the "structureOk" field. It's identical to StructureOkEQ.
func StructureOk(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldStructureOk, v))
}

// DepsOk applies equality check predicate on the "depsOk" field. It's identical to DepsOkEQ.
func DepsOk(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldDepsOk, v))
}

// SemverOk applies equality check predicate on the "semverOk" field. It's identical to SemverOkEQ.
func SemverOk(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldSemverOk, v))
}

// FileSizeOk applies equality check predicate on the "fileSizeOk" field. It's identical to FileSizeOkEQ.
func FileSizeOk(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldFileSizeOk, v))
}

// SecurityScanOk applies equality check predicate on the "securityScanOk" field. It's identical to SecurityScanOkEQ.
func SecurityScanOk(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldSecurityScanOk, v))
}

// SandboxLoadOk applies equality check predicate on the "sandboxLoadOk" field. It's identical to SandboxLoadOkEQ.
func SandboxLoadOk(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldSandboxLoadOk, v))
}

// SandboxCrashFree applies equality check predicate on the "sandboxCrashFree" field. It's identical to SandboxCrashFreeEQ.
func SandboxCrashFree(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldSandboxCrashFree, v))
}

// Logs applies equality check predicate on the "logs" field. It's identical to LogsEQ.
func Logs(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldLogs, v))
}

// Score applies equality check predicate on the "score" field. It's identical to ScoreEQ.
func Score(v float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldScore, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldCreatedAt, v))
}

// FinishedAt applies equality check predicate on the "finishedAt" field. It's identical to FinishedAtEQ.
func FinishedAt(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldFinishedAt, v))
}

// PluginId applies equality check predicate on the "pluginId" field. It's identical to PluginIdEQ.
func PluginId(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldPluginId, v))
}

// TierEQ applies the EQ predicate on the "tier" field.
func TierEQ(v Tier) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldTier, v))
}

// TierNEQ applies the NEQ predicate on the "tier" field.
func TierNEQ(v Tier) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldTier, v))
}

// TierIn applies the In predicate on the "tier" field.
func TierIn(vs ...Tier) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIn(FieldTier, vs...))
}

// TierNotIn applies the NotIn predicate on the "tier" field.
func TierNotIn(vs ...Tier) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotIn(FieldTier, vs...))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotIn(FieldStatus, vs...))
}

// StructureOkEQ applies the EQ predicate on the "structureOk" field.
func StructureOkEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldStructureOk, v))
}

// StructureOkNEQ applies the NEQ predicate on the "structureOk" field.
func StructureOkNEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldStructureOk, v))
}

// StructureOkIsNil applies the IsNil predicate on the "structureOk" field.
func StructureOkIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldStructureOk))
}

// StructureOkNotNil applies the NotNil predicate on the "structureOk" field.
func StructureOkNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldStructureOk))
}

// DepsOkEQ applies the EQ predicate on the "depsOk" field.
func DepsOkEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldDepsOk, v))
}

// DepsOkNEQ applies the NEQ predicate on the "depsOk" field.
func DepsOkNEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldDepsOk, v))
}

// DepsOkIsNil applies the IsNil predicate on the "depsOk" field.
func DepsOkIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldDepsOk))
}

// DepsOkNotNil applies the NotNil predicate on the "depsOk" field.
func DepsOkNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldDepsOk))
}

// SemverOkEQ applies the EQ predicate on the "semverOk" field.
func SemverOkEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldSemverOk, v))
}

// SemverOkNEQ applies the NEQ predicate on the "semverOk" field.
func SemverOkNEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldSemverOk, v))
}

// SemverOkIsNil applies the IsNil predicate on the "semverOk" field.
func SemverOkIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldSemverOk))
}

// SemverOkNotNil applies the NotNil predicate on the "semverOk" field.
func SemverOkNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldSemverOk))
}

// FileSizeOkEQ applies the EQ predicate on the "fileSizeOk" field.
func FileSizeOkEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldFileSizeOk, v))
}

// FileSizeOkNEQ applies the NEQ predicate on the "fileSizeOk" field.
func FileSizeOkNEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldFileSizeOk, v))
}

// FileSizeOkIsNil applies the IsNil predicate on the "fileSizeOk" field.
func FileSizeOkIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldFileSizeOk))
}

// FileSizeOkNotNil applies the NotNil predicate on the "fileSizeOk" field.
func FileSizeOkNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldFileSizeOk))
}

// SecurityScanOkEQ applies the EQ predicate on the "securityScanOk" field.
func SecurityScanOkEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldSecurityScanOk, v))
}

// SecurityScanOkNEQ applies the NEQ predicate on the "securityScanOk" field.
func SecurityScanOkNEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldSecurityScanOk, v))
}

// SecurityScanOkIsNil applies the IsNil predicate on the "securityScanOk" field.
func SecurityScanOkIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldSecurityScanOk))
}

// SecurityScanOkNotNil applies the NotNil predicate on the "securityScanOk" field.
func SecurityScanOkNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldSecurityScanOk))
}

// SandboxLoadOkEQ applies the EQ predicate on the "sandboxLoadOk" field.
func SandboxLoadOkEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldSandboxLoadOk, v))
}

// SandboxLoadOkNEQ applies the NEQ predicate on the "sandboxLoadOk" field.
func SandboxLoadOkNEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldSandboxLoadOk, v))
}

// SandboxLoadOkIsNil applies the IsNil predicate on the "sandboxLoadOk" field.
func SandboxLoadOkIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldSandboxLoadOk))
}

// SandboxLoadOkNotNil applies the NotNil predicate on the "sandboxLoadOk" field.
func SandboxLoadOkNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldSandboxLoadOk))
}

// SandboxCrashFreeEQ applies the EQ predicate on the "sandboxCrashFree" field.
func SandboxCrashFreeEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldSandboxCrashFree, v))
}

// SandboxCrashFreeNEQ applies the NEQ predicate on the "sandboxCrashFree" field.
func SandboxCrashFreeNEQ(v bool) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldSandboxCrashFree, v))
}

// SandboxCrashFreeIsNil applies the IsNil predicate on the "sandboxCrashFree" field.
func SandboxCrashFreeIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldSandboxCrashFree))
}

// SandboxCrashFreeNotNil applies the NotNil predicate on the "sandboxCrashFree" field.
func SandboxCrashFreeNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldSandboxCrashFree))
}

// LogsEQ applies the EQ predicate on the "logs" field.
func LogsEQ(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldLogs, v))
}

// LogsNEQ applies the NEQ predicate on the "logs" field.
func LogsNEQ(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldLogs, v))
}

// LogsIn applies the In predicate on the "logs" field.
func LogsIn(vs ...string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIn(FieldLogs, vs...))
}

// LogsNotIn applies the NotIn predicate on the "logs" field.
func LogsNotIn(vs ...string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotIn(FieldLogs, vs...))
}

// LogsGT applies the GT predicate on the "logs" field.
func LogsGT(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGT(FieldLogs, v))
}

// LogsGTE applies the GTE predicate on the "logs" field.
func LogsGTE(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGTE(FieldLogs, v))
}

// LogsLT applies the LT predicate on the "logs" field.
func LogsLT(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLT(FieldLogs, v))
}

// LogsLTE applies the LTE predicate on the "logs" field.
func LogsLTE(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLTE(FieldLogs, v))
}

// LogsContains applies the Contains predicate on the "logs" field.
func LogsContains(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldContains(FieldLogs, v))
}

// LogsHasPrefix applies the HasPrefix predicate on the "logs" field.
func LogsHasPrefix(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldHasPrefix(FieldLogs, v))
}

// LogsHasSuffix applies the HasSuffix predicate on the "logs" field.
func LogsHasSuffix(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldHasSuffix(FieldLogs, v))
}

// LogsIsNil applies the IsNil predicate on the "logs" field.
func LogsIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldLogs))
}

// LogsNotNil applies the NotNil predicate on the "logs" field.
func LogsNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldLogs))
}

// LogsEqualFold applies the EqualFold predicate on the "logs" field.
func LogsEqualFold(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEqualFold(FieldLogs, v))
}

// LogsContainsFold applies the ContainsFold predicate on the "logs" field.
func LogsContainsFold(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldContainsFold(FieldLogs, v))
}

// ScoreEQ applies the EQ predicate on the "score" field.
func ScoreEQ(v float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldScore, v))
}

// ScoreNEQ applies the NEQ predicate on the "score" field.
func ScoreNEQ(v float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldScore, v))
}

// ScoreIn applies the In predicate on the "score" field.
func ScoreIn(vs ...float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIn(FieldScore, vs...))
}

// ScoreNotIn applies the NotIn predicate on the "score" field.
func ScoreNotIn(vs ...float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotIn(FieldScore, vs...))
}

// ScoreGT applies the GT predicate on the "score" field.
func ScoreGT(v float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGT(FieldScore, v))
}

// ScoreGTE applies the GTE predicate on the "score" field.
func ScoreGTE(v float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGTE(FieldScore, v))
}

// ScoreLT applies the LT predicate on the "score" field.
func ScoreLT(v float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLT(FieldScore, v))
}

// ScoreLTE applies the LTE predicate on the "score" field.
func ScoreLTE(v float64) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLTE(FieldScore, v))
}

// ScoreIsNil applies the IsNil predicate on the "score" field.
func ScoreIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldScore))
}

// ScoreNotNil applies the NotNil predicate on the "score" field.
func ScoreNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldScore))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLTE(FieldCreatedAt, v))
}

// FinishedAtEQ applies the EQ predicate on the "finishedAt" field.
func FinishedAtEQ(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldFinishedAt, v))
}

// FinishedAtNEQ applies the NEQ predicate on the "finishedAt" field.
func FinishedAtNEQ(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldFinishedAt, v))
}

// FinishedAtIn applies the In predicate on the "finishedAt" field.
func FinishedAtIn(vs ...time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIn(FieldFinishedAt, vs...))
}

// FinishedAtNotIn applies the NotIn predicate on the "finishedAt" field.
func FinishedAtNotIn(vs ...time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotIn(FieldFinishedAt, vs...))
}

// FinishedAtGT applies the GT predicate on the "finishedAt" field.
func FinishedAtGT(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGT(FieldFinishedAt, v))
}

// FinishedAtGTE applies the GTE predicate on the "finishedAt" field.
func FinishedAtGTE(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGTE(FieldFinishedAt, v))
}

// FinishedAtLT applies the LT predicate on the "finishedAt" field.
func FinishedAtLT(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLT(FieldFinishedAt, v))
}

// FinishedAtLTE applies the LTE predicate on the "finishedAt" field.
func FinishedAtLTE(v time.Time) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLTE(FieldFinishedAt, v))
}

// FinishedAtIsNil applies the IsNil predicate on the "finishedAt" field.
func FinishedAtIsNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIsNull(FieldFinishedAt))
}

// FinishedAtNotNil applies the NotNil predicate on the "finishedAt" field.
func FinishedAtNotNil() predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotNull(FieldFinishedAt))
}

// PluginIdEQ applies the EQ predicate on the "pluginId" field.
func PluginIdEQ(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEQ(FieldPluginId, v))
}

// PluginIdNEQ applies the NEQ predicate on the "pluginId" field.
func PluginIdNEQ(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNEQ(FieldPluginId, v))
}

// PluginIdIn applies the In predicate on the "pluginId" field.
func PluginIdIn(vs ...string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldIn(FieldPluginId, vs...))
}

// PluginIdNotIn applies the NotIn predicate on the "pluginId" field.
func PluginIdNotIn(vs ...string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldNotIn(FieldPluginId, vs...))
}

// PluginIdGT applies the GT predicate on the "pluginId" field.
func PluginIdGT(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGT(FieldPluginId, v))
}

// PluginIdGTE applies the GTE predicate on the "pluginId" field.
func PluginIdGTE(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldGTE(FieldPluginId, v))
}

// PluginIdLT applies the LT predicate on the "pluginId" field.
func PluginIdLT(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLT(FieldPluginId, v))
}

// PluginIdLTE applies the LTE predicate on the "pluginId" field.
func PluginIdLTE(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldLTE(FieldPluginId, v))
}

// PluginIdContains applies the Contains predicate on the "pluginId" field.
func PluginIdContains(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldContains(FieldPluginId, v))
}

// PluginIdHasPrefix applies the HasPrefix predicate on the "pluginId" field.
func PluginIdHasPrefix(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldHasPrefix(FieldPluginId, v))
}

// PluginIdHasSuffix applies the HasSuffix predicate on the "pluginId" field.
func PluginIdHasSuffix(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldHasSuffix(FieldPluginId, v))
}

// PluginIdEqualFold applies the EqualFold predicate on the "pluginId" field.
func PluginIdEqualFold(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldEqualFold(FieldPluginId, v))
}

// PluginIdContainsFold applies the ContainsFold predicate on the "pluginId" field.
func PluginIdContainsFold(v string) predicate.AutoCheck {
	return predicate.AutoCheck(sql.FieldContainsFold(FieldPluginId, v))
}

// HasPlugin applies the HasEdge predicate on the "plugin" edge.
func HasPlugin() predicate.AutoCheck {
	return predicate.AutoCheck(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, PluginTable, PluginColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasPluginWith applies the HasEdge predicate on the "plugin" edge with a given conditions (other predicates).
func HasPluginWith(preds ...predicate.Plugin) predicate.AutoCheck {
	return predicate.AutoCheck(func(s *sql.Selector) {
		step := newPluginStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.AutoCheck) predicate.AutoCheck {
	return predicate.AutoCheck(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.AutoCheck) predicate.AutoCheck {
	return predicate.AutoCheck(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.AutoCheck) predicate.AutoCheck {
	return predicate.AutoCheck(sql.NotPredicates(p))
}
