// Code generated by ent, DO NOT EDIT.

package plugin

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the plugin type in the database.
	Label = "plugin"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldSlug holds the string denoting the slug field in the database.
	FieldSlug = "slug"
	// FieldDisplayName holds the string denoting the displayname field in the database.
	FieldDisplayName = "display_name"
	// FieldDescription holds the string denoting the description field in the database.
	FieldDescription = "description"
	// FieldLongDescription holds the string denoting the longdescription field in the database.
	FieldLongDescription = "long_description"
	// FieldIconUrl holds the string denoting the iconurl field in the database.
	FieldIconUrl = "icon_url"
	// FieldRepoUrl holds the string denoting the repourl field in the database.
	FieldRepoUrl = "repo_url"
	// FieldLicense holds the string denoting the license field in the database.
	FieldLicense = "license"
	// FieldTags holds the string denoting the tags field in the database.
	FieldTags = "tags"
	// FieldKeywords holds the string denoting the keywords field in the database.
	FieldKeywords = "keywords"
	// FieldPluginType holds the string denoting the plugintype field in the database.
	FieldPluginType = "plugin_type"
	// FieldDownloads holds the string denoting the downloads field in the database.
	FieldDownloads = "downloads"
	// FieldStars holds the string denoting the stars field in the database.
	FieldStars = "stars"
	// FieldCommentCount holds the string denoting the commentcount field in the database.
	FieldCommentCount = "comment_count"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusReason holds the string denoting the statusreason field in the database.
	FieldStatusReason = "status_reason"
	// FieldTrustScore holds the string denoting the trustscore field in the database.
	FieldTrustScore = "trust_score"
	// FieldQualityBadge holds the string denoting the qualitybadge field in the database.
	FieldQualityBadge = "quality_badge"
	// FieldIsVerified holds the string denoting the isverified field in the database.
	FieldIsVerified = "is_verified"
	// FieldIsFeatured holds the string denoting the isfeatured field in the database.
	FieldIsFeatured = "is_featured"
	// FieldReviewBuildId holds the string denoting the reviewbuildid field in the database.
	FieldReviewBuildId = "review_build_id"
	// FieldWebhookId holds the string denoting the webhookid field in the database.
	FieldWebhookId = "webhook_id"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// FieldAuthorId holds the string denoting the authorid field in the database.
	FieldAuthorId = "author_id"
	// EdgeAuthor holds the string denoting the author edge name in mutations.
	EdgeAuthor = "author"
	// EdgeVersions holds the string denoting the versions edge name in mutations.
	EdgeVersions = "versions"
	// EdgeBuilds holds the string denoting the builds edge name in mutations.
	EdgeBuilds = "builds"
	// EdgeReviews holds the string denoting the reviews edge name in mutations.
	EdgeReviews = "reviews"
	// EdgeReports holds the string denoting the reports edge name in mutations.
	EdgeReports = "reports"
	// EdgeRatings holds the string denoting the ratings edge name in mutations.
	EdgeRatings = "ratings"
	// EdgeComments holds the string denoting the comments edge name in mutations.
	EdgeComments = "comments"
	// EdgeAutoChecks holds the string denoting the autochecks edge name in mutations.
	EdgeAutoChecks = "autoChecks"
	// EdgeModerationLogs holds the string denoting the moderationlogs edge name in mutations.
	EdgeModerationLogs = "moderationLogs"
	// EdgeAnalytics holds the string denoting the analytics edge name in mutations.
	EdgeAnalytics = "analytics"
	// Table holds the table name of the plugin in the database.
	Table = "plugins"
	// AuthorTable is the table that holds the author relation/edge.
	AuthorTable = "plugins"
	// AuthorInverseTable is the table name for the User entity.
	// It exists in this package in order to avoid circular dependency with the "user" package.
	AuthorInverseTable = "users"
	// AuthorColumn is the table column denoting the author relation/edge.
	AuthorColumn = "author_id"
	// VersionsTable is the table that holds the versions relation/edge.
	VersionsTable = "versions"
	// VersionsInverseTable is the table name for the Version entity.
	// It exists in this package in order to avoid circular dependency with the "version" package.
	VersionsInverseTable = "versions"
	// VersionsColumn is the table column denoting the versions relation/edge.
	VersionsColumn = "plugin_id"
	// BuildsTable is the table that holds the builds relation/edge.
	BuildsTable = "builds"
	// BuildsInverseTable is the table name for the Build entity.
	// It exists in this package in order to avoid circular dependency with the "build" package.
	BuildsInverseTable = "builds"
	// BuildsColumn is the table column denoting the builds relation/edge.
	BuildsColumn = "plugin_id"
	// ReviewsTable is the table that holds the reviews relation/edge.
	ReviewsTable = "reviews"
	// ReviewsInverseTable is the table name for the Review entity.
	// It exists in this package in order to avoid circular dependency with the "review" package.
	ReviewsInverseTable = "reviews"
	// ReviewsColumn is the table column denoting the reviews relation/edge.
	ReviewsColumn = "plugin_id"
	// ReportsTable is the table that holds the reports relation/edge.
	ReportsTable = "reports"
	// ReportsInverseTable is the table name for the Report entity.
	// It exists in this package in order to avoid circular dependency with the "report" package.
	ReportsInverseTable = "reports"
	// ReportsColumn is the table column denoting the reports relation/edge.
	ReportsColumn = "plugin_id"
	// RatingsTable is the table that holds the ratings relation/edge.
	RatingsTable = "ratings"
	// RatingsInverseTable is the table name for the Rating entity.
	// It exists in this package in order to avoid circular dependency with the "rating" package.
	RatingsInverseTable = "ratings"
	// RatingsColumn is the table column denoting the ratings relation/edge.
	RatingsColumn = "plugin_id"
	// CommentsTable is the table that holds the comments relation/edge.
	CommentsTable = "plugin_comments"
	// CommentsInverseTable is the table name for the PluginComment entity.
	// It exists in this package in order to avoid circular dependency with the "plugincomment" package.
	CommentsInverseTable = "plugin_comments"
	// CommentsColumn is the table column denoting the comments relation/edge.
	CommentsColumn = "plugin_id"
	// AutoChecksTable is the table that holds the autoChecks relation/edge.
	AutoChecksTable = "auto_checks"
	// AutoChecksInverseTable is the table name for the AutoCheck entity.
	// It exists in this package in order to avoid circular dependency with the "autocheck" package.
	AutoChecksInverseTable = "auto_checks"
	// AutoChecksColumn is the table column denoting the autoChecks relation/edge.
	AutoChecksColumn = "plugin_id"
	// ModerationLogsTable is the table that holds the moderationLogs relation/edge.
	ModerationLogsTable = "moderation_logs"
	// ModerationLogsInverseTable is the table name for the ModerationLog entity.
	// It exists in this package in order to avoid circular dependency with the "moderationlog" package.
	ModerationLogsInverseTable = "moderation_logs"
	// ModerationLogsColumn is the table column denoting the moderationLogs relation/edge.
	ModerationLogsColumn = "plugin_id"
	// AnalyticsTable is the table that holds the analytics relation/edge.
	AnalyticsTable = "plugin_analytics"
	// AnalyticsInverseTable is the table name for the PluginAnalytics entity.
	// It exists in this package in order to avoid circular dependency with the "pluginanalytics" package.
	AnalyticsInverseTable = "plugin_analytics"
	// AnalyticsColumn is the table column denoting the analytics relation/edge.
	AnalyticsColumn = "plugin_id"
)

// Columns holds all SQL columns for plugin fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldSlug,
	FieldDisplayName,
	FieldDescription,
	FieldLongDescription,
	FieldIconUrl,
	FieldRepoUrl,
	FieldLicense,
	FieldTags,
	FieldKeywords,
	FieldPluginType,
	FieldDownloads,
	FieldStars,
	FieldCommentCount,
	FieldStatus,
	FieldStatusReason,
	FieldTrustScore,
	FieldQualityBadge,
	FieldIsVerified,
	FieldIsFeatured,
	FieldReviewBuildId,
	FieldWebhookId,
	FieldCreatedAt,
	FieldUpdatedAt,
	FieldAuthorId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTags holds the default value on creation for the "tags" field.
	DefaultTags []string
	// DefaultKeywords holds the default value on creation for the "keywords" field.
	DefaultKeywords []string
	// DefaultDownloads holds the default value on creation for the "downloads" field.
	DefaultDownloads int
	// DefaultStars holds the default value on creation for the "stars" field.
	DefaultStars int
	// DefaultCommentCount holds the default value on creation for the "commentCount" field.
	DefaultCommentCount int
	// DefaultTrustScore holds the default value on creation for the "trustScore" field.
	DefaultTrustScore float64
	// DefaultIsVerified holds the default value on creation for the "isVerified" field.
	DefaultIsVerified bool
	// DefaultIsFeatured holds the default value on creation for the "isFeatured" field.
	DefaultIsFeatured bool
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// PluginType defines the type for the "pluginType" enum field.
type PluginType string

// PluginTypePYTHON is the default value of the PluginType enum.
const DefaultPluginType = PluginTypePYTHON

// PluginType values.
const (
	PluginTypePYTHON PluginType = "PYTHON"
	PluginTypeCPP    PluginType = "CPP"
)

func (pt PluginType) String() string {
	return string(pt)
}

// PluginTypeValidator is a validator for the "pluginType" field enum values. It is called by the builders before save.
func PluginTypeValidator(pt PluginType) error {
	switch pt {
	case PluginTypePYTHON, PluginTypeCPP:
		return nil
	default:
		return fmt.Errorf("plugin: invalid enum value for pluginType field: %q", pt)
	}
}

// Status defines the type for the "status" enum field.
type Status string

// StatusDRAFT is the default value of the Status enum.
const DefaultStatus = StatusDRAFT

// Status values.
const (
	StatusDRAFT          Status = "DRAFT"
	StatusBUILDING       Status = "BUILDING"
	StatusBUILD_FAILED   Status = "BUILD_FAILED"
	StatusPENDING_REVIEW Status = "PENDING_REVIEW"
	StatusAPPROVED       Status = "APPROVED"
	StatusREJECTED       Status = "REJECTED"
	StatusFLAGGED        Status = "FLAGGED"
	StatusSUSPENDED      Status = "SUSPENDED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDRAFT, StatusBUILDING, StatusBUILD_FAILED, StatusPENDING_REVIEW, StatusAPPROVED, StatusREJECTED, StatusFLAGGED, StatusSUSPENDED:
		return nil
	default:
		return fmt.Errorf("plugin: invalid enum value for status field: %q", s)
	}
}

// QualityBadge defines the type for the "qualityBadge" enum field.
type QualityBadge string

// QualityBadgeNONE is the default value of the QualityBadge enum.
const DefaultQualityBadge = QualityBadgeNONE

// QualityBadge values.
const (
	QualityBadgeNONE   QualityBadge = "NONE"
	QualityBadgeBRONZE QualityBadge = "BRONZE"
	QualityBadgeSILVER QualityBadge = "SILVER"
	QualityBadgeGOLD   QualityBadge = "GOLD"
)

func (qb QualityBadge) String() string {
	return string(qb)
}

// QualityBadgeValidator is a validator for the "qualityBadge" field enum values. It is called by the builders before save.
func QualityBadgeValidator(qb QualityBadge) error {
	switch qb {
	case QualityBadgeNONE, QualityBadgeBRONZE, QualityBadgeSILVER, QualityBadgeGOLD:
		return nil
	default:
		return fmt.Errorf("plugin: invalid enum value for qualityBadge field: %q", qb)
	}
}

// OrderOption defines the ordering options for the Plugin queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// BySlug orders the results by the slug field.
func BySlug(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldSlug, opts...).ToFunc()
}

// ByDisplayName orders the results by the displayName field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByDescription orders the results by the description field.
func ByDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDescription, opts...).ToFunc()
}

// ByLongDescription orders the results by the longDescription field.
func ByLongDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongDescription, opts...).ToFunc()
}

// ByIconUrl orders the results by the iconUrl field.
func ByIconUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIconUrl, opts...).ToFunc()
}

// ByRepoUrl orders the results by the repoUrl field.
func ByRepoUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRepoUrl, opts...).ToFunc()
}

// ByLicense orders the results by the license field.
func ByLicense(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLicense, opts...).ToFunc()
}

// ByPluginType orders the results by the pluginType field.
func ByPluginType(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginType, opts...).ToFunc()
}

// ByDownloads orders the results by the downloads field.
func ByDownloads(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloads, opts...).ToFunc()
}

// ByStars orders the results by the stars field.
func ByStars(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStars, opts...).ToFunc()
}

// ByCommentCount orders the results by the commentCount field.
func ByCommentCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCommentCount, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStatusReason orders the results by the statusReason field.
func ByStatusReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusReason, opts...).ToFunc()
}

// ByTrustScore orders the results by the trustScore field.
func ByTrustScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrustScore, opts...).ToFunc()
}

// ByQualityBadge orders the results by the qualityBadge field.
func ByQualityBadge(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQualityBadge, opts...).ToFunc()
}

// ByIsVerified orders the results by the isVerified field.
func ByIsVerified(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsVerified, opts...).ToFunc()
}

// ByIsFeatured orders the results by the isFeatured field.
func ByIsFeatured(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsFeatured, opts...).ToFunc()
}

// ByReviewBuildId orders the results by the reviewBuildId field.
func ByReviewBuildId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldReviewBuildId, opts...).ToFunc()
}

// ByWebhookId orders the results by the webhookId field.
func ByWebhookId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWebhookId, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByAuthorId orders the results by the authorId field.
func ByAuthorId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAuthorId, opts...).ToFunc()
}

// ByAuthorField orders the results by author field.
func ByAuthorField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAuthorStep(), sql.OrderByField(field, opts...))
	}
}

// ByVersionsCount orders the results by versions count.
func ByVersionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newVersionsStep(), opts...)
	}
}

// ByVersions orders the results by versions terms.
func ByVersions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByBuildsCount orders the results by builds count.
func ByBuildsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newBuildsStep(), opts...)
	}
}

// ByBuilds orders the results by builds terms.
func ByBuilds(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newBuildsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReviewsCount orders the results by reviews count.
func ByReviewsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewsStep(), opts...)
	}
}

// ByReviews orders the results by reviews terms.
func ByReviews(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReportsCount orders the results by reports count.
func ByReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReportsStep(), opts...)
	}
}

// ByReports orders the results by reports terms.
func ByReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRatingsCount orders the results by ratings count.
func ByRatingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRatingsStep(), opts...)
	}
}

// ByRatings orders the results by ratings terms.
func ByRatings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRatingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByCommentsCount orders the results by comments count.
func ByCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newCommentsStep(), opts...)
	}
}

// ByComments orders the results by comments terms.
func ByComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAutoChecksCount orders the results by autoChecks count.
func ByAutoChecksCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAutoChecksStep(), opts...)
	}
}

// ByAutoChecks orders the results by autoChecks terms.
func ByAutoChecks(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAutoChecksStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByModerationLogsCount orders the results by moderationLogs count.
func ByModerationLogsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newModerationLogsStep(), opts...)
	}
}

// ByModerationLogs orders the results by moderationLogs terms.
func ByModerationLogs(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newModerationLogsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAnalyticsCount orders the results by analytics count.
func ByAnalyticsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAnalyticsStep(), opts...)
	}
}

// ByAnalytics orders the results by analytics terms.
func ByAnalytics(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAnalyticsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newAuthorStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AuthorInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, AuthorTable, AuthorColumn),
	)
}
func newVersionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, VersionsTable, VersionsColumn),
	)
}
func newBuildsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(BuildsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, BuildsTable, BuildsColumn),
	)
}
func newReviewsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ReviewsTable, ReviewsColumn),
	)
}
func newReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ReportsTable, ReportsColumn),
	)
}
func newRatingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RatingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, RatingsTable, RatingsColumn),
	)
}
func newCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(CommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, CommentsTable, CommentsColumn),
	)
}
func newAutoChecksStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AutoChecksInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, AutoChecksTable, AutoChecksColumn),
	)
}
func newModerationLogsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ModerationLogsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ModerationLogsTable, ModerationLogsColumn),
	)
}
func newAnalyticsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AnalyticsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, AnalyticsTable, AnalyticsColumn),
	)
}
