// Code generated by ent, DO NOT EDIT.

package plugin

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldID, id))
}

// IDEqualFold applies the EqualFold predicate on the ID field.
func IDEqualFold(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldID, id))
}

// IDContainsFold applies the ContainsFold predicate on the ID field.
func IDContainsFold(id string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldID, id))
}

// Name applies equality check predicate on the "name" field. It's identical to NameEQ.
func Name(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldName, v))
}

// Slug applies equality check predicate on the "slug" field. It's identical to SlugEQ.
func Slug(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldSlug, v))
}

// DisplayName applies equality check predicate on the "displayName" field. It's identical to DisplayNameEQ.
func DisplayName(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDisplayName, v))
}

// Description applies equality check predicate on the "description" field. It's identical to DescriptionEQ.
func Description(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDescription, v))
}

// LongDescription applies equality check predicate on the "longDescription" field. It's identical to LongDescriptionEQ.
func LongDescription(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLongDescription, v))
}

// IconUrl applies equality check predicate on the "iconUrl" field. It's identical to IconUrlEQ.
func IconUrl(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldIconUrl, v))
}

// RepoUrl applies equality check predicate on the "repoUrl" field. It's identical to RepoUrlEQ.
func RepoUrl(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldRepoUrl, v))
}

// License applies equality check predicate on the "license" field. It's identical to LicenseEQ.
func License(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLicense, v))
}

// Downloads applies equality check predicate on the "downloads" field. It's identical to DownloadsEQ.
func Downloads(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDownloads, v))
}

// Stars applies equality check predicate on the "stars" field. It's identical to StarsEQ.
func Stars(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldStars, v))
}

// CommentCount applies equality check predicate on the "commentCount" field. It's identical to CommentCountEQ.
func CommentCount(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldCommentCount, v))
}

// StatusReason applies equality check predicate on the "statusReason" field. It's identical to StatusReasonEQ.
func StatusReason(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldStatusReason, v))
}

// TrustScore applies equality check predicate on the "trustScore" field. It's identical to TrustScoreEQ.
func TrustScore(v float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldTrustScore, v))
}

// IsVerified applies equality check predicate on the "isVerified" field. It's identical to IsVerifiedEQ.
func IsVerified(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldIsVerified, v))
}

// IsFeatured applies equality check predicate on the "isFeatured" field. It's identical to IsFeaturedEQ.
func IsFeatured(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldIsFeatured, v))
}

// ReviewBuildId applies equality check predicate on the "reviewBuildId" field. It's identical to ReviewBuildIdEQ.
func ReviewBuildId(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldReviewBuildId, v))
}

// WebhookId applies equality check predicate on the "webhookId" field. It's identical to WebhookIdEQ.
func WebhookId(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldWebhookId, v))
}

// CreatedAt applies equality check predicate on the "createdAt" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updatedAt" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldUpdatedAt, v))
}

// AuthorId applies equality check predicate on the "authorId" field. It's identical to AuthorIdEQ.
func AuthorId(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldAuthorId, v))
}

// NameEQ applies the EQ predicate on the "name" field.
func NameEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldName, v))
}

// NameNEQ applies the NEQ predicate on the "name" field.
func NameNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldName, v))
}

// NameIn applies the In predicate on the "name" field.
func NameIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldName, vs...))
}

// NameNotIn applies the NotIn predicate on the "name" field.
func NameNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldName, vs...))
}

// NameGT applies the GT predicate on the "name" field.
func NameGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldName, v))
}

// NameGTE applies the GTE predicate on the "name" field.
func NameGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldName, v))
}

// NameLT applies the LT predicate on the "name" field.
func NameLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldName, v))
}

// NameLTE applies the LTE predicate on the "name" field.
func NameLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldName, v))
}

// NameContains applies the Contains predicate on the "name" field.
func NameContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldName, v))
}

// NameHasPrefix applies the HasPrefix predicate on the "name" field.
func NameHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldName, v))
}

// NameHasSuffix applies the HasSuffix predicate on the "name" field.
func NameHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldName, v))
}

// NameEqualFold applies the EqualFold predicate on the "name" field.
func NameEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldName, v))
}

// NameContainsFold applies the ContainsFold predicate on the "name" field.
func NameContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldName, v))
}

// SlugEQ applies the EQ predicate on the "slug" field.
func SlugEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldSlug, v))
}

// SlugNEQ applies the NEQ predicate on the "slug" field.
func SlugNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldSlug, v))
}

// SlugIn applies the In predicate on the "slug" field.
func SlugIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldSlug, vs...))
}

// SlugNotIn applies the NotIn predicate on the "slug" field.
func SlugNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldSlug, vs...))
}

// SlugGT applies the GT predicate on the "slug" field.
func SlugGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldSlug, v))
}

// SlugGTE applies the GTE predicate on the "slug" field.
func SlugGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldSlug, v))
}

// SlugLT applies the LT predicate on the "slug" field.
func SlugLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldSlug, v))
}

// SlugLTE applies the LTE predicate on the "slug" field.
func SlugLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldSlug, v))
}

// SlugContains applies the Contains predicate on the "slug" field.
func SlugContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldSlug, v))
}

// SlugHasPrefix applies the HasPrefix predicate on the "slug" field.
func SlugHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldSlug, v))
}

// SlugHasSuffix applies the HasSuffix predicate on the "slug" field.
func SlugHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldSlug, v))
}

// SlugEqualFold applies the EqualFold predicate on the "slug" field.
func SlugEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldSlug, v))
}

// SlugContainsFold applies the ContainsFold predicate on the "slug" field.
func SlugContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldSlug, v))
}

// DisplayNameEQ applies the EQ predicate on the "displayName" field.
func DisplayNameEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDisplayName, v))
}

// DisplayNameNEQ applies the NEQ predicate on the "displayName" field.
func DisplayNameNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldDisplayName, v))
}

// DisplayNameIn applies the In predicate on the "displayName" field.
func DisplayNameIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldDisplayName, vs...))
}

// DisplayNameNotIn applies the NotIn predicate on the "displayName" field.
func DisplayNameNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldDisplayName, vs...))
}

// DisplayNameGT applies the GT predicate on the "displayName" field.
func DisplayNameGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldDisplayName, v))
}

// DisplayNameGTE applies the GTE predicate on the "displayName" field.
func DisplayNameGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldDisplayName, v))
}

// DisplayNameLT applies the LT predicate on the "displayName" field.
func DisplayNameLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldDisplayName, v))
}

// DisplayNameLTE applies the LTE predicate on the "displayName" field.
func DisplayNameLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldDisplayName, v))
}

// DisplayNameContains applies the Contains predicate on the "displayName" field.
func DisplayNameContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldDisplayName, v))
}

// DisplayNameHasPrefix applies the HasPrefix predicate on the "displayName" field.
func DisplayNameHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldDisplayName, v))
}

// DisplayNameHasSuffix applies the HasSuffix predicate on the "displayName" field.
func DisplayNameHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldDisplayName, v))
}

// DisplayNameEqualFold applies the EqualFold predicate on the "displayName" field.
func DisplayNameEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldDisplayName, v))
}

// DisplayNameContainsFold applies the ContainsFold predicate on the "displayName" field.
func DisplayNameContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldDisplayName, v))
}

// DescriptionEQ applies the EQ predicate on the "description" field.
func DescriptionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDescription, v))
}

// DescriptionNEQ applies the NEQ predicate on the "description" field.
func DescriptionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldDescription, v))
}

// DescriptionIn applies the In predicate on the "description" field.
func DescriptionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldDescription, vs...))
}

// DescriptionNotIn applies the NotIn predicate on the "description" field.
func DescriptionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldDescription, vs...))
}

// DescriptionGT applies the GT predicate on the "description" field.
func DescriptionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldDescription, v))
}

// DescriptionGTE applies the GTE predicate on the "description" field.
func DescriptionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldDescription, v))
}

// DescriptionLT applies the LT predicate on the "description" field.
func DescriptionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldDescription, v))
}

// DescriptionLTE applies the LTE predicate on the "description" field.
func DescriptionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldDescription, v))
}

// DescriptionContains applies the Contains predicate on the "description" field.
func DescriptionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldDescription, v))
}

// DescriptionHasPrefix applies the HasPrefix predicate on the "description" field.
func DescriptionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldDescription, v))
}

// DescriptionHasSuffix applies the HasSuffix predicate on the "description" field.
func DescriptionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldDescription, v))
}

// DescriptionEqualFold applies the EqualFold predicate on the "description" field.
func DescriptionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldDescription, v))
}

// DescriptionContainsFold applies the ContainsFold predicate on the "description" field.
func DescriptionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldDescription, v))
}

// LongDescriptionEQ applies the EQ predicate on the "longDescription" field.
func LongDescriptionEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLongDescription, v))
}

// LongDescriptionNEQ applies the NEQ predicate on the "longDescription" field.
func LongDescriptionNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldLongDescription, v))
}

// LongDescriptionIn applies the In predicate on the "longDescription" field.
func LongDescriptionIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldLongDescription, vs...))
}

// LongDescriptionNotIn applies the NotIn predicate on the "longDescription" field.
func LongDescriptionNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldLongDescription, vs...))
}

// LongDescriptionGT applies the GT predicate on the "longDescription" field.
func LongDescriptionGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldLongDescription, v))
}

// LongDescriptionGTE applies the GTE predicate on the "longDescription" field.
func LongDescriptionGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldLongDescription, v))
}

// LongDescriptionLT applies the LT predicate on the "longDescription" field.
func LongDescriptionLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldLongDescription, v))
}

// LongDescriptionLTE applies the LTE predicate on the "longDescription" field.
func LongDescriptionLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldLongDescription, v))
}

// LongDescriptionContains applies the Contains predicate on the "longDescription" field.
func LongDescriptionContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldLongDescription, v))
}

// LongDescriptionHasPrefix applies the HasPrefix predicate on the "longDescription" field.
func LongDescriptionHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldLongDescription, v))
}

// LongDescriptionHasSuffix applies the HasSuffix predicate on the "longDescription" field.
func LongDescriptionHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldLongDescription, v))
}

// LongDescriptionIsNil applies the IsNil predicate on the "longDescription" field.
func LongDescriptionIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldLongDescription))
}

// LongDescriptionNotNil applies the NotNil predicate on the "longDescription" field.
func LongDescriptionNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldLongDescription))
}

// LongDescriptionEqualFold applies the EqualFold predicate on the "longDescription" field.
func LongDescriptionEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldLongDescription, v))
}

// LongDescriptionContainsFold applies the ContainsFold predicate on the "longDescription" field.
func LongDescriptionContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldLongDescription, v))
}

// IconUrlEQ applies the EQ predicate on the "iconUrl" field.
func IconUrlEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldIconUrl, v))
}

// IconUrlNEQ applies the NEQ predicate on the "iconUrl" field.
func IconUrlNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldIconUrl, v))
}

// IconUrlIn applies the In predicate on the "iconUrl" field.
func IconUrlIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldIconUrl, vs...))
}

// IconUrlNotIn applies the NotIn predicate on the "iconUrl" field.
func IconUrlNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldIconUrl, vs...))
}

// IconUrlGT applies the GT predicate on the "iconUrl" field.
func IconUrlGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldIconUrl, v))
}

// IconUrlGTE applies the GTE predicate on the "iconUrl" field.
func IconUrlGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldIconUrl, v))
}

// IconUrlLT applies the LT predicate on the "iconUrl" field.
func IconUrlLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldIconUrl, v))
}

// IconUrlLTE applies the LTE predicate on the "iconUrl" field.
func IconUrlLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldIconUrl, v))
}

// IconUrlContains applies the Contains predicate on the "iconUrl" field.
func IconUrlContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldIconUrl, v))
}

// IconUrlHasPrefix applies the HasPrefix predicate on the "iconUrl" field.
func IconUrlHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldIconUrl, v))
}

// IconUrlHasSuffix applies the HasSuffix predicate on the "iconUrl" field.
func IconUrlHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldIconUrl, v))
}

// IconUrlIsNil applies the IsNil predicate on the "iconUrl" field.
func IconUrlIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldIconUrl))
}

// IconUrlNotNil applies the NotNil predicate on the "iconUrl" field.
func IconUrlNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldIconUrl))
}

// IconUrlEqualFold applies the EqualFold predicate on the "iconUrl" field.
func IconUrlEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldIconUrl, v))
}

// IconUrlContainsFold applies the ContainsFold predicate on the "iconUrl" field.
func IconUrlContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldIconUrl, v))
}

// RepoUrlEQ applies the EQ predicate on the "repoUrl" field.
func RepoUrlEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldRepoUrl, v))
}

// RepoUrlNEQ applies the NEQ predicate on the "repoUrl" field.
func RepoUrlNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldRepoUrl, v))
}

// RepoUrlIn applies the In predicate on the "repoUrl" field.
func RepoUrlIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldRepoUrl, vs...))
}

// RepoUrlNotIn applies the NotIn predicate on the "repoUrl" field.
func RepoUrlNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldRepoUrl, vs...))
}

// RepoUrlGT applies the GT predicate on the "repoUrl" field.
func RepoUrlGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldRepoUrl, v))
}

// RepoUrlGTE applies the GTE predicate on the "repoUrl" field.
func RepoUrlGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldRepoUrl, v))
}

// RepoUrlLT applies the LT predicate on the "repoUrl" field.
func RepoUrlLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldRepoUrl, v))
}

// RepoUrlLTE applies the LTE predicate on the "repoUrl" field.
func RepoUrlLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldRepoUrl, v))
}

// RepoUrlContains applies the Contains predicate on the "repoUrl" field.
func RepoUrlContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldRepoUrl, v))
}

// RepoUrlHasPrefix applies the HasPrefix predicate on the "repoUrl" field.
func RepoUrlHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldRepoUrl, v))
}

// RepoUrlHasSuffix applies the HasSuffix predicate on the "repoUrl" field.
func RepoUrlHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldRepoUrl, v))
}

// RepoUrlIsNil applies the IsNil predicate on the "repoUrl" field.
func RepoUrlIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldRepoUrl))
}

// RepoUrlNotNil applies the NotNil predicate on the "repoUrl" field.
func RepoUrlNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldRepoUrl))
}

// RepoUrlEqualFold applies the EqualFold predicate on the "repoUrl" field.
func RepoUrlEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldRepoUrl, v))
}

// RepoUrlContainsFold applies the ContainsFold predicate on the "repoUrl" field.
func RepoUrlContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldRepoUrl, v))
}

// LicenseEQ applies the EQ predicate on the "license" field.
func LicenseEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldLicense, v))
}

// LicenseNEQ applies the NEQ predicate on the "license" field.
func LicenseNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldLicense, v))
}

// LicenseIn applies the In predicate on the "license" field.
func LicenseIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldLicense, vs...))
}

// LicenseNotIn applies the NotIn predicate on the "license" field.
func LicenseNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldLicense, vs...))
}

// LicenseGT applies the GT predicate on the "license" field.
func LicenseGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldLicense, v))
}

// LicenseGTE applies the GTE predicate on the "license" field.
func LicenseGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldLicense, v))
}

// LicenseLT applies the LT predicate on the "license" field.
func LicenseLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldLicense, v))
}

// LicenseLTE applies the LTE predicate on the "license" field.
func LicenseLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldLicense, v))
}

// LicenseContains applies the Contains predicate on the "license" field.
func LicenseContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldLicense, v))
}

// LicenseHasPrefix applies the HasPrefix predicate on the "license" field.
func LicenseHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldLicense, v))
}

// LicenseHasSuffix applies the HasSuffix predicate on the "license" field.
func LicenseHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldLicense, v))
}

// LicenseIsNil applies the IsNil predicate on the "license" field.
func LicenseIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldLicense))
}

// LicenseNotNil applies the NotNil predicate on the "license" field.
func LicenseNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldLicense))
}

// LicenseEqualFold applies the EqualFold predicate on the "license" field.
func LicenseEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldLicense, v))
}

// LicenseContainsFold applies the ContainsFold predicate on the "license" field.
func LicenseContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldLicense, v))
}

// PluginTypeEQ applies the EQ predicate on the "pluginType" field.
func PluginTypeEQ(v PluginType) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldPluginType, v))
}

// PluginTypeNEQ applies the NEQ predicate on the "pluginType" field.
func PluginTypeNEQ(v PluginType) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldPluginType, v))
}

// PluginTypeIn applies the In predicate on the "pluginType" field.
func PluginTypeIn(vs ...PluginType) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldPluginType, vs...))
}

// PluginTypeNotIn applies the NotIn predicate on the "pluginType" field.
func PluginTypeNotIn(vs ...PluginType) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldPluginType, vs...))
}

// DownloadsEQ applies the EQ predicate on the "downloads" field.
func DownloadsEQ(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldDownloads, v))
}

// DownloadsNEQ applies the NEQ predicate on the "downloads" field.
func DownloadsNEQ(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldDownloads, v))
}

// DownloadsIn applies the In predicate on the "downloads" field.
func DownloadsIn(vs ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldDownloads, vs...))
}

// DownloadsNotIn applies the NotIn predicate on the "downloads" field.
func DownloadsNotIn(vs ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldDownloads, vs...))
}

// DownloadsGT applies the GT predicate on the "downloads" field.
func DownloadsGT(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldDownloads, v))
}

// DownloadsGTE applies the GTE predicate on the "downloads" field.
func DownloadsGTE(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldDownloads, v))
}

// DownloadsLT applies the LT predicate on the "downloads" field.
func DownloadsLT(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldDownloads, v))
}

// DownloadsLTE applies the LTE predicate on the "downloads" field.
func DownloadsLTE(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldDownloads, v))
}

// StarsEQ applies the EQ predicate on the "stars" field.
func StarsEQ(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldStars, v))
}

// StarsNEQ applies the NEQ predicate on the "stars" field.
func StarsNEQ(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldStars, v))
}

// StarsIn applies the In predicate on the "stars" field.
func StarsIn(vs ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldStars, vs...))
}

// StarsNotIn applies the NotIn predicate on the "stars" field.
func StarsNotIn(vs ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldStars, vs...))
}

// StarsGT applies the GT predicate on the "stars" field.
func StarsGT(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldStars, v))
}

// StarsGTE applies the GTE predicate on the "stars" field.
func StarsGTE(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldStars, v))
}

// StarsLT applies the LT predicate on the "stars" field.
func StarsLT(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldStars, v))
}

// StarsLTE applies the LTE predicate on the "stars" field.
func StarsLTE(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldStars, v))
}

// CommentCountEQ applies the EQ predicate on the "commentCount" field.
func CommentCountEQ(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldCommentCount, v))
}

// CommentCountNEQ applies the NEQ predicate on the "commentCount" field.
func CommentCountNEQ(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldCommentCount, v))
}

// CommentCountIn applies the In predicate on the "commentCount" field.
func CommentCountIn(vs ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldCommentCount, vs...))
}

// CommentCountNotIn applies the NotIn predicate on the "commentCount" field.
func CommentCountNotIn(vs ...int) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldCommentCount, vs...))
}

// CommentCountGT applies the GT predicate on the "commentCount" field.
func CommentCountGT(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldCommentCount, v))
}

// CommentCountGTE applies the GTE predicate on the "commentCount" field.
func CommentCountGTE(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldCommentCount, v))
}

// CommentCountLT applies the LT predicate on the "commentCount" field.
func CommentCountLT(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldCommentCount, v))
}

// CommentCountLTE applies the LTE predicate on the "commentCount" field.
func CommentCountLTE(v int) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldCommentCount, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v Status) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v Status) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...Status) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...Status) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusReasonEQ applies the EQ predicate on the "statusReason" field.
func StatusReasonEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldStatusReason, v))
}

// StatusReasonNEQ applies the NEQ predicate on the "statusReason" field.
func StatusReasonNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldStatusReason, v))
}

// StatusReasonIn applies the In predicate on the "statusReason" field.
func StatusReasonIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldStatusReason, vs...))
}

// StatusReasonNotIn applies the NotIn predicate on the "statusReason" field.
func StatusReasonNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldStatusReason, vs...))
}

// StatusReasonGT applies the GT predicate on the "statusReason" field.
func StatusReasonGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldStatusReason, v))
}

// StatusReasonGTE applies the GTE predicate on the "statusReason" field.
func StatusReasonGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldStatusReason, v))
}

// StatusReasonLT applies the LT predicate on the "statusReason" field.
func StatusReasonLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldStatusReason, v))
}

// StatusReasonLTE applies the LTE predicate on the "statusReason" field.
func StatusReasonLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldStatusReason, v))
}

// StatusReasonContains applies the Contains predicate on the "statusReason" field.
func StatusReasonContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldStatusReason, v))
}

// StatusReasonHasPrefix applies the HasPrefix predicate on the "statusReason" field.
func StatusReasonHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldStatusReason, v))
}

// StatusReasonHasSuffix applies the HasSuffix predicate on the "statusReason" field.
func StatusReasonHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldStatusReason, v))
}

// StatusReasonIsNil applies the IsNil predicate on the "statusReason" field.
func StatusReasonIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldStatusReason))
}

// StatusReasonNotNil applies the NotNil predicate on the "statusReason" field.
func StatusReasonNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldStatusReason))
}

// StatusReasonEqualFold applies the EqualFold predicate on the "statusReason" field.
func StatusReasonEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldStatusReason, v))
}

// StatusReasonContainsFold applies the ContainsFold predicate on the "statusReason" field.
func StatusReasonContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldStatusReason, v))
}

// TrustScoreEQ applies the EQ predicate on the "trustScore" field.
func TrustScoreEQ(v float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldTrustScore, v))
}

// TrustScoreNEQ applies the NEQ predicate on the "trustScore" field.
func TrustScoreNEQ(v float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldTrustScore, v))
}

// TrustScoreIn applies the In predicate on the "trustScore" field.
func TrustScoreIn(vs ...float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldTrustScore, vs...))
}

// TrustScoreNotIn applies the NotIn predicate on the "trustScore" field.
func TrustScoreNotIn(vs ...float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldTrustScore, vs...))
}

// TrustScoreGT applies the GT predicate on the "trustScore" field.
func TrustScoreGT(v float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldTrustScore, v))
}

// TrustScoreGTE applies the GTE predicate on the "trustScore" field.
func TrustScoreGTE(v float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldTrustScore, v))
}

// TrustScoreLT applies the LT predicate on the "trustScore" field.
func TrustScoreLT(v float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldTrustScore, v))
}

// TrustScoreLTE applies the LTE predicate on the "trustScore" field.
func TrustScoreLTE(v float64) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldTrustScore, v))
}

// QualityBadgeEQ applies the EQ predicate on the "qualityBadge" field.
func QualityBadgeEQ(v QualityBadge) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldQualityBadge, v))
}

// QualityBadgeNEQ applies the NEQ predicate on the "qualityBadge" field.
func QualityBadgeNEQ(v QualityBadge) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldQualityBadge, v))
}

// QualityBadgeIn applies the In predicate on the "qualityBadge" field.
func QualityBadgeIn(vs ...QualityBadge) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldQualityBadge, vs...))
}

// QualityBadgeNotIn applies the NotIn predicate on the "qualityBadge" field.
func QualityBadgeNotIn(vs ...QualityBadge) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldQualityBadge, vs...))
}

// IsVerifiedEQ applies the EQ predicate on the "isVerified" field.
func IsVerifiedEQ(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldIsVerified, v))
}

// IsVerifiedNEQ applies the NEQ predicate on the "isVerified" field.
func IsVerifiedNEQ(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldIsVerified, v))
}

// IsFeaturedEQ applies the EQ predicate on the "isFeatured" field.
func IsFeaturedEQ(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldIsFeatured, v))
}

// IsFeaturedNEQ applies the NEQ predicate on the "isFeatured" field.
func IsFeaturedNEQ(v bool) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldIsFeatured, v))
}

// ReviewBuildIdEQ applies the EQ predicate on the "reviewBuildId" field.
func ReviewBuildIdEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldReviewBuildId, v))
}

// ReviewBuildIdNEQ applies the NEQ predicate on the "reviewBuildId" field.
func ReviewBuildIdNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldReviewBuildId, v))
}

// ReviewBuildIdIn applies the In predicate on the "reviewBuildId" field.
func ReviewBuildIdIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldReviewBuildId, vs...))
}

// ReviewBuildIdNotIn applies the NotIn predicate on the "reviewBuildId" field.
func ReviewBuildIdNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldReviewBuildId, vs...))
}

// ReviewBuildIdGT applies the GT predicate on the "reviewBuildId" field.
func ReviewBuildIdGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldReviewBuildId, v))
}

// ReviewBuildIdGTE applies the GTE predicate on the "reviewBuildId" field.
func ReviewBuildIdGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldReviewBuildId, v))
}

// ReviewBuildIdLT applies the LT predicate on the "reviewBuildId" field.
func ReviewBuildIdLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldReviewBuildId, v))
}

// ReviewBuildIdLTE applies the LTE predicate on the "reviewBuildId" field.
func ReviewBuildIdLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldReviewBuildId, v))
}

// ReviewBuildIdContains applies the Contains predicate on the "reviewBuildId" field.
func ReviewBuildIdContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldReviewBuildId, v))
}

// ReviewBuildIdHasPrefix applies the HasPrefix predicate on the "reviewBuildId" field.
func ReviewBuildIdHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldReviewBuildId, v))
}

// ReviewBuildIdHasSuffix applies the HasSuffix predicate on the "reviewBuildId" field.
func ReviewBuildIdHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldReviewBuildId, v))
}

// ReviewBuildIdIsNil applies the IsNil predicate on the "reviewBuildId" field.
func ReviewBuildIdIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldReviewBuildId))
}

// ReviewBuildIdNotNil applies the NotNil predicate on the "reviewBuildId" field.
func ReviewBuildIdNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldReviewBuildId))
}

// ReviewBuildIdEqualFold applies the EqualFold predicate on the "reviewBuildId" field.
func ReviewBuildIdEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldReviewBuildId, v))
}

// ReviewBuildIdContainsFold applies the ContainsFold predicate on the "reviewBuildId" field.
func ReviewBuildIdContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldReviewBuildId, v))
}

// WebhookIdEQ applies the EQ predicate on the "webhookId" field.
func WebhookIdEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldWebhookId, v))
}

// WebhookIdNEQ applies the NEQ predicate on the "webhookId" field.
func WebhookIdNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldWebhookId, v))
}

// WebhookIdIn applies the In predicate on the "webhookId" field.
func WebhookIdIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldWebhookId, vs...))
}

// WebhookIdNotIn applies the NotIn predicate on the "webhookId" field.
func WebhookIdNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldWebhookId, vs...))
}

// WebhookIdGT applies the GT predicate on the "webhookId" field.
func WebhookIdGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldWebhookId, v))
}

// WebhookIdGTE applies the GTE predicate on the "webhookId" field.
func WebhookIdGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldWebhookId, v))
}

// WebhookIdLT applies the LT predicate on the "webhookId" field.
func WebhookIdLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldWebhookId, v))
}

// WebhookIdLTE applies the LTE predicate on the "webhookId" field.
func WebhookIdLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldWebhookId, v))
}

// WebhookIdContains applies the Contains predicate on the "webhookId" field.
func WebhookIdContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldWebhookId, v))
}

// WebhookIdHasPrefix applies the HasPrefix predicate on the "webhookId" field.
func WebhookIdHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldWebhookId, v))
}

// WebhookIdHasSuffix applies the HasSuffix predicate on the "webhookId" field.
func WebhookIdHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldWebhookId, v))
}

// WebhookIdIsNil applies the IsNil predicate on the "webhookId" field.
func WebhookIdIsNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldIsNull(FieldWebhookId))
}

// WebhookIdNotNil applies the NotNil predicate on the "webhookId" field.
func WebhookIdNotNil() predicate.Plugin {
	return predicate.Plugin(sql.FieldNotNull(FieldWebhookId))
}

// WebhookIdEqualFold applies the EqualFold predicate on the "webhookId" field.
func WebhookIdEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldWebhookId, v))
}

// WebhookIdContainsFold applies the ContainsFold predicate on the "webhookId" field.
func WebhookIdContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldWebhookId, v))
}

// CreatedAtEQ applies the EQ predicate on the "createdAt" field.
func CreatedAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "createdAt" field.
func CreatedAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "createdAt" field.
func CreatedAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "createdAt" field.
func CreatedAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "createdAt" field.
func CreatedAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "createdAt" field.
func CreatedAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "createdAt" field.
func CreatedAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "createdAt" field.
func CreatedAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updatedAt" field.
func UpdatedAtEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updatedAt" field.
func UpdatedAtNEQ(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updatedAt" field.
func UpdatedAtIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updatedAt" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updatedAt" field.
func UpdatedAtGT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updatedAt" field.
func UpdatedAtGTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updatedAt" field.
func UpdatedAtLT(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updatedAt" field.
func UpdatedAtLTE(v time.Time) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldUpdatedAt, v))
}

// AuthorIdEQ applies the EQ predicate on the "authorId" field.
func AuthorIdEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEQ(FieldAuthorId, v))
}

// AuthorIdNEQ applies the NEQ predicate on the "authorId" field.
func AuthorIdNEQ(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNEQ(FieldAuthorId, v))
}

// AuthorIdIn applies the In predicate on the "authorId" field.
func AuthorIdIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldIn(FieldAuthorId, vs...))
}

// AuthorIdNotIn applies the NotIn predicate on the "authorId" field.
func AuthorIdNotIn(vs ...string) predicate.Plugin {
	return predicate.Plugin(sql.FieldNotIn(FieldAuthorId, vs...))
}

// AuthorIdGT applies the GT predicate on the "authorId" field.
func AuthorIdGT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGT(FieldAuthorId, v))
}

// AuthorIdGTE applies the GTE predicate on the "authorId" field.
func AuthorIdGTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldGTE(FieldAuthorId, v))
}

// AuthorIdLT applies the LT predicate on the "authorId" field.
func AuthorIdLT(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLT(FieldAuthorId, v))
}

// AuthorIdLTE applies the LTE predicate on the "authorId" field.
func AuthorIdLTE(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldLTE(FieldAuthorId, v))
}

// AuthorIdContains applies the Contains predicate on the "authorId" field.
func AuthorIdContains(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContains(FieldAuthorId, v))
}

// AuthorIdHasPrefix applies the HasPrefix predicate on the "authorId" field.
func AuthorIdHasPrefix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasPrefix(FieldAuthorId, v))
}

// AuthorIdHasSuffix applies the HasSuffix predicate on the "authorId" field.
func AuthorIdHasSuffix(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldHasSuffix(FieldAuthorId, v))
}

// AuthorIdEqualFold applies the EqualFold predicate on the "authorId" field.
func AuthorIdEqualFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldEqualFold(FieldAuthorId, v))
}

// AuthorIdContainsFold applies the ContainsFold predicate on the "authorId" field.
func AuthorIdContainsFold(v string) predicate.Plugin {
	return predicate.Plugin(sql.FieldContainsFold(FieldAuthorId, v))
}

// HasAuthor applies the HasEdge predicate on the "author" edge.
func HasAuthor() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, AuthorTable, AuthorColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAuthorWith applies the HasEdge predicate on the "author" edge with a given conditions (other predicates).
func HasAuthorWith(preds ...predicate.User) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newAuthorStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasVersions applies the HasEdge predicate on the "versions" edge.
func HasVersions() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, VersionsTable, VersionsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasVersionsWith applies the HasEdge predicate on the "versions" edge with a given conditions (other predicates).
func HasVersionsWith(preds ...predicate.Version) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newVersionsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasBuilds applies the HasEdge predicate on the "builds" edge.
func HasBuilds() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, BuildsTable, BuildsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasBuildsWith applies the HasEdge predicate on the "builds" edge with a given conditions (other predicates).
func HasBuildsWith(preds ...predicate.Build) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newBuildsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReviews applies the HasEdge predicate on the "reviews" edge.
func HasReviews() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ReviewsTable, ReviewsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReviewsWith applies the HasEdge predicate on the "reviews" edge with a given conditions (other predicates).
func HasReviewsWith(preds ...predicate.Review) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newReviewsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasReports applies the HasEdge predicate on the "reports" edge.
func HasReports() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ReportsTable, ReportsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasReportsWith applies the HasEdge predicate on the "reports" edge with a given conditions (other predicates).
func HasReportsWith(preds ...predicate.Report) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newReportsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasRatings applies the HasEdge predicate on the "ratings" edge.
func HasRatings() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, RatingsTable, RatingsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasRatingsWith applies the HasEdge predicate on the "ratings" edge with a given conditions (other predicates).
func HasRatingsWith(preds ...predicate.Rating) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newRatingsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasComments applies the HasEdge predicate on the "comments" edge.
func HasComments() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, CommentsTable, CommentsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasCommentsWith applies the HasEdge predicate on the "comments" edge with a given conditions (other predicates).
func HasCommentsWith(preds ...predicate.PluginComment) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newCommentsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAutoChecks applies the HasEdge predicate on the "autoChecks" edge.
func HasAutoChecks() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AutoChecksTable, AutoChecksColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAutoChecksWith applies the HasEdge predicate on the "autoChecks" edge with a given conditions (other predicates).
func HasAutoChecksWith(preds ...predicate.AutoCheck) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newAutoChecksStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasModerationLogs applies the HasEdge predicate on the "moderationLogs" edge.
func HasModerationLogs() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, ModerationLogsTable, ModerationLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasModerationLogsWith applies the HasEdge predicate on the "moderationLogs" edge with a given conditions (other predicates).
func HasModerationLogsWith(preds ...predicate.ModerationLog) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newModerationLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAnalytics applies the HasEdge predicate on the "analytics" edge.
func HasAnalytics() predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, AnalyticsTable, AnalyticsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAnalyticsWith applies the HasEdge predicate on the "analytics" edge with a given conditions (other predicates).
func HasAnalyticsWith(preds ...predicate.PluginAnalytics) predicate.Plugin {
	return predicate.Plugin(func(s *sql.Selector) {
		step := newAnalyticsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.Plugin) predicate.Plugin {
	return predicate.Plugin(sql.NotPredicates(p))
}
