// Code generated by ent, DO NOT EDIT.

package version

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the version type in the database.
	Label = "version"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldChangelog holds the string denoting the changelog field in the database.
	FieldChangelog = "changelog"
	// FieldLongDescription holds the string denoting the longdescription field in the database.
	FieldLongDescription = "long_description"
	// FieldFileUrl holds the string denoting the fileurl field in the database.
	FieldFileUrl = "file_url"
	// FieldFileName holds the string denoting the filename field in the database.
	FieldFileName = "file_name"
	// FieldFileSize holds the string denoting the filesize field in the database.
	FieldFileSize = "file_size"
	// FieldFileHash holds the string denoting the filehash field in the database.
	FieldFileHash = "file_hash"
	// FieldMinApiVersion holds the string denoting the minapiversion field in the database.
	FieldMinApiVersion = "min_api_version"
	// FieldSupportedApis holds the string denoting the supportedapis field in the database.
	FieldSupportedApis = "supported_apis"
	// FieldDownloads holds the string denoting the downloads field in the database.
	FieldDownloads = "downloads"
	// FieldIsLatest holds the string denoting the islatest field in the database.
	FieldIsLatest = "is_latest"
	// FieldIsPreRelease holds the string denoting the isprerelease field in the database.
	FieldIsPreRelease = "is_pre_release"
	// FieldStatus holds the string denoting the status field in the database.
	FieldStatus = "status"
	// FieldStatusReason holds the string denoting the statusreason field in the database.
	FieldStatusReason = "status_reason"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldVtScanId holds the string denoting the vtscanid field in the database.
	FieldVtScanId = "vt_scan_id"
	// FieldVtStatus holds the string denoting the vtstatus field in the database.
	FieldVtStatus = "vt_status"
	// FieldVtMalicious holds the string denoting the vtmalicious field in the database.
	FieldVtMalicious = "vt_malicious"
	// FieldVtSuspicious holds the string denoting the vtsuspicious field in the database.
	FieldVtSuspicious = "vt_suspicious"
	// FieldVtUndetected holds the string denoting the vtundetected field in the database.
	FieldVtUndetected = "vt_undetected"
	// FieldVtTotal holds the string denoting the vttotal field in the database.
	FieldVtTotal = "vt_total"
	// FieldVtPermalink holds the string denoting the vtpermalink field in the database.
	FieldVtPermalink = "vt_permalink"
	// FieldVtScanDate holds the string denoting the vtscandate field in the database.
	FieldVtScanDate = "vt_scan_date"
	// FieldPluginId holds the string denoting the pluginid field in the database.
	FieldPluginId = "plugin_id"
	// EdgePlugin holds the string denoting the plugin edge name in mutations.
	EdgePlugin = "plugin"
	// EdgeDependencies holds the string denoting the dependencies edge name in mutations.
	EdgeDependencies = "dependencies"
	// EdgeProducers holds the string denoting the producers edge name in mutations.
	EdgeProducers = "producers"
	// Table holds the table name of the version in the database.
	Table = "versions"
	// PluginTable is the table that holds the plugin relation/edge.
	PluginTable = "versions"
	// PluginInverseTable is the table name for the Plugin entity.
	// It exists in this package in order to avoid circular dependency with the "plugin" package.
	PluginInverseTable = "plugins"
	// PluginColumn is the table column denoting the plugin relation/edge.
	PluginColumn = "plugin_id"
	// DependenciesTable is the table that holds the dependencies relation/edge.
	DependenciesTable = "dependencies"
	// DependenciesInverseTable is the table name for the Dependency entity.
	// It exists in this package in order to avoid circular dependency with the "dependency" package.
	DependenciesInverseTable = "dependencies"
	// DependenciesColumn is the table column denoting the dependencies relation/edge.
	DependenciesColumn = "version_id"
	// ProducersTable is the table that holds the producers relation/edge.
	ProducersTable = "producers"
	// ProducersInverseTable is the table name for the Producer entity.
	// It exists in this package in order to avoid circular dependency with the "producer" package.
	ProducersInverseTable = "producers"
	// ProducersColumn is the table column denoting the producers relation/edge.
	ProducersColumn = "version_id"
)

// Columns holds all SQL columns for version fields.
var Columns = []string{
	FieldID,
	FieldVersion,
	FieldChangelog,
	FieldLongDescription,
	FieldFileUrl,
	FieldFileName,
	FieldFileSize,
	FieldFileHash,
	FieldMinApiVersion,
	FieldSupportedApis,
	FieldDownloads,
	FieldIsLatest,
	FieldIsPreRelease,
	FieldStatus,
	FieldStatusReason,
	FieldCreatedAt,
	FieldVtScanId,
	FieldVtStatus,
	FieldVtMalicious,
	FieldVtSuspicious,
	FieldVtUndetected,
	FieldVtTotal,
	FieldVtPermalink,
	FieldVtScanDate,
	FieldPluginId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultDownloads holds the default value on creation for the "downloads" field.
	DefaultDownloads int
	// DefaultIsLatest holds the default value on creation for the "isLatest" field.
	DefaultIsLatest bool
	// DefaultIsPreRelease holds the default value on creation for the "isPreRelease" field.
	DefaultIsPreRelease bool
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Status defines the type for the "status" enum field.
type Status string

// StatusPENDING is the default value of the Status enum.
const DefaultStatus = StatusPENDING

// Status values.
const (
	StatusDRAFT          Status = "DRAFT"
	StatusPENDING        Status = "PENDING"
	StatusAUTO_PASSED    Status = "AUTO_PASSED"
	StatusSANDBOX_PASSED Status = "SANDBOX_PASSED"
	StatusAPPROVED       Status = "APPROVED"
	StatusREJECTED       Status = "REJECTED"
)

func (s Status) String() string {
	return string(s)
}

// StatusValidator is a validator for the "status" field enum values. It is called by the builders before save.
func StatusValidator(s Status) error {
	switch s {
	case StatusDRAFT, StatusPENDING, StatusAUTO_PASSED, StatusSANDBOX_PASSED, StatusAPPROVED, StatusREJECTED:
		return nil
	default:
		return fmt.Errorf("version: invalid enum value for status field: %q", s)
	}
}

// OrderOption defines the ordering options for the Version queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByChangelog orders the results by the changelog field.
func ByChangelog(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldChangelog, opts...).ToFunc()
}

// ByLongDescription orders the results by the longDescription field.
func ByLongDescription(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldLongDescription, opts...).ToFunc()
}

// ByFileUrl orders the results by the fileUrl field.
func ByFileUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileUrl, opts...).ToFunc()
}

// ByFileName orders the results by the fileName field.
func ByFileName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileName, opts...).ToFunc()
}

// ByFileSize orders the results by the fileSize field.
func ByFileSize(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileSize, opts...).ToFunc()
}

// ByFileHash orders the results by the fileHash field.
func ByFileHash(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldFileHash, opts...).ToFunc()
}

// ByMinApiVersion orders the results by the minApiVersion field.
func ByMinApiVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldMinApiVersion, opts...).ToFunc()
}

// ByDownloads orders the results by the downloads field.
func ByDownloads(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDownloads, opts...).ToFunc()
}

// ByIsLatest orders the results by the isLatest field.
func ByIsLatest(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsLatest, opts...).ToFunc()
}

// ByIsPreRelease orders the results by the isPreRelease field.
func ByIsPreRelease(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldIsPreRelease, opts...).ToFunc()
}

// ByStatus orders the results by the status field.
func ByStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatus, opts...).ToFunc()
}

// ByStatusReason orders the results by the statusReason field.
func ByStatusReason(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldStatusReason, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByVtScanId orders the results by the vtScanId field.
func ByVtScanId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVtScanId, opts...).ToFunc()
}

// ByVtStatus orders the results by the vtStatus field.
func ByVtStatus(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVtStatus, opts...).ToFunc()
}

// ByVtMalicious orders the results by the vtMalicious field.
func ByVtMalicious(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVtMalicious, opts...).ToFunc()
}

// ByVtSuspicious orders the results by the vtSuspicious field.
func ByVtSuspicious(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVtSuspicious, opts...).ToFunc()
}

// ByVtUndetected orders the results by the vtUndetected field.
func ByVtUndetected(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVtUndetected, opts...).ToFunc()
}

// ByVtTotal orders the results by the vtTotal field.
func ByVtTotal(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVtTotal, opts...).ToFunc()
}

// ByVtPermalink orders the results by the vtPermalink field.
func ByVtPermalink(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVtPermalink, opts...).ToFunc()
}

// ByVtScanDate orders the results by the vtScanDate field.
func ByVtScanDate(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVtScanDate, opts...).ToFunc()
}

// ByPluginId orders the results by the pluginId field.
func ByPluginId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldPluginId, opts...).ToFunc()
}

// ByPluginField orders the results by plugin field.
func ByPluginField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPluginStep(), sql.OrderByField(field, opts...))
	}
}

// ByDependenciesCount orders the results by dependencies count.
func ByDependenciesCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newDependenciesStep(), opts...)
	}
}

// ByDependencies orders the results by dependencies terms.
func ByDependencies(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newDependenciesStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByProducersCount orders the results by producers count.
func ByProducersCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newProducersStep(), opts...)
	}
}

// ByProducers orders the results by producers terms.
func ByProducers(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newProducersStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPluginStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PluginInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, PluginTable, PluginColumn),
	)
}
func newDependenciesStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(DependenciesInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, DependenciesTable, DependenciesColumn),
	)
}
func newProducersStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ProducersInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ProducersTable, ProducersColumn),
	)
}
