// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/EndGitHQ/endgit-core/ent/autocheck"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
)

// AutoCheck is the model entity for the AutoCheck schema.
type AutoCheck struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Tier holds the value of the "tier" field.
	Tier autocheck.Tier `json:"tier,omitempty"`
	// Status holds the value of the "status" field.
	Status autocheck.Status `json:"status,omitempty"`
	// StructureOk holds the value of the "structureOk" field.
	StructureOk *bool `json:"structureOk,omitempty"`
	// DepsOk holds the value of the "depsOk" field.
	DepsOk *bool `json:"depsOk,omitempty"`
	// SemverOk holds the value of the "semverOk" field.
	SemverOk *bool `json:"semverOk,omitempty"`
	// FileSizeOk holds the value of the "fileSizeOk" field.
	FileSizeOk *bool `json:"fileSizeOk,omitempty"`
	// SecurityScanOk holds the value of the "securityScanOk" field.
	SecurityScanOk *bool `json:"securityScanOk,omitempty"`
	// SandboxLoadOk holds the value of the "sandboxLoadOk" field.
	SandboxLoadOk *bool `json:"sandboxLoadOk,omitempty"`
	// SandboxCrashFree holds the value of the "sandboxCrashFree" field.
	SandboxCrashFree *bool `json:"sandboxCrashFree,omitempty"`
	// Logs holds the value of the "logs" field.
	Logs *string `json:"logs,omitempty"`
	// Score holds the value of the "score" field.
	Score *float64 `json:"score,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// FinishedAt holds the value of the "finishedAt" field.
	FinishedAt *time.Time `json:"finishedAt,omitempty"`
	// PluginId holds the value of the "pluginId" field.
	PluginId string `json:"pluginId,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the AutoCheckQuery when eager-loading is set.
	Edges        AutoCheckEdges `json:"edges"`
	selectValues sql.SelectValues
}

// AutoCheckEdges holds the relations/edges for other nodes in the graph.
type AutoCheckEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e AutoCheckEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*AutoCheck) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case autocheck.FieldStructureOk, autocheck.FieldDepsOk, autocheck.FieldSemverOk, autocheck.FieldFileSizeOk, autocheck.FieldSecurityScanOk, autocheck.FieldSandboxLoadOk, autocheck.FieldSandboxCrashFree:
			values[i] = new(sql.NullBool)
		case autocheck.FieldScore:
			values[i] = new(sql.NullFloat64)
		case autocheck.FieldID, autocheck.FieldTier, autocheck.FieldStatus, autocheck.FieldLogs, autocheck.FieldPluginId:
			values[i] = new(sql.NullString)
		case autocheck.FieldCreatedAt, autocheck.FieldFinishedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the AutoCheck fields.
func (_m *AutoCheck) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case autocheck.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case autocheck.FieldTier:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field tier", values[i])
			} else if value.Valid {
				_m.Tier = autocheck.Tier(value.String)
			}
		case autocheck.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = autocheck.Status(value.String)
			}
		case autocheck.FieldStructureOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field structureOk", values[i])
			} else if value.Valid {
				_m.StructureOk = new(bool)
				*_m.StructureOk = value.Bool
			}
		case autocheck.FieldDepsOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field depsOk", values[i])
			} else if value.Valid {
				_m.DepsOk = new(bool)
				*_m.DepsOk = value.Bool
			}
		case autocheck.FieldSemverOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field semverOk", values[i])
			} else if value.Valid {
				_m.SemverOk = new(bool)
				*_m.SemverOk = value.Bool
			}
		case autocheck.FieldFileSizeOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field fileSizeOk", values[i])
			} else if value.Valid {
				_m.FileSizeOk = new(bool)
				*_m.FileSizeOk = value.Bool
			}
		case autocheck.FieldSecurityScanOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field securityScanOk", values[i])
			} else if value.Valid {
				_m.SecurityScanOk = new(bool)
				*_m.SecurityScanOk = value.Bool
			}
		case autocheck.FieldSandboxLoadOk:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sandboxLoadOk", values[i])
			} else if value.Valid {
				_m.SandboxLoadOk = new(bool)
				*_m.SandboxLoadOk = value.Bool
			}
		case autocheck.FieldSandboxCrashFree:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field sandboxCrashFree", values[i])
			} else if value.Valid {
				_m.SandboxCrashFree = new(bool)
				*_m.SandboxCrashFree = value.Bool
			}
		case autocheck.FieldLogs:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field logs", values[i])
			} else if value.Valid {
				_m.Logs = new(string)
				*_m.Logs = value.String
			}
		case autocheck.FieldScore:
			if value, ok := values[i].(*sql.NullFloat64); !ok {
				return fmt.Errorf("unexpected type %T for field score", values[i])
			} else if value.Valid {
				_m.Score = new(float64)
				*_m.Score = value.Float64
			}
		case autocheck.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case autocheck.FieldFinishedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field finishedAt", values[i])
			} else if value.Valid {
				_m.FinishedAt = new(time.Time)
				*_m.FinishedAt = value.Time
			}
		case autocheck.FieldPluginId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pluginId", values[i])
			} else if value.Valid {
				_m.PluginId = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the AutoCheck.
// This includes values selected through modifiers, order, etc.
func (_m *AutoCheck) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugin queries the "plugin" edge of the AutoCheck entity.
func (_m *AutoCheck) QueryPlugin() *PluginQuery {
	return NewAutoCheckClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this AutoCheck.
// Note that you need to call AutoCheck.Unwrap() before calling this method if this AutoCheck
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *AutoCheck) Update() *AutoCheckUpdateOne {
	return NewAutoCheckClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the AutoCheck entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *AutoCheck) Unwrap() *AutoCheck {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: AutoCheck is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *AutoCheck) String() string {
	var builder strings.Builder
	builder.WriteString("AutoCheck(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("tier=")
	builder.WriteString(fmt.Sprintf("%v", _m.Tier))
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(fmt.Sprintf("%v", _m.Status))
	builder.WriteString(", ")
	if v := _m.StructureOk; v != nil {
		builder.WriteString("structureOk=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.DepsOk; v != nil {
		builder.WriteString("depsOk=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SemverOk; v != nil {
		builder.WriteString("semverOk=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.FileSizeOk; v != nil {
		builder.WriteString("fileSizeOk=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SecurityScanOk; v != nil {
		builder.WriteString("securityScanOk=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SandboxLoadOk; v != nil {
		builder.WriteString("sandboxLoadOk=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.SandboxCrashFree; v != nil {
		builder.WriteString("sandboxCrashFree=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	if v := _m.Logs; v != nil {
		builder.WriteString("logs=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Score; v != nil {
		builder.WriteString("score=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.FinishedAt; v != nil {
		builder.WriteString("finishedAt=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	builder.WriteString("pluginId=")
	builder.WriteString(_m.PluginId)
	builder.WriteByte(')')
	return builder.String()
}

// AutoChecks is a parsable slice of AutoCheck.
type AutoChecks []*AutoCheck
