// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/autocheck"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
)

// AutoCheckUpdate is the builder for updating AutoCheck entities.
type AutoCheckUpdate struct {
	config
	hooks    []Hook
	mutation *AutoCheckMutation
}

// Where appends a list predicates to the AutoCheckUpdate builder.
func (_u *AutoCheckUpdate) Where(ps ...predicate.AutoCheck) *AutoCheckUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetTier sets the "tier" field.
func (_u *AutoCheckUpdate) SetTier(v autocheck.Tier) *AutoCheckUpdate {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableTier(v *autocheck.Tier) *AutoCheckUpdate {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AutoCheckUpdate) SetStatus(v autocheck.Status) *AutoCheckUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableStatus(v *autocheck.Status) *AutoCheckUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStructureOk sets the "structureOk" field.
func (_u *AutoCheckUpdate) SetStructureOk(v bool) *AutoCheckUpdate {
	_u.mutation.SetStructureOk(v)
	return _u
}

// SetNillableStructureOk sets the "structureOk" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableStructureOk(v *bool) *AutoCheckUpdate {
	if v != nil {
		_u.SetStructureOk(*v)
	}
	return _u
}

// ClearStructureOk clears the value of the "structureOk" field.
func (_u *AutoCheckUpdate) ClearStructureOk() *AutoCheckUpdate {
	_u.mutation.ClearStructureOk()
	return _u
}

// SetDepsOk sets the "depsOk" field.
func (_u *AutoCheckUpdate) SetDepsOk(v bool) *AutoCheckUpdate {
	_u.mutation.SetDepsOk(v)
	return _u
}

// SetNillableDepsOk sets the "depsOk" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableDepsOk(v *bool) *AutoCheckUpdate {
	if v != nil {
		_u.SetDepsOk(*v)
	}
	return _u
}

// ClearDepsOk clears the value of the "depsOk" field.
func (_u *AutoCheckUpdate) ClearDepsOk() *AutoCheckUpdate {
	_u.mutation.ClearDepsOk()
	return _u
}

// SetSemverOk sets the "semverOk" field.
func (_u *AutoCheckUpdate) SetSemverOk(v bool) *AutoCheckUpdate {
	_u.mutation.SetSemverOk(v)
	return _u
}

// SetNillableSemverOk sets the "semverOk" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableSemverOk(v *bool) *AutoCheckUpdate {
	if v != nil {
		_u.SetSemverOk(*v)
	}
	return _u
}

// ClearSemverOk clears the value of the "semverOk" field.
func (_u *AutoCheckUpdate) ClearSemverOk() *AutoCheckUpdate {
	_u.mutation.ClearSemverOk()
	return _u
}

// SetFileSizeOk sets the "fileSizeOk" field.
func (_u *AutoCheckUpdate) SetFileSizeOk(v bool) *AutoCheckUpdate {
	_u.mutation.SetFileSizeOk(v)
	return _u
}

// SetNillableFileSizeOk sets the "fileSizeOk" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableFileSizeOk(v *bool) *AutoCheckUpdate {
	if v != nil {
		_u.SetFileSizeOk(*v)
	}
	return _u
}

// ClearFileSizeOk clears the value of the "fileSizeOk" field.
func (_u *AutoCheckUpdate) ClearFileSizeOk() *AutoCheckUpdate {
	_u.mutation.ClearFileSizeOk()
	return _u
}

// SetSecurityScanOk sets the "securityScanOk" field.
func (_u *AutoCheckUpdate) SetSecurityScanOk(v bool) *AutoCheckUpdate {
	_u.mutation.SetSecurityScanOk(v)
	return _u
}

// SetNillableSecurityScanOk sets the "securityScanOk" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableSecurityScanOk(v *bool) *AutoCheckUpdate {
	if v != nil {
		_u.SetSecurityScanOk(*v)
	}
	return _u
}

// ClearSecurityScanOk clears the value of the "securityScanOk" field.
func (_u *AutoCheckUpdate) ClearSecurityScanOk() *AutoCheckUpdate {
	_u.mutation.ClearSecurityScanOk()
	return _u
}

// SetSandboxLoadOk sets the "sandboxLoadOk" field.
func (_u *AutoCheckUpdate) SetSandboxLoadOk(v bool) *AutoCheckUpdate {
	_u.mutation.SetSandboxLoadOk(v)
	return _u
}

// SetNillableSandboxLoadOk sets the "sandboxLoadOk" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableSandboxLoadOk(v *bool) *AutoCheckUpdate {
	if v != nil {
		_u.SetSandboxLoadOk(*v)
	}
	return _u
}

// ClearSandboxLoadOk clears the value of the "sandboxLoadOk" field.
func (_u *AutoCheckUpdate) ClearSandboxLoadOk() *AutoCheckUpdate {
	_u.mutation.ClearSandboxLoadOk()
	return _u
}

// SetSandboxCrashFree sets the "sandboxCrashFree" field.
func (_u *AutoCheckUpdate) SetSandboxCrashFree(v bool) *AutoCheckUpdate {
	_u.mutation.SetSandboxCrashFree(v)
	return _u
}

// SetNillableSandboxCrashFree sets the "sandboxCrashFree" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableSandboxCrashFree(v *bool) *AutoCheckUpdate {
	if v != nil {
		_u.SetSandboxCrashFree(*v)
	}
	return _u
}

// ClearSandboxCrashFree clears the value of the "sandboxCrashFree" field.
func (_u *AutoCheckUpdate) ClearSandboxCrashFree() *AutoCheckUpdate {
	_u.mutation.ClearSandboxCrashFree()
	return _u
}

// SetLogs sets the "logs" field.
func (_u *AutoCheckUpdate) SetLogs(v string) *AutoCheckUpdate {
	_u.mutation.SetLogs(v)
	return _u
}

// SetNillableLogs sets the "logs" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableLogs(v *string) *AutoCheckUpdate {
	if v != nil {
		_u.SetLogs(*v)
	}
	return _u
}

// ClearLogs clears the value of the "logs" field.
func (_u *AutoCheckUpdate) ClearLogs() *AutoCheckUpdate {
	_u.mutation.ClearLogs()
	return _u
}

// SetScore sets the "score" field.
func (_u *AutoCheckUpdate) SetScore(v float64) *AutoCheckUpdate {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableScore(v *float64) *AutoCheckUpdate {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *AutoCheckUpdate) AddScore(v float64) *AutoCheckUpdate {
	_u.mutation.AddScore(v)
	return _u
}

// ClearScore clears the value of the "score" field.
func (_u *AutoCheckUpdate) ClearScore() *AutoCheckUpdate {
	_u.mutation.ClearScore()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *AutoCheckUpdate) SetCreatedAt(v time.Time) *AutoCheckUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableCreatedAt(v *time.Time) *AutoCheckUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finishedAt" field.
func (_u *AutoCheckUpdate) SetFinishedAt(v time.Time) *AutoCheckUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finishedAt" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillableFinishedAt(v *time.Time) *AutoCheckUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finishedAt" field.
func (_u *AutoCheckUpdate) ClearFinishedAt() *AutoCheckUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *AutoCheckUpdate) SetPluginId(v string) *AutoCheckUpdate {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *AutoCheckUpdate) SetNillablePluginId(v *string) *AutoCheckUpdate {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *AutoCheckUpdate) SetPluginID(id string) *AutoCheckUpdate {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *AutoCheckUpdate) SetPlugin(v *Plugin) *AutoCheckUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the AutoCheckMutation object of the builder.
func (_u *AutoCheckUpdate) Mutation() *AutoCheckMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *AutoCheckUpdate) ClearPlugin() *AutoCheckUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *AutoCheckUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AutoCheckUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *AutoCheckUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AutoCheckUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AutoCheckUpdate) check() error {
	if v, ok := _u.mutation.Tier(); ok {
		if err := autocheck.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "AutoCheck.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := autocheck.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AutoCheck.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AutoCheck.plugin"`)
	}
	return nil
}

func (_u *AutoCheckUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(autocheck.Table, autocheck.Columns, sqlgraph.NewFieldSpec(autocheck.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(autocheck.FieldTier, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(autocheck.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StructureOk(); ok {
		_spec.SetField(autocheck.FieldStructureOk, field.TypeBool, value)
	}
	if _u.mutation.StructureOkCleared() {
		_spec.ClearField(autocheck.FieldStructureOk, field.TypeBool)
	}
	if value, ok := _u.mutation.DepsOk(); ok {
		_spec.SetField(autocheck.FieldDepsOk, field.TypeBool, value)
	}
	if _u.mutation.DepsOkCleared() {
		_spec.ClearField(autocheck.FieldDepsOk, field.TypeBool)
	}
	if value, ok := _u.mutation.SemverOk(); ok {
		_spec.SetField(autocheck.FieldSemverOk, field.TypeBool, value)
	}
	if _u.mutation.SemverOkCleared() {
		_spec.ClearField(autocheck.FieldSemverOk, field.TypeBool)
	}
	if value, ok := _u.mutation.FileSizeOk(); ok {
		_spec.SetField(autocheck.FieldFileSizeOk, field.TypeBool, value)
	}
	if _u.mutation.FileSizeOkCleared() {
		_spec.ClearField(autocheck.FieldFileSizeOk, field.TypeBool)
	}
	if value, ok := _u.mutation.SecurityScanOk(); ok {
		_spec.SetField(autocheck.FieldSecurityScanOk, field.TypeBool, value)
	}
	if _u.mutation.SecurityScanOkCleared() {
		_spec.ClearField(autocheck.FieldSecurityScanOk, field.TypeBool)
	}
	if value, ok := _u.mutation.SandboxLoadOk(); ok {
		_spec.SetField(autocheck.FieldSandboxLoadOk, field.TypeBool, value)
	}
	if _u.mutation.SandboxLoadOkCleared() {
		_spec.ClearField(autocheck.FieldSandboxLoadOk, field.TypeBool)
	}
	if value, ok := _u.mutation.SandboxCrashFree(); ok {
		_spec.SetField(autocheck.FieldSandboxCrashFree, field.TypeBool, value)
	}
	if _u.mutation.SandboxCrashFreeCleared() {
		_spec.ClearField(autocheck.FieldSandboxCrashFree, field.TypeBool)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(autocheck.FieldLogs, field.TypeString, value)
	}
	if _u.mutation.LogsCleared() {
		_spec.ClearField(autocheck.FieldLogs, field.TypeString)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(autocheck.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(autocheck.FieldScore, field.TypeFloat64, value)
	}
	if _u.mutation.ScoreCleared() {
		_spec.ClearField(autocheck.FieldScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(autocheck.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(autocheck.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(autocheck.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   autocheck.PluginTable,
			Columns: []string{autocheck.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   autocheck.PluginTable,
			Columns: []string{autocheck.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{autocheck.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// AutoCheckUpdateOne is the builder for updating a single AutoCheck entity.
type AutoCheckUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *AutoCheckMutation
}

// SetTier sets the "tier" field.
func (_u *AutoCheckUpdateOne) SetTier(v autocheck.Tier) *AutoCheckUpdateOne {
	_u.mutation.SetTier(v)
	return _u
}

// SetNillableTier sets the "tier" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableTier(v *autocheck.Tier) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetTier(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *AutoCheckUpdateOne) SetStatus(v autocheck.Status) *AutoCheckUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableStatus(v *autocheck.Status) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetStructureOk sets the "structureOk" field.
func (_u *AutoCheckUpdateOne) SetStructureOk(v bool) *AutoCheckUpdateOne {
	_u.mutation.SetStructureOk(v)
	return _u
}

// SetNillableStructureOk sets the "structureOk" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableStructureOk(v *bool) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetStructureOk(*v)
	}
	return _u
}

// ClearStructureOk clears the value of the "structureOk" field.
func (_u *AutoCheckUpdateOne) ClearStructureOk() *AutoCheckUpdateOne {
	_u.mutation.ClearStructureOk()
	return _u
}

// SetDepsOk sets the "depsOk" field.
func (_u *AutoCheckUpdateOne) SetDepsOk(v bool) *AutoCheckUpdateOne {
	_u.mutation.SetDepsOk(v)
	return _u
}

// SetNillableDepsOk sets the "depsOk" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableDepsOk(v *bool) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetDepsOk(*v)
	}
	return _u
}

// ClearDepsOk clears the value of the "depsOk" field.
func (_u *AutoCheckUpdateOne) ClearDepsOk() *AutoCheckUpdateOne {
	_u.mutation.ClearDepsOk()
	return _u
}

// SetSemverOk sets the "semverOk" field.
func (_u *AutoCheckUpdateOne) SetSemverOk(v bool) *AutoCheckUpdateOne {
	_u.mutation.SetSemverOk(v)
	return _u
}

// SetNillableSemverOk sets the "semverOk" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableSemverOk(v *bool) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetSemverOk(*v)
	}
	return _u
}

// ClearSemverOk clears the value of the "semverOk" field.
func (_u *AutoCheckUpdateOne) ClearSemverOk() *AutoCheckUpdateOne {
	_u.mutation.ClearSemverOk()
	return _u
}

// SetFileSizeOk sets the "fileSizeOk" field.
func (_u *AutoCheckUpdateOne) SetFileSizeOk(v bool) *AutoCheckUpdateOne {
	_u.mutation.SetFileSizeOk(v)
	return _u
}

// SetNillableFileSizeOk sets the "fileSizeOk" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableFileSizeOk(v *bool) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetFileSizeOk(*v)
	}
	return _u
}

// ClearFileSizeOk clears the value of the "fileSizeOk" field.
func (_u *AutoCheckUpdateOne) ClearFileSizeOk() *AutoCheckUpdateOne {
	_u.mutation.ClearFileSizeOk()
	return _u
}

// SetSecurityScanOk sets the "securityScanOk" field.
func (_u *AutoCheckUpdateOne) SetSecurityScanOk(v bool) *AutoCheckUpdateOne {
	_u.mutation.SetSecurityScanOk(v)
	return _u
}

// SetNillableSecurityScanOk sets the "securityScanOk" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableSecurityScanOk(v *bool) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetSecurityScanOk(*v)
	}
	return _u
}

// ClearSecurityScanOk clears the value of the "securityScanOk" field.
func (_u *AutoCheckUpdateOne) ClearSecurityScanOk() *AutoCheckUpdateOne {
	_u.mutation.ClearSecurityScanOk()
	return _u
}

// SetSandboxLoadOk sets the "sandboxLoadOk" field.
func (_u *AutoCheckUpdateOne) SetSandboxLoadOk(v bool) *AutoCheckUpdateOne {
	_u.mutation.SetSandboxLoadOk(v)
	return _u
}

// SetNillableSandboxLoadOk sets the "sandboxLoadOk" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableSandboxLoadOk(v *bool) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetSandboxLoadOk(*v)
	}
	return _u
}

// ClearSandboxLoadOk clears the value of the "sandboxLoadOk" field.
func (_u *AutoCheckUpdateOne) ClearSandboxLoadOk() *AutoCheckUpdateOne {
	_u.mutation.ClearSandboxLoadOk()
	return _u
}

// SetSandboxCrashFree sets the "sandboxCrashFree" field.
func (_u *AutoCheckUpdateOne) SetSandboxCrashFree(v bool) *AutoCheckUpdateOne {
	_u.mutation.SetSandboxCrashFree(v)
	return _u
}

// SetNillableSandboxCrashFree sets the "sandboxCrashFree" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableSandboxCrashFree(v *bool) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetSandboxCrashFree(*v)
	}
	return _u
}

// ClearSandboxCrashFree clears the value of the "sandboxCrashFree" field.
func (_u *AutoCheckUpdateOne) ClearSandboxCrashFree() *AutoCheckUpdateOne {
	_u.mutation.ClearSandboxCrashFree()
	return _u
}

// SetLogs sets the "logs" field.
func (_u *AutoCheckUpdateOne) SetLogs(v string) *AutoCheckUpdateOne {
	_u.mutation.SetLogs(v)
	return _u
}

// SetNillableLogs sets the "logs" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableLogs(v *string) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetLogs(*v)
	}
	return _u
}

// ClearLogs clears the value of the "logs" field.
func (_u *AutoCheckUpdateOne) ClearLogs() *AutoCheckUpdateOne {
	_u.mutation.ClearLogs()
	return _u
}

// SetScore sets the "score" field.
func (_u *AutoCheckUpdateOne) SetScore(v float64) *AutoCheckUpdateOne {
	_u.mutation.ResetScore()
	_u.mutation.SetScore(v)
	return _u
}

// SetNillableScore sets the "score" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableScore(v *float64) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetScore(*v)
	}
	return _u
}

// AddScore adds value to the "score" field.
func (_u *AutoCheckUpdateOne) AddScore(v float64) *AutoCheckUpdateOne {
	_u.mutation.AddScore(v)
	return _u
}

// ClearScore clears the value of the "score" field.
func (_u *AutoCheckUpdateOne) ClearScore() *AutoCheckUpdateOne {
	_u.mutation.ClearScore()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *AutoCheckUpdateOne) SetCreatedAt(v time.Time) *AutoCheckUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableCreatedAt(v *time.Time) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finishedAt" field.
func (_u *AutoCheckUpdateOne) SetFinishedAt(v time.Time) *AutoCheckUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finishedAt" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillableFinishedAt(v *time.Time) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finishedAt" field.
func (_u *AutoCheckUpdateOne) ClearFinishedAt() *AutoCheckUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *AutoCheckUpdateOne) SetPluginId(v string) *AutoCheckUpdateOne {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *AutoCheckUpdateOne) SetNillablePluginId(v *string) *AutoCheckUpdateOne {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *AutoCheckUpdateOne) SetPluginID(id string) *AutoCheckUpdateOne {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *AutoCheckUpdateOne) SetPlugin(v *Plugin) *AutoCheckUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the AutoCheckMutation object of the builder.
func (_u *AutoCheckUpdateOne) Mutation() *AutoCheckMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *AutoCheckUpdateOne) ClearPlugin() *AutoCheckUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the AutoCheckUpdate builder.
func (_u *AutoCheckUpdateOne) Where(ps ...predicate.AutoCheck) *AutoCheckUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *AutoCheckUpdateOne) Select(field string, fields ...string) *AutoCheckUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated AutoCheck entity.
func (_u *AutoCheckUpdateOne) Save(ctx context.Context) (*AutoCheck, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *AutoCheckUpdateOne) SaveX(ctx context.Context) *AutoCheck {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *AutoCheckUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *AutoCheckUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *AutoCheckUpdateOne) check() error {
	if v, ok := _u.mutation.Tier(); ok {
		if err := autocheck.TierValidator(v); err != nil {
			return &ValidationError{Name: "tier", err: fmt.Errorf(`ent: validator failed for field "AutoCheck.tier": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := autocheck.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "AutoCheck.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "AutoCheck.plugin"`)
	}
	return nil
}

func (_u *AutoCheckUpdateOne) sqlSave(ctx context.Context) (_node *AutoCheck, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(autocheck.Table, autocheck.Columns, sqlgraph.NewFieldSpec(autocheck.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "AutoCheck.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, autocheck.FieldID)
		for _, f := range fields {
			if !autocheck.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != autocheck.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Tier(); ok {
		_spec.SetField(autocheck.FieldTier, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(autocheck.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.StructureOk(); ok {
		_spec.SetField(autocheck.FieldStructureOk, field.TypeBool, value)
	}
	if _u.mutation.StructureOkCleared() {
		_spec.ClearField(autocheck.FieldStructureOk, field.TypeBool)
	}
	if value, ok := _u.mutation.DepsOk(); ok {
		_spec.SetField(autocheck.FieldDepsOk, field.TypeBool, value)
	}
	if _u.mutation.DepsOkCleared() {
		_spec.ClearField(autocheck.FieldDepsOk, field.TypeBool)
	}
	if value, ok := _u.mutation.SemverOk(); ok {
		_spec.SetField(autocheck.FieldSemverOk, field.TypeBool, value)
	}
	if _u.mutation.SemverOkCleared() {
		_spec.ClearField(autocheck.FieldSemverOk, field.TypeBool)
	}
	if value, ok := _u.mutation.FileSizeOk(); ok {
		_spec.SetField(autocheck.FieldFileSizeOk, field.TypeBool, value)
	}
	if _u.mutation.FileSizeOkCleared() {
		_spec.ClearField(autocheck.FieldFileSizeOk, field.TypeBool)
	}
	if value, ok := _u.mutation.SecurityScanOk(); ok {
		_spec.SetField(autocheck.FieldSecurityScanOk, field.TypeBool, value)
	}
	if _u.mutation.SecurityScanOkCleared() {
		_spec.ClearField(autocheck.FieldSecurityScanOk, field.TypeBool)
	}
	if value, ok := _u.mutation.SandboxLoadOk(); ok {
		_spec.SetField(autocheck.FieldSandboxLoadOk, field.TypeBool, value)
	}
	if _u.mutation.SandboxLoadOkCleared() {
		_spec.ClearField(autocheck.FieldSandboxLoadOk, field.TypeBool)
	}
	if value, ok := _u.mutation.SandboxCrashFree(); ok {
		_spec.SetField(autocheck.FieldSandboxCrashFree, field.TypeBool, value)
	}
	if _u.mutation.SandboxCrashFreeCleared() {
		_spec.ClearField(autocheck.FieldSandboxCrashFree, field.TypeBool)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(autocheck.FieldLogs, field.TypeString, value)
	}
	if _u.mutation.LogsCleared() {
		_spec.ClearField(autocheck.FieldLogs, field.TypeString)
	}
	if value, ok := _u.mutation.Score(); ok {
		_spec.SetField(autocheck.FieldScore, field.TypeFloat64, value)
	}
	if value, ok := _u.mutation.AddedScore(); ok {
		_spec.AddField(autocheck.FieldScore, field.TypeFloat64, value)
	}
	if _u.mutation.ScoreCleared() {
		_spec.ClearField(autocheck.FieldScore, field.TypeFloat64)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(autocheck.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(autocheck.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(autocheck.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   autocheck.PluginTable,
			Columns: []string{autocheck.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   autocheck.PluginTable,
			Columns: []string{autocheck.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &AutoCheck{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{autocheck.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
