// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/build"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
)

// BuildUpdate is the builder for updating Build entities.
type BuildUpdate struct {
	config
	hooks    []Hook
	mutation *BuildMutation
}

// Where appends a list predicates to the BuildUpdate builder.
func (_u *BuildUpdate) Where(ps ...predicate.Build) *BuildUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetBuildNumber sets the "buildNumber" field.
func (_u *BuildUpdate) SetBuildNumber(v int) *BuildUpdate {
	_u.mutation.ResetBuildNumber()
	_u.mutation.SetBuildNumber(v)
	return _u
}

// SetNillableBuildNumber sets the "buildNumber" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableBuildNumber(v *int) *BuildUpdate {
	if v != nil {
		_u.SetBuildNumber(*v)
	}
	return _u
}

// AddBuildNumber adds value to the "buildNumber" field.
func (_u *BuildUpdate) AddBuildNumber(v int) *BuildUpdate {
	_u.mutation.AddBuildNumber(v)
	return _u
}

// SetCommitHash sets the "commitHash" field.
func (_u *BuildUpdate) SetCommitHash(v string) *BuildUpdate {
	_u.mutation.SetCommitHash(v)
	return _u
}

// SetNillableCommitHash sets the "commitHash" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableCommitHash(v *string) *BuildUpdate {
	if v != nil {
		_u.SetCommitHash(*v)
	}
	return _u
}

// ClearCommitHash clears the value of the "commitHash" field.
func (_u *BuildUpdate) ClearCommitHash() *BuildUpdate {
	_u.mutation.ClearCommitHash()
	return _u
}

// SetBranch sets the "branch" field.
func (_u *BuildUpdate) SetBranch(v string) *BuildUpdate {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableBranch(v *string) *BuildUpdate {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BuildUpdate) SetStatus(v build.Status) *BuildUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableStatus(v *build.Status) *BuildUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsRelease sets the "isRelease" field.
func (_u *BuildUpdate) SetIsRelease(v bool) *BuildUpdate {
	_u.mutation.SetIsRelease(v)
	return _u
}

// SetNillableIsRelease sets the "isRelease" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableIsRelease(v *bool) *BuildUpdate {
	if v != nil {
		_u.SetIsRelease(*v)
	}
	return _u
}

// SetTriggerType sets the "triggerType" field.
func (_u *BuildUpdate) SetTriggerType(v string) *BuildUpdate {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "triggerType" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableTriggerType(v *string) *BuildUpdate {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetCommitMessage sets the "commitMessage" field.
func (_u *BuildUpdate) SetCommitMessage(v string) *BuildUpdate {
	_u.mutation.SetCommitMessage(v)
	return _u
}

// SetNillableCommitMessage sets the "commitMessage" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableCommitMessage(v *string) *BuildUpdate {
	if v != nil {
		_u.SetCommitMessage(*v)
	}
	return _u
}

// ClearCommitMessage clears the value of the "commitMessage" field.
func (_u *BuildUpdate) ClearCommitMessage() *BuildUpdate {
	_u.mutation.ClearCommitMessage()
	return _u
}

// SetLogs sets the "logs" field.
func (_u *BuildUpdate) SetLogs(v string) *BuildUpdate {
	_u.mutation.SetLogs(v)
	return _u
}

// SetNillableLogs sets the "logs" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableLogs(v *string) *BuildUpdate {
	if v != nil {
		_u.SetLogs(*v)
	}
	return _u
}

// ClearLogs clears the value of the "logs" field.
func (_u *BuildUpdate) ClearLogs() *BuildUpdate {
	_u.mutation.ClearLogs()
	return _u
}

// SetArtifactUrl sets the "artifactUrl" field.
func (_u *BuildUpdate) SetArtifactUrl(v string) *BuildUpdate {
	_u.mutation.SetArtifactUrl(v)
	return _u
}

// SetNillableArtifactUrl sets the "artifactUrl" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableArtifactUrl(v *string) *BuildUpdate {
	if v != nil {
		_u.SetArtifactUrl(*v)
	}
	return _u
}

// ClearArtifactUrl clears the value of the "artifactUrl" field.
func (_u *BuildUpdate) ClearArtifactUrl() *BuildUpdate {
	_u.mutation.ClearArtifactUrl()
	return _u
}

// SetArtifactSize sets the "artifactSize" field.
func (_u *BuildUpdate) SetArtifactSize(v int) *BuildUpdate {
	_u.mutation.ResetArtifactSize()
	_u.mutation.SetArtifactSize(v)
	return _u
}

// SetNillableArtifactSize sets the "artifactSize" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableArtifactSize(v *int) *BuildUpdate {
	if v != nil {
		_u.SetArtifactSize(*v)
	}
	return _u
}

// AddArtifactSize adds value to the "artifactSize" field.
func (_u *BuildUpdate) AddArtifactSize(v int) *BuildUpdate {
	_u.mutation.AddArtifactSize(v)
	return _u
}

// ClearArtifactSize clears the value of the "artifactSize" field.
func (_u *BuildUpdate) ClearArtifactSize() *BuildUpdate {
	_u.mutation.ClearArtifactSize()
	return _u
}

// SetArtifactUrlLinux sets the "artifactUrlLinux" field.
func (_u *BuildUpdate) SetArtifactUrlLinux(v string) *BuildUpdate {
	_u.mutation.SetArtifactUrlLinux(v)
	return _u
}

// SetNillableArtifactUrlLinux sets the "artifactUrlLinux" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableArtifactUrlLinux(v *string) *BuildUpdate {
	if v != nil {
		_u.SetArtifactUrlLinux(*v)
	}
	return _u
}

// ClearArtifactUrlLinux clears the value of the "artifactUrlLinux" field.
func (_u *BuildUpdate) ClearArtifactUrlLinux() *BuildUpdate {
	_u.mutation.ClearArtifactUrlLinux()
	return _u
}

// SetArtifactSizeLinux sets the "artifactSizeLinux" field.
func (_u *BuildUpdate) SetArtifactSizeLinux(v int) *BuildUpdate {
	_u.mutation.ResetArtifactSizeLinux()
	_u.mutation.SetArtifactSizeLinux(v)
	return _u
}

// SetNillableArtifactSizeLinux sets the "artifactSizeLinux" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableArtifactSizeLinux(v *int) *BuildUpdate {
	if v != nil {
		_u.SetArtifactSizeLinux(*v)
	}
	return _u
}

// AddArtifactSizeLinux adds value to the "artifactSizeLinux" field.
func (_u *BuildUpdate) AddArtifactSizeLinux(v int) *BuildUpdate {
	_u.mutation.AddArtifactSizeLinux(v)
	return _u
}

// ClearArtifactSizeLinux clears the value of the "artifactSizeLinux" field.
func (_u *BuildUpdate) ClearArtifactSizeLinux() *BuildUpdate {
	_u.mutation.ClearArtifactSizeLinux()
	return _u
}

// SetArtifactUrlWin sets the "artifactUrlWin" field.
func (_u *BuildUpdate) SetArtifactUrlWin(v string) *BuildUpdate {
	_u.mutation.SetArtifactUrlWin(v)
	return _u
}

// SetNillableArtifactUrlWin sets the "artifactUrlWin" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableArtifactUrlWin(v *string) *BuildUpdate {
	if v != nil {
		_u.SetArtifactUrlWin(*v)
	}
	return _u
}

// ClearArtifactUrlWin clears the value of the "artifactUrlWin" field.
func (_u *BuildUpdate) ClearArtifactUrlWin() *BuildUpdate {
	_u.mutation.ClearArtifactUrlWin()
	return _u
}

// SetArtifactSizeWin sets the "artifactSizeWin" field.
func (_u *BuildUpdate) SetArtifactSizeWin(v int) *BuildUpdate {
	_u.mutation.ResetArtifactSizeWin()
	_u.mutation.SetArtifactSizeWin(v)
	return _u
}

// SetNillableArtifactSizeWin sets the "artifactSizeWin" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableArtifactSizeWin(v *int) *BuildUpdate {
	if v != nil {
		_u.SetArtifactSizeWin(*v)
	}
	return _u
}

// AddArtifactSizeWin adds value to the "artifactSizeWin" field.
func (_u *BuildUpdate) AddArtifactSizeWin(v int) *BuildUpdate {
	_u.mutation.AddArtifactSizeWin(v)
	return _u
}

// ClearArtifactSizeWin clears the value of the "artifactSizeWin" field.
func (_u *BuildUpdate) ClearArtifactSizeWin() *BuildUpdate {
	_u.mutation.ClearArtifactSizeWin()
	return _u
}

// SetWinBuildStatus sets the "winBuildStatus" field.
func (_u *BuildUpdate) SetWinBuildStatus(v string) *BuildUpdate {
	_u.mutation.SetWinBuildStatus(v)
	return _u
}

// SetNillableWinBuildStatus sets the "winBuildStatus" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableWinBuildStatus(v *string) *BuildUpdate {
	if v != nil {
		_u.SetWinBuildStatus(*v)
	}
	return _u
}

// ClearWinBuildStatus clears the value of the "winBuildStatus" field.
func (_u *BuildUpdate) ClearWinBuildStatus() *BuildUpdate {
	_u.mutation.ClearWinBuildStatus()
	return _u
}

// SetLinuxBuildStatus sets the "linuxBuildStatus" field.
func (_u *BuildUpdate) SetLinuxBuildStatus(v string) *BuildUpdate {
	_u.mutation.SetLinuxBuildStatus(v)
	return _u
}

// SetNillableLinuxBuildStatus sets the "linuxBuildStatus" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableLinuxBuildStatus(v *string) *BuildUpdate {
	if v != nil {
		_u.SetLinuxBuildStatus(*v)
	}
	return _u
}

// ClearLinuxBuildStatus clears the value of the "linuxBuildStatus" field.
func (_u *BuildUpdate) ClearLinuxBuildStatus() *BuildUpdate {
	_u.mutation.ClearLinuxBuildStatus()
	return _u
}

// SetGhActionsRunId sets the "ghActionsRunId" field.
func (_u *BuildUpdate) SetGhActionsRunId(v string) *BuildUpdate {
	_u.mutation.SetGhActionsRunId(v)
	return _u
}

// SetNillableGhActionsRunId sets the "ghActionsRunId" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableGhActionsRunId(v *string) *BuildUpdate {
	if v != nil {
		_u.SetGhActionsRunId(*v)
	}
	return _u
}

// ClearGhActionsRunId clears the value of the "ghActionsRunId" field.
func (_u *BuildUpdate) ClearGhActionsRunId() *BuildUpdate {
	_u.mutation.ClearGhActionsRunId()
	return _u
}

// SetDuration sets the "duration" field.
func (_u *BuildUpdate) SetDuration(v int) *BuildUpdate {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableDuration(v *int) *BuildUpdate {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *BuildUpdate) AddDuration(v int) *BuildUpdate {
	_u.mutation.AddDuration(v)
	return _u
}

// ClearDuration clears the value of the "duration" field.
func (_u *BuildUpdate) ClearDuration() *BuildUpdate {
	_u.mutation.ClearDuration()
	return _u
}

// SetSafeScore sets the "safeScore" field.
func (_u *BuildUpdate) SetSafeScore(v int) *BuildUpdate {
	_u.mutation.ResetSafeScore()
	_u.mutation.SetSafeScore(v)
	return _u
}

// SetNillableSafeScore sets the "safeScore" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableSafeScore(v *int) *BuildUpdate {
	if v != nil {
		_u.SetSafeScore(*v)
	}
	return _u
}

// AddSafeScore adds value to the "safeScore" field.
func (_u *BuildUpdate) AddSafeScore(v int) *BuildUpdate {
	_u.mutation.AddSafeScore(v)
	return _u
}

// ClearSafeScore clears the value of the "safeScore" field.
func (_u *BuildUpdate) ClearSafeScore() *BuildUpdate {
	_u.mutation.ClearSafeScore()
	return _u
}

// SetScanResults sets the "scanResults" field.
func (_u *BuildUpdate) SetScanResults(v string) *BuildUpdate {
	_u.mutation.SetScanResults(v)
	return _u
}

// SetNillableScanResults sets the "scanResults" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableScanResults(v *string) *BuildUpdate {
	if v != nil {
		_u.SetScanResults(*v)
	}
	return _u
}

// ClearScanResults clears the value of the "scanResults" field.
func (_u *BuildUpdate) ClearScanResults() *BuildUpdate {
	_u.mutation.ClearScanResults()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *BuildUpdate) SetCreatedAt(v time.Time) *BuildUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableCreatedAt(v *time.Time) *BuildUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finishedAt" field.
func (_u *BuildUpdate) SetFinishedAt(v time.Time) *BuildUpdate {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finishedAt" field if the given value is not nil.
func (_u *BuildUpdate) SetNillableFinishedAt(v *time.Time) *BuildUpdate {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finishedAt" field.
func (_u *BuildUpdate) ClearFinishedAt() *BuildUpdate {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *BuildUpdate) SetPluginId(v string) *BuildUpdate {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *BuildUpdate) SetNillablePluginId(v *string) *BuildUpdate {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *BuildUpdate) SetPluginID(id string) *BuildUpdate {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *BuildUpdate) SetPlugin(v *Plugin) *BuildUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the BuildMutation object of the builder.
func (_u *BuildUpdate) Mutation() *BuildMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *BuildUpdate) ClearPlugin() *BuildUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *BuildUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BuildUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *BuildUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BuildUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BuildUpdate) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := build.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Build.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Build.plugin"`)
	}
	return nil
}

func (_u *BuildUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(build.Table, build.Columns, sqlgraph.NewFieldSpec(build.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BuildNumber(); ok {
		_spec.SetField(build.FieldBuildNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBuildNumber(); ok {
		_spec.AddField(build.FieldBuildNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommitHash(); ok {
		_spec.SetField(build.FieldCommitHash, field.TypeString, value)
	}
	if _u.mutation.CommitHashCleared() {
		_spec.ClearField(build.FieldCommitHash, field.TypeString)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(build.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(build.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsRelease(); ok {
		_spec.SetField(build.FieldIsRelease, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(build.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommitMessage(); ok {
		_spec.SetField(build.FieldCommitMessage, field.TypeString, value)
	}
	if _u.mutation.CommitMessageCleared() {
		_spec.ClearField(build.FieldCommitMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(build.FieldLogs, field.TypeString, value)
	}
	if _u.mutation.LogsCleared() {
		_spec.ClearField(build.FieldLogs, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactUrl(); ok {
		_spec.SetField(build.FieldArtifactUrl, field.TypeString, value)
	}
	if _u.mutation.ArtifactUrlCleared() {
		_spec.ClearField(build.FieldArtifactUrl, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactSize(); ok {
		_spec.SetField(build.FieldArtifactSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedArtifactSize(); ok {
		_spec.AddField(build.FieldArtifactSize, field.TypeInt, value)
	}
	if _u.mutation.ArtifactSizeCleared() {
		_spec.ClearField(build.FieldArtifactSize, field.TypeInt)
	}
	if value, ok := _u.mutation.ArtifactUrlLinux(); ok {
		_spec.SetField(build.FieldArtifactUrlLinux, field.TypeString, value)
	}
	if _u.mutation.ArtifactUrlLinuxCleared() {
		_spec.ClearField(build.FieldArtifactUrlLinux, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactSizeLinux(); ok {
		_spec.SetField(build.FieldArtifactSizeLinux, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedArtifactSizeLinux(); ok {
		_spec.AddField(build.FieldArtifactSizeLinux, field.TypeInt, value)
	}
	if _u.mutation.ArtifactSizeLinuxCleared() {
		_spec.ClearField(build.FieldArtifactSizeLinux, field.TypeInt)
	}
	if value, ok := _u.mutation.ArtifactUrlWin(); ok {
		_spec.SetField(build.FieldArtifactUrlWin, field.TypeString, value)
	}
	if _u.mutation.ArtifactUrlWinCleared() {
		_spec.ClearField(build.FieldArtifactUrlWin, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactSizeWin(); ok {
		_spec.SetField(build.FieldArtifactSizeWin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedArtifactSizeWin(); ok {
		_spec.AddField(build.FieldArtifactSizeWin, field.TypeInt, value)
	}
	if _u.mutation.ArtifactSizeWinCleared() {
		_spec.ClearField(build.FieldArtifactSizeWin, field.TypeInt)
	}
	if value, ok := _u.mutation.WinBuildStatus(); ok {
		_spec.SetField(build.FieldWinBuildStatus, field.TypeString, value)
	}
	if _u.mutation.WinBuildStatusCleared() {
		_spec.ClearField(build.FieldWinBuildStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LinuxBuildStatus(); ok {
		_spec.SetField(build.FieldLinuxBuildStatus, field.TypeString, value)
	}
	if _u.mutation.LinuxBuildStatusCleared() {
		_spec.ClearField(build.FieldLinuxBuildStatus, field.TypeString)
	}
	if value, ok := _u.mutation.GhActionsRunId(); ok {
		_spec.SetField(build.FieldGhActionsRunId, field.TypeString, value)
	}
	if _u.mutation.GhActionsRunIdCleared() {
		_spec.ClearField(build.FieldGhActionsRunId, field.TypeString)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(build.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(build.FieldDuration, field.TypeInt, value)
	}
	if _u.mutation.DurationCleared() {
		_spec.ClearField(build.FieldDuration, field.TypeInt)
	}
	if value, ok := _u.mutation.SafeScore(); ok {
		_spec.SetField(build.FieldSafeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSafeScore(); ok {
		_spec.AddField(build.FieldSafeScore, field.TypeInt, value)
	}
	if _u.mutation.SafeScoreCleared() {
		_spec.ClearField(build.FieldSafeScore, field.TypeInt)
	}
	if value, ok := _u.mutation.ScanResults(); ok {
		_spec.SetField(build.FieldScanResults, field.TypeString, value)
	}
	if _u.mutation.ScanResultsCleared() {
		_spec.ClearField(build.FieldScanResults, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(build.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(build.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(build.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   build.PluginTable,
			Columns: []string{build.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   build.PluginTable,
			Columns: []string{build.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{build.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// BuildUpdateOne is the builder for updating a single Build entity.
type BuildUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *BuildMutation
}

// SetBuildNumber sets the "buildNumber" field.
func (_u *BuildUpdateOne) SetBuildNumber(v int) *BuildUpdateOne {
	_u.mutation.ResetBuildNumber()
	_u.mutation.SetBuildNumber(v)
	return _u
}

// SetNillableBuildNumber sets the "buildNumber" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableBuildNumber(v *int) *BuildUpdateOne {
	if v != nil {
		_u.SetBuildNumber(*v)
	}
	return _u
}

// AddBuildNumber adds value to the "buildNumber" field.
func (_u *BuildUpdateOne) AddBuildNumber(v int) *BuildUpdateOne {
	_u.mutation.AddBuildNumber(v)
	return _u
}

// SetCommitHash sets the "commitHash" field.
func (_u *BuildUpdateOne) SetCommitHash(v string) *BuildUpdateOne {
	_u.mutation.SetCommitHash(v)
	return _u
}

// SetNillableCommitHash sets the "commitHash" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableCommitHash(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetCommitHash(*v)
	}
	return _u
}

// ClearCommitHash clears the value of the "commitHash" field.
func (_u *BuildUpdateOne) ClearCommitHash() *BuildUpdateOne {
	_u.mutation.ClearCommitHash()
	return _u
}

// SetBranch sets the "branch" field.
func (_u *BuildUpdateOne) SetBranch(v string) *BuildUpdateOne {
	_u.mutation.SetBranch(v)
	return _u
}

// SetNillableBranch sets the "branch" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableBranch(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetBranch(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *BuildUpdateOne) SetStatus(v build.Status) *BuildUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableStatus(v *build.Status) *BuildUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetIsRelease sets the "isRelease" field.
func (_u *BuildUpdateOne) SetIsRelease(v bool) *BuildUpdateOne {
	_u.mutation.SetIsRelease(v)
	return _u
}

// SetNillableIsRelease sets the "isRelease" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableIsRelease(v *bool) *BuildUpdateOne {
	if v != nil {
		_u.SetIsRelease(*v)
	}
	return _u
}

// SetTriggerType sets the "triggerType" field.
func (_u *BuildUpdateOne) SetTriggerType(v string) *BuildUpdateOne {
	_u.mutation.SetTriggerType(v)
	return _u
}

// SetNillableTriggerType sets the "triggerType" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableTriggerType(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetTriggerType(*v)
	}
	return _u
}

// SetCommitMessage sets the "commitMessage" field.
func (_u *BuildUpdateOne) SetCommitMessage(v string) *BuildUpdateOne {
	_u.mutation.SetCommitMessage(v)
	return _u
}

// SetNillableCommitMessage sets the "commitMessage" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableCommitMessage(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetCommitMessage(*v)
	}
	return _u
}

// ClearCommitMessage clears the value of the "commitMessage" field.
func (_u *BuildUpdateOne) ClearCommitMessage() *BuildUpdateOne {
	_u.mutation.ClearCommitMessage()
	return _u
}

// SetLogs sets the "logs" field.
func (_u *BuildUpdateOne) SetLogs(v string) *BuildUpdateOne {
	_u.mutation.SetLogs(v)
	return _u
}

// SetNillableLogs sets the "logs" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableLogs(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetLogs(*v)
	}
	return _u
}

// ClearLogs clears the value of the "logs" field.
func (_u *BuildUpdateOne) ClearLogs() *BuildUpdateOne {
	_u.mutation.ClearLogs()
	return _u
}

// SetArtifactUrl sets the "artifactUrl" field.
func (_u *BuildUpdateOne) SetArtifactUrl(v string) *BuildUpdateOne {
	_u.mutation.SetArtifactUrl(v)
	return _u
}

// SetNillableArtifactUrl sets the "artifactUrl" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableArtifactUrl(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetArtifactUrl(*v)
	}
	return _u
}

// ClearArtifactUrl clears the value of the "artifactUrl" field.
func (_u *BuildUpdateOne) ClearArtifactUrl() *BuildUpdateOne {
	_u.mutation.ClearArtifactUrl()
	return _u
}

// SetArtifactSize sets the "artifactSize" field.
func (_u *BuildUpdateOne) SetArtifactSize(v int) *BuildUpdateOne {
	_u.mutation.ResetArtifactSize()
	_u.mutation.SetArtifactSize(v)
	return _u
}

// SetNillableArtifactSize sets the "artifactSize" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableArtifactSize(v *int) *BuildUpdateOne {
	if v != nil {
		_u.SetArtifactSize(*v)
	}
	return _u
}

// AddArtifactSize adds value to the "artifactSize" field.
func (_u *BuildUpdateOne) AddArtifactSize(v int) *BuildUpdateOne {
	_u.mutation.AddArtifactSize(v)
	return _u
}

// ClearArtifactSize clears the value of the "artifactSize" field.
func (_u *BuildUpdateOne) ClearArtifactSize() *BuildUpdateOne {
	_u.mutation.ClearArtifactSize()
	return _u
}

// SetArtifactUrlLinux sets the "artifactUrlLinux" field.
func (_u *BuildUpdateOne) SetArtifactUrlLinux(v string) *BuildUpdateOne {
	_u.mutation.SetArtifactUrlLinux(v)
	return _u
}

// SetNillableArtifactUrlLinux sets the "artifactUrlLinux" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableArtifactUrlLinux(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetArtifactUrlLinux(*v)
	}
	return _u
}

// ClearArtifactUrlLinux clears the value of the "artifactUrlLinux" field.
func (_u *BuildUpdateOne) ClearArtifactUrlLinux() *BuildUpdateOne {
	_u.mutation.ClearArtifactUrlLinux()
	return _u
}

// SetArtifactSizeLinux sets the "artifactSizeLinux" field.
func (_u *BuildUpdateOne) SetArtifactSizeLinux(v int) *BuildUpdateOne {
	_u.mutation.ResetArtifactSizeLinux()
	_u.mutation.SetArtifactSizeLinux(v)
	return _u
}

// SetNillableArtifactSizeLinux sets the "artifactSizeLinux" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableArtifactSizeLinux(v *int) *BuildUpdateOne {
	if v != nil {
		_u.SetArtifactSizeLinux(*v)
	}
	return _u
}

// AddArtifactSizeLinux adds value to the "artifactSizeLinux" field.
func (_u *BuildUpdateOne) AddArtifactSizeLinux(v int) *BuildUpdateOne {
	_u.mutation.AddArtifactSizeLinux(v)
	return _u
}

// ClearArtifactSizeLinux clears the value of the "artifactSizeLinux" field.
func (_u *BuildUpdateOne) ClearArtifactSizeLinux() *BuildUpdateOne {
	_u.mutation.ClearArtifactSizeLinux()
	return _u
}

// SetArtifactUrlWin sets the "artifactUrlWin" field.
func (_u *BuildUpdateOne) SetArtifactUrlWin(v string) *BuildUpdateOne {
	_u.mutation.SetArtifactUrlWin(v)
	return _u
}

// SetNillableArtifactUrlWin sets the "artifactUrlWin" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableArtifactUrlWin(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetArtifactUrlWin(*v)
	}
	return _u
}

// ClearArtifactUrlWin clears the value of the "artifactUrlWin" field.
func (_u *BuildUpdateOne) ClearArtifactUrlWin() *BuildUpdateOne {
	_u.mutation.ClearArtifactUrlWin()
	return _u
}

// SetArtifactSizeWin sets the "artifactSizeWin" field.
func (_u *BuildUpdateOne) SetArtifactSizeWin(v int) *BuildUpdateOne {
	_u.mutation.ResetArtifactSizeWin()
	_u.mutation.SetArtifactSizeWin(v)
	return _u
}

// SetNillableArtifactSizeWin sets the "artifactSizeWin" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableArtifactSizeWin(v *int) *BuildUpdateOne {
	if v != nil {
		_u.SetArtifactSizeWin(*v)
	}
	return _u
}

// AddArtifactSizeWin adds value to the "artifactSizeWin" field.
func (_u *BuildUpdateOne) AddArtifactSizeWin(v int) *BuildUpdateOne {
	_u.mutation.AddArtifactSizeWin(v)
	return _u
}

// ClearArtifactSizeWin clears the value of the "artifactSizeWin" field.
func (_u *BuildUpdateOne) ClearArtifactSizeWin() *BuildUpdateOne {
	_u.mutation.ClearArtifactSizeWin()
	return _u
}

// SetWinBuildStatus sets the "winBuildStatus" field.
func (_u *BuildUpdateOne) SetWinBuildStatus(v string) *BuildUpdateOne {
	_u.mutation.SetWinBuildStatus(v)
	return _u
}

// SetNillableWinBuildStatus sets the "winBuildStatus" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableWinBuildStatus(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetWinBuildStatus(*v)
	}
	return _u
}

// ClearWinBuildStatus clears the value of the "winBuildStatus" field.
func (_u *BuildUpdateOne) ClearWinBuildStatus() *BuildUpdateOne {
	_u.mutation.ClearWinBuildStatus()
	return _u
}

// SetLinuxBuildStatus sets the "linuxBuildStatus" field.
func (_u *BuildUpdateOne) SetLinuxBuildStatus(v string) *BuildUpdateOne {
	_u.mutation.SetLinuxBuildStatus(v)
	return _u
}

// SetNillableLinuxBuildStatus sets the "linuxBuildStatus" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableLinuxBuildStatus(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetLinuxBuildStatus(*v)
	}
	return _u
}

// ClearLinuxBuildStatus clears the value of the "linuxBuildStatus" field.
func (_u *BuildUpdateOne) ClearLinuxBuildStatus() *BuildUpdateOne {
	_u.mutation.ClearLinuxBuildStatus()
	return _u
}

// SetGhActionsRunId sets the "ghActionsRunId" field.
func (_u *BuildUpdateOne) SetGhActionsRunId(v string) *BuildUpdateOne {
	_u.mutation.SetGhActionsRunId(v)
	return _u
}

// SetNillableGhActionsRunId sets the "ghActionsRunId" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableGhActionsRunId(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetGhActionsRunId(*v)
	}
	return _u
}

// ClearGhActionsRunId clears the value of the "ghActionsRunId" field.
func (_u *BuildUpdateOne) ClearGhActionsRunId() *BuildUpdateOne {
	_u.mutation.ClearGhActionsRunId()
	return _u
}

// SetDuration sets the "duration" field.
func (_u *BuildUpdateOne) SetDuration(v int) *BuildUpdateOne {
	_u.mutation.ResetDuration()
	_u.mutation.SetDuration(v)
	return _u
}

// SetNillableDuration sets the "duration" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableDuration(v *int) *BuildUpdateOne {
	if v != nil {
		_u.SetDuration(*v)
	}
	return _u
}

// AddDuration adds value to the "duration" field.
func (_u *BuildUpdateOne) AddDuration(v int) *BuildUpdateOne {
	_u.mutation.AddDuration(v)
	return _u
}

// ClearDuration clears the value of the "duration" field.
func (_u *BuildUpdateOne) ClearDuration() *BuildUpdateOne {
	_u.mutation.ClearDuration()
	return _u
}

// SetSafeScore sets the "safeScore" field.
func (_u *BuildUpdateOne) SetSafeScore(v int) *BuildUpdateOne {
	_u.mutation.ResetSafeScore()
	_u.mutation.SetSafeScore(v)
	return _u
}

// SetNillableSafeScore sets the "safeScore" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableSafeScore(v *int) *BuildUpdateOne {
	if v != nil {
		_u.SetSafeScore(*v)
	}
	return _u
}

// AddSafeScore adds value to the "safeScore" field.
func (_u *BuildUpdateOne) AddSafeScore(v int) *BuildUpdateOne {
	_u.mutation.AddSafeScore(v)
	return _u
}

// ClearSafeScore clears the value of the "safeScore" field.
func (_u *BuildUpdateOne) ClearSafeScore() *BuildUpdateOne {
	_u.mutation.ClearSafeScore()
	return _u
}

// SetScanResults sets the "scanResults" field.
func (_u *BuildUpdateOne) SetScanResults(v string) *BuildUpdateOne {
	_u.mutation.SetScanResults(v)
	return _u
}

// SetNillableScanResults sets the "scanResults" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableScanResults(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetScanResults(*v)
	}
	return _u
}

// ClearScanResults clears the value of the "scanResults" field.
func (_u *BuildUpdateOne) ClearScanResults() *BuildUpdateOne {
	_u.mutation.ClearScanResults()
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *BuildUpdateOne) SetCreatedAt(v time.Time) *BuildUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableCreatedAt(v *time.Time) *BuildUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetFinishedAt sets the "finishedAt" field.
func (_u *BuildUpdateOne) SetFinishedAt(v time.Time) *BuildUpdateOne {
	_u.mutation.SetFinishedAt(v)
	return _u
}

// SetNillableFinishedAt sets the "finishedAt" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillableFinishedAt(v *time.Time) *BuildUpdateOne {
	if v != nil {
		_u.SetFinishedAt(*v)
	}
	return _u
}

// ClearFinishedAt clears the value of the "finishedAt" field.
func (_u *BuildUpdateOne) ClearFinishedAt() *BuildUpdateOne {
	_u.mutation.ClearFinishedAt()
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *BuildUpdateOne) SetPluginId(v string) *BuildUpdateOne {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *BuildUpdateOne) SetNillablePluginId(v *string) *BuildUpdateOne {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *BuildUpdateOne) SetPluginID(id string) *BuildUpdateOne {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *BuildUpdateOne) SetPlugin(v *Plugin) *BuildUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the BuildMutation object of the builder.
func (_u *BuildUpdateOne) Mutation() *BuildMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *BuildUpdateOne) ClearPlugin() *BuildUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the BuildUpdate builder.
func (_u *BuildUpdateOne) Where(ps ...predicate.Build) *BuildUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *BuildUpdateOne) Select(field string, fields ...string) *BuildUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Build entity.
func (_u *BuildUpdateOne) Save(ctx context.Context) (*Build, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *BuildUpdateOne) SaveX(ctx context.Context) *Build {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *BuildUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *BuildUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *BuildUpdateOne) check() error {
	if v, ok := _u.mutation.Status(); ok {
		if err := build.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "Build.status": %w`, err)}
		}
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Build.plugin"`)
	}
	return nil
}

func (_u *BuildUpdateOne) sqlSave(ctx context.Context) (_node *Build, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(build.Table, build.Columns, sqlgraph.NewFieldSpec(build.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Build.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, build.FieldID)
		for _, f := range fields {
			if !build.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != build.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.BuildNumber(); ok {
		_spec.SetField(build.FieldBuildNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedBuildNumber(); ok {
		_spec.AddField(build.FieldBuildNumber, field.TypeInt, value)
	}
	if value, ok := _u.mutation.CommitHash(); ok {
		_spec.SetField(build.FieldCommitHash, field.TypeString, value)
	}
	if _u.mutation.CommitHashCleared() {
		_spec.ClearField(build.FieldCommitHash, field.TypeString)
	}
	if value, ok := _u.mutation.Branch(); ok {
		_spec.SetField(build.FieldBranch, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(build.FieldStatus, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.IsRelease(); ok {
		_spec.SetField(build.FieldIsRelease, field.TypeBool, value)
	}
	if value, ok := _u.mutation.TriggerType(); ok {
		_spec.SetField(build.FieldTriggerType, field.TypeString, value)
	}
	if value, ok := _u.mutation.CommitMessage(); ok {
		_spec.SetField(build.FieldCommitMessage, field.TypeString, value)
	}
	if _u.mutation.CommitMessageCleared() {
		_spec.ClearField(build.FieldCommitMessage, field.TypeString)
	}
	if value, ok := _u.mutation.Logs(); ok {
		_spec.SetField(build.FieldLogs, field.TypeString, value)
	}
	if _u.mutation.LogsCleared() {
		_spec.ClearField(build.FieldLogs, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactUrl(); ok {
		_spec.SetField(build.FieldArtifactUrl, field.TypeString, value)
	}
	if _u.mutation.ArtifactUrlCleared() {
		_spec.ClearField(build.FieldArtifactUrl, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactSize(); ok {
		_spec.SetField(build.FieldArtifactSize, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedArtifactSize(); ok {
		_spec.AddField(build.FieldArtifactSize, field.TypeInt, value)
	}
	if _u.mutation.ArtifactSizeCleared() {
		_spec.ClearField(build.FieldArtifactSize, field.TypeInt)
	}
	if value, ok := _u.mutation.ArtifactUrlLinux(); ok {
		_spec.SetField(build.FieldArtifactUrlLinux, field.TypeString, value)
	}
	if _u.mutation.ArtifactUrlLinuxCleared() {
		_spec.ClearField(build.FieldArtifactUrlLinux, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactSizeLinux(); ok {
		_spec.SetField(build.FieldArtifactSizeLinux, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedArtifactSizeLinux(); ok {
		_spec.AddField(build.FieldArtifactSizeLinux, field.TypeInt, value)
	}
	if _u.mutation.ArtifactSizeLinuxCleared() {
		_spec.ClearField(build.FieldArtifactSizeLinux, field.TypeInt)
	}
	if value, ok := _u.mutation.ArtifactUrlWin(); ok {
		_spec.SetField(build.FieldArtifactUrlWin, field.TypeString, value)
	}
	if _u.mutation.ArtifactUrlWinCleared() {
		_spec.ClearField(build.FieldArtifactUrlWin, field.TypeString)
	}
	if value, ok := _u.mutation.ArtifactSizeWin(); ok {
		_spec.SetField(build.FieldArtifactSizeWin, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedArtifactSizeWin(); ok {
		_spec.AddField(build.FieldArtifactSizeWin, field.TypeInt, value)
	}
	if _u.mutation.ArtifactSizeWinCleared() {
		_spec.ClearField(build.FieldArtifactSizeWin, field.TypeInt)
	}
	if value, ok := _u.mutation.WinBuildStatus(); ok {
		_spec.SetField(build.FieldWinBuildStatus, field.TypeString, value)
	}
	if _u.mutation.WinBuildStatusCleared() {
		_spec.ClearField(build.FieldWinBuildStatus, field.TypeString)
	}
	if value, ok := _u.mutation.LinuxBuildStatus(); ok {
		_spec.SetField(build.FieldLinuxBuildStatus, field.TypeString, value)
	}
	if _u.mutation.LinuxBuildStatusCleared() {
		_spec.ClearField(build.FieldLinuxBuildStatus, field.TypeString)
	}
	if value, ok := _u.mutation.GhActionsRunId(); ok {
		_spec.SetField(build.FieldGhActionsRunId, field.TypeString, value)
	}
	if _u.mutation.GhActionsRunIdCleared() {
		_spec.ClearField(build.FieldGhActionsRunId, field.TypeString)
	}
	if value, ok := _u.mutation.Duration(); ok {
		_spec.SetField(build.FieldDuration, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDuration(); ok {
		_spec.AddField(build.FieldDuration, field.TypeInt, value)
	}
	if _u.mutation.DurationCleared() {
		_spec.ClearField(build.FieldDuration, field.TypeInt)
	}
	if value, ok := _u.mutation.SafeScore(); ok {
		_spec.SetField(build.FieldSafeScore, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedSafeScore(); ok {
		_spec.AddField(build.FieldSafeScore, field.TypeInt, value)
	}
	if _u.mutation.SafeScoreCleared() {
		_spec.ClearField(build.FieldSafeScore, field.TypeInt)
	}
	if value, ok := _u.mutation.ScanResults(); ok {
		_spec.SetField(build.FieldScanResults, field.TypeString, value)
	}
	if _u.mutation.ScanResultsCleared() {
		_spec.ClearField(build.FieldScanResults, field.TypeString)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(build.FieldCreatedAt, field.TypeTime, value)
	}
	if value, ok := _u.mutation.FinishedAt(); ok {
		_spec.SetField(build.FieldFinishedAt, field.TypeTime, value)
	}
	if _u.mutation.FinishedAtCleared() {
		_spec.ClearField(build.FieldFinishedAt, field.TypeTime)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   build.PluginTable,
			Columns: []string{build.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   build.PluginTable,
			Columns: []string{build.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Build{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{build.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
