// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/EndGitHQ/endgit-core/ent/moderationlog"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
)

// ModerationLog is the model entity for the ModerationLog schema.
type ModerationLog struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Action holds the value of the "action" field.
	Action string `json:"action,omitempty"`
	// TargetType holds the value of the "targetType" field.
	TargetType string `json:"targetType,omitempty"`
	// TargetId holds the value of the "targetId" field.
	TargetId string `json:"targetId,omitempty"`
	// OldStatus holds the value of the "oldStatus" field.
	OldStatus string `json:"oldStatus,omitempty"`
	// NewStatus holds the value of the "newStatus" field.
	NewStatus string `json:"newStatus,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason *string `json:"reason,omitempty"`
	// ActorId holds the value of the "actorId" field.
	ActorId string `json:"actorId,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// PluginId holds the value of the "pluginId" field.
	PluginId *string `json:"pluginId,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ModerationLogQuery when eager-loading is set.
	Edges        ModerationLogEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ModerationLogEdges holds the relations/edges for other nodes in the graph.
type ModerationLogEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ModerationLogEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*ModerationLog) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case moderationlog.FieldID, moderationlog.FieldAction, moderationlog.FieldTargetType, moderationlog.FieldTargetId, moderationlog.FieldOldStatus, moderationlog.FieldNewStatus, moderationlog.FieldReason, moderationlog.FieldActorId, moderationlog.FieldPluginId:
			values[i] = new(sql.NullString)
		case moderationlog.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the ModerationLog fields.
func (_m *ModerationLog) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case moderationlog.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case moderationlog.FieldAction:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field action", values[i])
			} else if value.Valid {
				_m.Action = value.String
			}
		case moderationlog.FieldTargetType:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field targetType", values[i])
			} else if value.Valid {
				_m.TargetType = value.String
			}
		case moderationlog.FieldTargetId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field targetId", values[i])
			} else if value.Valid {
				_m.TargetId = value.String
			}
		case moderationlog.FieldOldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field oldStatus", values[i])
			} else if value.Valid {
				_m.OldStatus = value.String
			}
		case moderationlog.FieldNewStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field newStatus", values[i])
			} else if value.Valid {
				_m.NewStatus = value.String
			}
		case moderationlog.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = new(string)
				*_m.Reason = value.String
			}
		case moderationlog.FieldActorId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field actorId", values[i])
			} else if value.Valid {
				_m.ActorId = value.String
			}
		case moderationlog.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case moderationlog.FieldPluginId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pluginId", values[i])
			} else if value.Valid {
				_m.PluginId = new(string)
				*_m.PluginId = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the ModerationLog.
// This includes values selected through modifiers, order, etc.
func (_m *ModerationLog) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugin queries the "plugin" edge of the ModerationLog entity.
func (_m *ModerationLog) QueryPlugin() *PluginQuery {
	return NewModerationLogClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this ModerationLog.
// Note that you need to call ModerationLog.Unwrap() before calling this method if this ModerationLog
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *ModerationLog) Update() *ModerationLogUpdateOne {
	return NewModerationLogClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the ModerationLog entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *ModerationLog) Unwrap() *ModerationLog {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: ModerationLog is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *ModerationLog) String() string {
	var builder strings.Builder
	builder.WriteString("ModerationLog(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("action=")
	builder.WriteString(_m.Action)
	builder.WriteString(", ")
	builder.WriteString("targetType=")
	builder.WriteString(_m.TargetType)
	builder.WriteString(", ")
	builder.WriteString("targetId=")
	builder.WriteString(_m.TargetId)
	builder.WriteString(", ")
	builder.WriteString("oldStatus=")
	builder.WriteString(_m.OldStatus)
	builder.WriteString(", ")
	builder.WriteString("newStatus=")
	builder.WriteString(_m.NewStatus)
	builder.WriteString(", ")
	if v := _m.Reason; v != nil {
		builder.WriteString("reason=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("actorId=")
	builder.WriteString(_m.ActorId)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	if v := _m.PluginId; v != nil {
		builder.WriteString("pluginId=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// ModerationLogs is a parsable slice of ModerationLog.
type ModerationLogs []*ModerationLog
