// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/moderationlog"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
)

// ModerationLogUpdate is the builder for updating ModerationLog entities.
type ModerationLogUpdate struct {
	config
	hooks    []Hook
	mutation *ModerationLogMutation
}

// Where appends a list predicates to the ModerationLogUpdate builder.
func (_u *ModerationLogUpdate) Where(ps ...predicate.ModerationLog) *ModerationLogUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetAction sets the "action" field.
func (_u *ModerationLogUpdate) SetAction(v string) *ModerationLogUpdate {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillableAction(v *string) *ModerationLogUpdate {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "targetType" field.
func (_u *ModerationLogUpdate) SetTargetType(v string) *ModerationLogUpdate {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "targetType" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillableTargetType(v *string) *ModerationLogUpdate {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetId sets the "targetId" field.
func (_u *ModerationLogUpdate) SetTargetId(v string) *ModerationLogUpdate {
	_u.mutation.SetTargetId(v)
	return _u
}

// SetNillableTargetId sets the "targetId" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillableTargetId(v *string) *ModerationLogUpdate {
	if v != nil {
		_u.SetTargetId(*v)
	}
	return _u
}

// SetOldStatus sets the "oldStatus" field.
func (_u *ModerationLogUpdate) SetOldStatus(v string) *ModerationLogUpdate {
	_u.mutation.SetOldStatus(v)
	return _u
}

// SetNillableOldStatus sets the "oldStatus" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillableOldStatus(v *string) *ModerationLogUpdate {
	if v != nil {
		_u.SetOldStatus(*v)
	}
	return _u
}

// SetNewStatus sets the "newStatus" field.
func (_u *ModerationLogUpdate) SetNewStatus(v string) *ModerationLogUpdate {
	_u.mutation.SetNewStatus(v)
	return _u
}

// SetNillableNewStatus sets the "newStatus" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillableNewStatus(v *string) *ModerationLogUpdate {
	if v != nil {
		_u.SetNewStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *ModerationLogUpdate) SetReason(v string) *ModerationLogUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillableReason(v *string) *ModerationLogUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *ModerationLogUpdate) ClearReason() *ModerationLogUpdate {
	_u.mutation.ClearReason()
	return _u
}

// SetActorId sets the "actorId" field.
func (_u *ModerationLogUpdate) SetActorId(v string) *ModerationLogUpdate {
	_u.mutation.SetActorId(v)
	return _u
}

// SetNillableActorId sets the "actorId" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillableActorId(v *string) *ModerationLogUpdate {
	if v != nil {
		_u.SetActorId(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *ModerationLogUpdate) SetCreatedAt(v time.Time) *ModerationLogUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillableCreatedAt(v *time.Time) *ModerationLogUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *ModerationLogUpdate) SetPluginId(v string) *ModerationLogUpdate {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillablePluginId(v *string) *ModerationLogUpdate {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// ClearPluginId clears the value of the "pluginId" field.
func (_u *ModerationLogUpdate) ClearPluginId() *ModerationLogUpdate {
	_u.mutation.ClearPluginId()
	return _u
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *ModerationLogUpdate) SetPluginID(id string) *ModerationLogUpdate {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetNillablePluginID sets the "plugin" edge to the Plugin entity by ID if the given value is not nil.
func (_u *ModerationLogUpdate) SetNillablePluginID(id *string) *ModerationLogUpdate {
	if id != nil {
		_u = _u.SetPluginID(*id)
	}
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *ModerationLogUpdate) SetPlugin(v *Plugin) *ModerationLogUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the ModerationLogMutation object of the builder.
func (_u *ModerationLogUpdate) Mutation() *ModerationLogMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *ModerationLogUpdate) ClearPlugin() *ModerationLogUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ModerationLogUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModerationLogUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ModerationLogUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModerationLogUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ModerationLogUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	_spec := sqlgraph.NewUpdateSpec(moderationlog.Table, moderationlog.Columns, sqlgraph.NewFieldSpec(moderationlog.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(moderationlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(moderationlog.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetId(); ok {
		_spec.SetField(moderationlog.FieldTargetId, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldStatus(); ok {
		_spec.SetField(moderationlog.FieldOldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NewStatus(); ok {
		_spec.SetField(moderationlog.FieldNewStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(moderationlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(moderationlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.ActorId(); ok {
		_spec.SetField(moderationlog.FieldActorId, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(moderationlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   moderationlog.PluginTable,
			Columns: []string{moderationlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   moderationlog.PluginTable,
			Columns: []string{moderationlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moderationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ModerationLogUpdateOne is the builder for updating a single ModerationLog entity.
type ModerationLogUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ModerationLogMutation
}

// SetAction sets the "action" field.
func (_u *ModerationLogUpdateOne) SetAction(v string) *ModerationLogUpdateOne {
	_u.mutation.SetAction(v)
	return _u
}

// SetNillableAction sets the "action" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillableAction(v *string) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetAction(*v)
	}
	return _u
}

// SetTargetType sets the "targetType" field.
func (_u *ModerationLogUpdateOne) SetTargetType(v string) *ModerationLogUpdateOne {
	_u.mutation.SetTargetType(v)
	return _u
}

// SetNillableTargetType sets the "targetType" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillableTargetType(v *string) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetTargetType(*v)
	}
	return _u
}

// SetTargetId sets the "targetId" field.
func (_u *ModerationLogUpdateOne) SetTargetId(v string) *ModerationLogUpdateOne {
	_u.mutation.SetTargetId(v)
	return _u
}

// SetNillableTargetId sets the "targetId" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillableTargetId(v *string) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetTargetId(*v)
	}
	return _u
}

// SetOldStatus sets the "oldStatus" field.
func (_u *ModerationLogUpdateOne) SetOldStatus(v string) *ModerationLogUpdateOne {
	_u.mutation.SetOldStatus(v)
	return _u
}

// SetNillableOldStatus sets the "oldStatus" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillableOldStatus(v *string) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetOldStatus(*v)
	}
	return _u
}

// SetNewStatus sets the "newStatus" field.
func (_u *ModerationLogUpdateOne) SetNewStatus(v string) *ModerationLogUpdateOne {
	_u.mutation.SetNewStatus(v)
	return _u
}

// SetNillableNewStatus sets the "newStatus" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillableNewStatus(v *string) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetNewStatus(*v)
	}
	return _u
}

// SetReason sets the "reason" field.
func (_u *ModerationLogUpdateOne) SetReason(v string) *ModerationLogUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillableReason(v *string) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// ClearReason clears the value of the "reason" field.
func (_u *ModerationLogUpdateOne) ClearReason() *ModerationLogUpdateOne {
	_u.mutation.ClearReason()
	return _u
}

// SetActorId sets the "actorId" field.
func (_u *ModerationLogUpdateOne) SetActorId(v string) *ModerationLogUpdateOne {
	_u.mutation.SetActorId(v)
	return _u
}

// SetNillableActorId sets the "actorId" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillableActorId(v *string) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetActorId(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *ModerationLogUpdateOne) SetCreatedAt(v time.Time) *ModerationLogUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillableCreatedAt(v *time.Time) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *ModerationLogUpdateOne) SetPluginId(v string) *ModerationLogUpdateOne {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillablePluginId(v *string) *ModerationLogUpdateOne {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// ClearPluginId clears the value of the "pluginId" field.
func (_u *ModerationLogUpdateOne) ClearPluginId() *ModerationLogUpdateOne {
	_u.mutation.ClearPluginId()
	return _u
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *ModerationLogUpdateOne) SetPluginID(id string) *ModerationLogUpdateOne {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetNillablePluginID sets the "plugin" edge to the Plugin entity by ID if the given value is not nil.
func (_u *ModerationLogUpdateOne) SetNillablePluginID(id *string) *ModerationLogUpdateOne {
	if id != nil {
		_u = _u.SetPluginID(*id)
	}
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *ModerationLogUpdateOne) SetPlugin(v *Plugin) *ModerationLogUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the ModerationLogMutation object of the builder.
func (_u *ModerationLogUpdateOne) Mutation() *ModerationLogMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *ModerationLogUpdateOne) ClearPlugin() *ModerationLogUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the ModerationLogUpdate builder.
func (_u *ModerationLogUpdateOne) Where(ps ...predicate.ModerationLog) *ModerationLogUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ModerationLogUpdateOne) Select(field string, fields ...string) *ModerationLogUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated ModerationLog entity.
func (_u *ModerationLogUpdateOne) Save(ctx context.Context) (*ModerationLog, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ModerationLogUpdateOne) SaveX(ctx context.Context) *ModerationLog {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ModerationLogUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ModerationLogUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

func (_u *ModerationLogUpdateOne) sqlSave(ctx context.Context) (_node *ModerationLog, err error) {
	_spec := sqlgraph.NewUpdateSpec(moderationlog.Table, moderationlog.Columns, sqlgraph.NewFieldSpec(moderationlog.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "ModerationLog.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, moderationlog.FieldID)
		for _, f := range fields {
			if !moderationlog.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != moderationlog.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Action(); ok {
		_spec.SetField(moderationlog.FieldAction, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetType(); ok {
		_spec.SetField(moderationlog.FieldTargetType, field.TypeString, value)
	}
	if value, ok := _u.mutation.TargetId(); ok {
		_spec.SetField(moderationlog.FieldTargetId, field.TypeString, value)
	}
	if value, ok := _u.mutation.OldStatus(); ok {
		_spec.SetField(moderationlog.FieldOldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.NewStatus(); ok {
		_spec.SetField(moderationlog.FieldNewStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(moderationlog.FieldReason, field.TypeString, value)
	}
	if _u.mutation.ReasonCleared() {
		_spec.ClearField(moderationlog.FieldReason, field.TypeString)
	}
	if value, ok := _u.mutation.ActorId(); ok {
		_spec.SetField(moderationlog.FieldActorId, field.TypeString, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(moderationlog.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   moderationlog.PluginTable,
			Columns: []string{moderationlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   moderationlog.PluginTable,
			Columns: []string{moderationlog.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &ModerationLog{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{moderationlog.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
