// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/pluginanalytics"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
)

// PluginAnalyticsDelete is the builder for deleting a PluginAnalytics entity.
type PluginAnalyticsDelete struct {
	config
	hooks    []Hook
	mutation *PluginAnalyticsMutation
}

// Where appends a list predicates to the PluginAnalyticsDelete builder.
func (_d *PluginAnalyticsDelete) Where(ps ...predicate.PluginAnalytics) *PluginAnalyticsDelete {
	_d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query and returns how many vertices were deleted.
func (_d *PluginAnalyticsDelete) Exec(ctx context.Context) (int, error) {
	return withHooks(ctx, _d.sqlExec, _d.mutation, _d.hooks)
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PluginAnalyticsDelete) ExecX(ctx context.Context) int {
	n, err := _d.Exec(ctx)
	if err != nil {
		panic(err)
	}
	return n
}

func (_d *PluginAnalyticsDelete) sqlExec(ctx context.Context) (int, error) {
	_spec := sqlgraph.NewDeleteSpec(pluginanalytics.Table, sqlgraph.NewFieldSpec(pluginanalytics.FieldID, field.TypeString))
	if ps := _d.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	affected, err := sqlgraph.DeleteNodes(ctx, _d.driver, _spec)
	if err != nil && sqlgraph.IsConstraintError(err) {
		err = &ConstraintError{msg: err.Error(), wrap: err}
	}
	_d.mutation.done = true
	return affected, err
}

// PluginAnalyticsDeleteOne is the builder for deleting a single PluginAnalytics entity.
type PluginAnalyticsDeleteOne struct {
	_d *PluginAnalyticsDelete
}

// Where appends a list predicates to the PluginAnalyticsDelete builder.
func (_d *PluginAnalyticsDeleteOne) Where(ps ...predicate.PluginAnalytics) *PluginAnalyticsDeleteOne {
	_d._d.mutation.Where(ps...)
	return _d
}

// Exec executes the deletion query.
func (_d *PluginAnalyticsDeleteOne) Exec(ctx context.Context) error {
	n, err := _d._d.Exec(ctx)
	switch {
	case err != nil:
		return err
	case n == 0:
		return &NotFoundError{pluginanalytics.Label}
	default:
		return nil
	}
}

// ExecX is like Exec, but panics if an error occurs.
func (_d *PluginAnalyticsDeleteOne) ExecX(ctx context.Context) {
	if err := _d.Exec(ctx); err != nil {
		panic(err)
	}
}
