// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/pluginanalytics"
)

// PluginAnalytics is the model entity for the PluginAnalytics schema.
type PluginAnalytics struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// PluginId holds the value of the "pluginId" field.
	PluginId string `json:"pluginId,omitempty"`
	// Date holds the value of the "date" field.
	Date time.Time `json:"date,omitempty"`
	// Downloads holds the value of the "downloads" field.
	Downloads int `json:"downloads,omitempty"`
	// Views holds the value of the "views" field.
	Views int `json:"views,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PluginAnalyticsQuery when eager-loading is set.
	Edges        PluginAnalyticsEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PluginAnalyticsEdges holds the relations/edges for other nodes in the graph.
type PluginAnalyticsEdges struct {
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [1]bool
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PluginAnalyticsEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginAnalytics) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case pluginanalytics.FieldDownloads, pluginanalytics.FieldViews:
			values[i] = new(sql.NullInt64)
		case pluginanalytics.FieldID, pluginanalytics.FieldPluginId:
			values[i] = new(sql.NullString)
		case pluginanalytics.FieldDate:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginAnalytics fields.
func (_m *PluginAnalytics) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case pluginanalytics.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case pluginanalytics.FieldPluginId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pluginId", values[i])
			} else if value.Valid {
				_m.PluginId = value.String
			}
		case pluginanalytics.FieldDate:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field date", values[i])
			} else if value.Valid {
				_m.Date = value.Time
			}
		case pluginanalytics.FieldDownloads:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field downloads", values[i])
			} else if value.Valid {
				_m.Downloads = int(value.Int64)
			}
		case pluginanalytics.FieldViews:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field views", values[i])
			} else if value.Valid {
				_m.Views = int(value.Int64)
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PluginAnalytics.
// This includes values selected through modifiers, order, etc.
func (_m *PluginAnalytics) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugin queries the "plugin" edge of the PluginAnalytics entity.
func (_m *PluginAnalytics) QueryPlugin() *PluginQuery {
	return NewPluginAnalyticsClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this PluginAnalytics.
// Note that you need to call PluginAnalytics.Unwrap() before calling this method if this PluginAnalytics
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PluginAnalytics) Update() *PluginAnalyticsUpdateOne {
	return NewPluginAnalyticsClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PluginAnalytics entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PluginAnalytics) Unwrap() *PluginAnalytics {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PluginAnalytics is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PluginAnalytics) String() string {
	var builder strings.Builder
	builder.WriteString("PluginAnalytics(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("pluginId=")
	builder.WriteString(_m.PluginId)
	builder.WriteString(", ")
	builder.WriteString("date=")
	builder.WriteString(_m.Date.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("downloads=")
	builder.WriteString(fmt.Sprintf("%v", _m.Downloads))
	builder.WriteString(", ")
	builder.WriteString("views=")
	builder.WriteString(fmt.Sprintf("%v", _m.Views))
	builder.WriteByte(')')
	return builder.String()
}

// PluginAnalyticsSlice is a parsable slice of PluginAnalytics.
type PluginAnalyticsSlice []*PluginAnalytics
