// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/pluginanalytics"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
)

// PluginAnalyticsUpdate is the builder for updating PluginAnalytics entities.
type PluginAnalyticsUpdate struct {
	config
	hooks    []Hook
	mutation *PluginAnalyticsMutation
}

// Where appends a list predicates to the PluginAnalyticsUpdate builder.
func (_u *PluginAnalyticsUpdate) Where(ps ...predicate.PluginAnalytics) *PluginAnalyticsUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *PluginAnalyticsUpdate) SetPluginId(v string) *PluginAnalyticsUpdate {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *PluginAnalyticsUpdate) SetNillablePluginId(v *string) *PluginAnalyticsUpdate {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *PluginAnalyticsUpdate) SetDate(v time.Time) *PluginAnalyticsUpdate {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *PluginAnalyticsUpdate) SetNillableDate(v *time.Time) *PluginAnalyticsUpdate {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetDownloads sets the "downloads" field.
func (_u *PluginAnalyticsUpdate) SetDownloads(v int) *PluginAnalyticsUpdate {
	_u.mutation.ResetDownloads()
	_u.mutation.SetDownloads(v)
	return _u
}

// SetNillableDownloads sets the "downloads" field if the given value is not nil.
func (_u *PluginAnalyticsUpdate) SetNillableDownloads(v *int) *PluginAnalyticsUpdate {
	if v != nil {
		_u.SetDownloads(*v)
	}
	return _u
}

// AddDownloads adds value to the "downloads" field.
func (_u *PluginAnalyticsUpdate) AddDownloads(v int) *PluginAnalyticsUpdate {
	_u.mutation.AddDownloads(v)
	return _u
}

// SetViews sets the "views" field.
func (_u *PluginAnalyticsUpdate) SetViews(v int) *PluginAnalyticsUpdate {
	_u.mutation.ResetViews()
	_u.mutation.SetViews(v)
	return _u
}

// SetNillableViews sets the "views" field if the given value is not nil.
func (_u *PluginAnalyticsUpdate) SetNillableViews(v *int) *PluginAnalyticsUpdate {
	if v != nil {
		_u.SetViews(*v)
	}
	return _u
}

// AddViews adds value to the "views" field.
func (_u *PluginAnalyticsUpdate) AddViews(v int) *PluginAnalyticsUpdate {
	_u.mutation.AddViews(v)
	return _u
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *PluginAnalyticsUpdate) SetPluginID(id string) *PluginAnalyticsUpdate {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *PluginAnalyticsUpdate) SetPlugin(v *Plugin) *PluginAnalyticsUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the PluginAnalyticsMutation object of the builder.
func (_u *PluginAnalyticsUpdate) Mutation() *PluginAnalyticsMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *PluginAnalyticsUpdate) ClearPlugin() *PluginAnalyticsUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *PluginAnalyticsUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginAnalyticsUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *PluginAnalyticsUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginAnalyticsUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginAnalyticsUpdate) check() error {
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginAnalytics.plugin"`)
	}
	return nil
}

func (_u *PluginAnalyticsUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginanalytics.Table, pluginanalytics.Columns, sqlgraph.NewFieldSpec(pluginanalytics.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(pluginanalytics.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Downloads(); ok {
		_spec.SetField(pluginanalytics.FieldDownloads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloads(); ok {
		_spec.AddField(pluginanalytics.FieldDownloads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Views(); ok {
		_spec.SetField(pluginanalytics.FieldViews, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViews(); ok {
		_spec.AddField(pluginanalytics.FieldViews, field.TypeInt, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pluginanalytics.PluginTable,
			Columns: []string{pluginanalytics.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pluginanalytics.PluginTable,
			Columns: []string{pluginanalytics.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginanalytics.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// PluginAnalyticsUpdateOne is the builder for updating a single PluginAnalytics entity.
type PluginAnalyticsUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *PluginAnalyticsMutation
}

// SetPluginId sets the "pluginId" field.
func (_u *PluginAnalyticsUpdateOne) SetPluginId(v string) *PluginAnalyticsUpdateOne {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *PluginAnalyticsUpdateOne) SetNillablePluginId(v *string) *PluginAnalyticsUpdateOne {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// SetDate sets the "date" field.
func (_u *PluginAnalyticsUpdateOne) SetDate(v time.Time) *PluginAnalyticsUpdateOne {
	_u.mutation.SetDate(v)
	return _u
}

// SetNillableDate sets the "date" field if the given value is not nil.
func (_u *PluginAnalyticsUpdateOne) SetNillableDate(v *time.Time) *PluginAnalyticsUpdateOne {
	if v != nil {
		_u.SetDate(*v)
	}
	return _u
}

// SetDownloads sets the "downloads" field.
func (_u *PluginAnalyticsUpdateOne) SetDownloads(v int) *PluginAnalyticsUpdateOne {
	_u.mutation.ResetDownloads()
	_u.mutation.SetDownloads(v)
	return _u
}

// SetNillableDownloads sets the "downloads" field if the given value is not nil.
func (_u *PluginAnalyticsUpdateOne) SetNillableDownloads(v *int) *PluginAnalyticsUpdateOne {
	if v != nil {
		_u.SetDownloads(*v)
	}
	return _u
}

// AddDownloads adds value to the "downloads" field.
func (_u *PluginAnalyticsUpdateOne) AddDownloads(v int) *PluginAnalyticsUpdateOne {
	_u.mutation.AddDownloads(v)
	return _u
}

// SetViews sets the "views" field.
func (_u *PluginAnalyticsUpdateOne) SetViews(v int) *PluginAnalyticsUpdateOne {
	_u.mutation.ResetViews()
	_u.mutation.SetViews(v)
	return _u
}

// SetNillableViews sets the "views" field if the given value is not nil.
func (_u *PluginAnalyticsUpdateOne) SetNillableViews(v *int) *PluginAnalyticsUpdateOne {
	if v != nil {
		_u.SetViews(*v)
	}
	return _u
}

// AddViews adds value to the "views" field.
func (_u *PluginAnalyticsUpdateOne) AddViews(v int) *PluginAnalyticsUpdateOne {
	_u.mutation.AddViews(v)
	return _u
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *PluginAnalyticsUpdateOne) SetPluginID(id string) *PluginAnalyticsUpdateOne {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *PluginAnalyticsUpdateOne) SetPlugin(v *Plugin) *PluginAnalyticsUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the PluginAnalyticsMutation object of the builder.
func (_u *PluginAnalyticsUpdateOne) Mutation() *PluginAnalyticsMutation {
	return _u.mutation
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *PluginAnalyticsUpdateOne) ClearPlugin() *PluginAnalyticsUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the PluginAnalyticsUpdate builder.
func (_u *PluginAnalyticsUpdateOne) Where(ps ...predicate.PluginAnalytics) *PluginAnalyticsUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *PluginAnalyticsUpdateOne) Select(field string, fields ...string) *PluginAnalyticsUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated PluginAnalytics entity.
func (_u *PluginAnalyticsUpdateOne) Save(ctx context.Context) (*PluginAnalytics, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *PluginAnalyticsUpdateOne) SaveX(ctx context.Context) *PluginAnalytics {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *PluginAnalyticsUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *PluginAnalyticsUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *PluginAnalyticsUpdateOne) check() error {
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "PluginAnalytics.plugin"`)
	}
	return nil
}

func (_u *PluginAnalyticsUpdateOne) sqlSave(ctx context.Context) (_node *PluginAnalytics, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(pluginanalytics.Table, pluginanalytics.Columns, sqlgraph.NewFieldSpec(pluginanalytics.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "PluginAnalytics.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, pluginanalytics.FieldID)
		for _, f := range fields {
			if !pluginanalytics.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != pluginanalytics.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Date(); ok {
		_spec.SetField(pluginanalytics.FieldDate, field.TypeTime, value)
	}
	if value, ok := _u.mutation.Downloads(); ok {
		_spec.SetField(pluginanalytics.FieldDownloads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedDownloads(); ok {
		_spec.AddField(pluginanalytics.FieldDownloads, field.TypeInt, value)
	}
	if value, ok := _u.mutation.Views(); ok {
		_spec.SetField(pluginanalytics.FieldViews, field.TypeInt, value)
	}
	if value, ok := _u.mutation.AddedViews(); ok {
		_spec.AddField(pluginanalytics.FieldViews, field.TypeInt, value)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pluginanalytics.PluginTable,
			Columns: []string{pluginanalytics.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pluginanalytics.PluginTable,
			Columns: []string{pluginanalytics.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &PluginAnalytics{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{pluginanalytics.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
