// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/plugincomment"
	"github.com/EndGitHQ/endgit-core/ent/user"
)

// PluginComment is the model entity for the PluginComment schema.
type PluginComment struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Body holds the value of the "body" field.
	Body string `json:"body,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// UserId holds the value of the "userId" field.
	UserId string `json:"userId,omitempty"`
	// PluginId holds the value of the "pluginId" field.
	PluginId string `json:"pluginId,omitempty"`
	// ParentId holds the value of the "parentId" field.
	ParentId *string `json:"parentId,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the PluginCommentQuery when eager-loading is set.
	Edges        PluginCommentEdges `json:"edges"`
	selectValues sql.SelectValues
}

// PluginCommentEdges holds the relations/edges for other nodes in the graph.
type PluginCommentEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// Replies holds the value of the replies edge.
	Replies []*PluginComment `json:"replies,omitempty"`
	// Parent holds the value of the parent edge.
	Parent *PluginComment `json:"parent,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [4]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PluginCommentEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PluginCommentEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// RepliesOrErr returns the Replies value or an error if the edge
// was not loaded in eager-loading.
func (e PluginCommentEdges) RepliesOrErr() ([]*PluginComment, error) {
	if e.loadedTypes[2] {
		return e.Replies, nil
	}
	return nil, &NotLoadedError{edge: "replies"}
}

// ParentOrErr returns the Parent value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e PluginCommentEdges) ParentOrErr() (*PluginComment, error) {
	if e.Parent != nil {
		return e.Parent, nil
	} else if e.loadedTypes[3] {
		return nil, &NotFoundError{label: plugincomment.Label}
	}
	return nil, &NotLoadedError{edge: "parent"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*PluginComment) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case plugincomment.FieldID, plugincomment.FieldBody, plugincomment.FieldUserId, plugincomment.FieldPluginId, plugincomment.FieldParentId:
			values[i] = new(sql.NullString)
		case plugincomment.FieldCreatedAt, plugincomment.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the PluginComment fields.
func (_m *PluginComment) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case plugincomment.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case plugincomment.FieldBody:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field body", values[i])
			} else if value.Valid {
				_m.Body = value.String
			}
		case plugincomment.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case plugincomment.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		case plugincomment.FieldUserId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field userId", values[i])
			} else if value.Valid {
				_m.UserId = value.String
			}
		case plugincomment.FieldPluginId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pluginId", values[i])
			} else if value.Valid {
				_m.PluginId = value.String
			}
		case plugincomment.FieldParentId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field parentId", values[i])
			} else if value.Valid {
				_m.ParentId = new(string)
				*_m.ParentId = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the PluginComment.
// This includes values selected through modifiers, order, etc.
func (_m *PluginComment) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the PluginComment entity.
func (_m *PluginComment) QueryUser() *UserQuery {
	return NewPluginCommentClient(_m.config).QueryUser(_m)
}

// QueryPlugin queries the "plugin" edge of the PluginComment entity.
func (_m *PluginComment) QueryPlugin() *PluginQuery {
	return NewPluginCommentClient(_m.config).QueryPlugin(_m)
}

// QueryReplies queries the "replies" edge of the PluginComment entity.
func (_m *PluginComment) QueryReplies() *PluginCommentQuery {
	return NewPluginCommentClient(_m.config).QueryReplies(_m)
}

// QueryParent queries the "parent" edge of the PluginComment entity.
func (_m *PluginComment) QueryParent() *PluginCommentQuery {
	return NewPluginCommentClient(_m.config).QueryParent(_m)
}

// Update returns a builder for updating this PluginComment.
// Note that you need to call PluginComment.Unwrap() before calling this method if this PluginComment
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *PluginComment) Update() *PluginCommentUpdateOne {
	return NewPluginCommentClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the PluginComment entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *PluginComment) Unwrap() *PluginComment {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: PluginComment is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *PluginComment) String() string {
	var builder strings.Builder
	builder.WriteString("PluginComment(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("body=")
	builder.WriteString(_m.Body)
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("userId=")
	builder.WriteString(_m.UserId)
	builder.WriteString(", ")
	builder.WriteString("pluginId=")
	builder.WriteString(_m.PluginId)
	builder.WriteString(", ")
	if v := _m.ParentId; v != nil {
		builder.WriteString("parentId=")
		builder.WriteString(*v)
	}
	builder.WriteByte(')')
	return builder.String()
}

// PluginComments is a parsable slice of PluginComment.
type PluginComments []*PluginComment
