// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/plugincomment"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
	"github.com/EndGitHQ/endgit-core/ent/user"
)

// PluginCommentQuery is the builder for querying PluginComment entities.
type PluginCommentQuery struct {
	config
	ctx         *QueryContext
	order       []plugincomment.OrderOption
	inters      []Interceptor
	predicates  []predicate.PluginComment
	withUser    *UserQuery
	withPlugin  *PluginQuery
	withReplies *PluginCommentQuery
	withParent  *PluginCommentQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the PluginCommentQuery builder.
func (_q *PluginCommentQuery) Where(ps ...predicate.PluginComment) *PluginCommentQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *PluginCommentQuery) Limit(limit int) *PluginCommentQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *PluginCommentQuery) Offset(offset int) *PluginCommentQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *PluginCommentQuery) Unique(unique bool) *PluginCommentQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *PluginCommentQuery) Order(o ...plugincomment.OrderOption) *PluginCommentQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryUser chains the current query on the "user" edge.
func (_q *PluginCommentQuery) QueryUser() *UserQuery {
	query := (&UserClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plugincomment.Table, plugincomment.FieldID, selector),
			sqlgraph.To(user.Table, user.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, plugincomment.UserTable, plugincomment.UserColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryPlugin chains the current query on the "plugin" edge.
func (_q *PluginCommentQuery) QueryPlugin() *PluginQuery {
	query := (&PluginClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plugincomment.Table, plugincomment.FieldID, selector),
			sqlgraph.To(plugin.Table, plugin.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, plugincomment.PluginTable, plugincomment.PluginColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryReplies chains the current query on the "replies" edge.
func (_q *PluginCommentQuery) QueryReplies() *PluginCommentQuery {
	query := (&PluginCommentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plugincomment.Table, plugincomment.FieldID, selector),
			sqlgraph.To(plugincomment.Table, plugincomment.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, plugincomment.RepliesTable, plugincomment.RepliesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryParent chains the current query on the "parent" edge.
func (_q *PluginCommentQuery) QueryParent() *PluginCommentQuery {
	query := (&PluginCommentClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(plugincomment.Table, plugincomment.FieldID, selector),
			sqlgraph.To(plugincomment.Table, plugincomment.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, plugincomment.ParentTable, plugincomment.ParentColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first PluginComment entity from the query.
// Returns a *NotFoundError when no PluginComment was found.
func (_q *PluginCommentQuery) First(ctx context.Context) (*PluginComment, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{plugincomment.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *PluginCommentQuery) FirstX(ctx context.Context) *PluginComment {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first PluginComment ID from the query.
// Returns a *NotFoundError when no PluginComment ID was found.
func (_q *PluginCommentQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{plugincomment.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *PluginCommentQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single PluginComment entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one PluginComment entity is found.
// Returns a *NotFoundError when no PluginComment entities are found.
func (_q *PluginCommentQuery) Only(ctx context.Context) (*PluginComment, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{plugincomment.Label}
	default:
		return nil, &NotSingularError{plugincomment.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *PluginCommentQuery) OnlyX(ctx context.Context) *PluginComment {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only PluginComment ID in the query.
// Returns a *NotSingularError when more than one PluginComment ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *PluginCommentQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{plugincomment.Label}
	default:
		err = &NotSingularError{plugincomment.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *PluginCommentQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of PluginComments.
func (_q *PluginCommentQuery) All(ctx context.Context) ([]*PluginComment, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*PluginComment, *PluginCommentQuery]()
	return withInterceptors[[]*PluginComment](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *PluginCommentQuery) AllX(ctx context.Context) []*PluginComment {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of PluginComment IDs.
func (_q *PluginCommentQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(plugincomment.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *PluginCommentQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *PluginCommentQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*PluginCommentQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *PluginCommentQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *PluginCommentQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *PluginCommentQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the PluginCommentQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *PluginCommentQuery) Clone() *PluginCommentQuery {
	if _q == nil {
		return nil
	}
	return &PluginCommentQuery{
		config:      _q.config,
		ctx:         _q.ctx.Clone(),
		order:       append([]plugincomment.OrderOption{}, _q.order...),
		inters:      append([]Interceptor{}, _q.inters...),
		predicates:  append([]predicate.PluginComment{}, _q.predicates...),
		withUser:    _q.withUser.Clone(),
		withPlugin:  _q.withPlugin.Clone(),
		withReplies: _q.withReplies.Clone(),
		withParent:  _q.withParent.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithUser tells the query-builder to eager-load the nodes that are connected to
// the "user" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PluginCommentQuery) WithUser(opts ...func(*UserQuery)) *PluginCommentQuery {
	query := (&UserClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withUser = query
	return _q
}

// WithPlugin tells the query-builder to eager-load the nodes that are connected to
// the "plugin" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PluginCommentQuery) WithPlugin(opts ...func(*PluginQuery)) *PluginCommentQuery {
	query := (&PluginClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlugin = query
	return _q
}

// WithReplies tells the query-builder to eager-load the nodes that are connected to
// the "replies" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PluginCommentQuery) WithReplies(opts ...func(*PluginCommentQuery)) *PluginCommentQuery {
	query := (&PluginCommentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withReplies = query
	return _q
}

// WithParent tells the query-builder to eager-load the nodes that are connected to
// the "parent" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *PluginCommentQuery) WithParent(opts ...func(*PluginCommentQuery)) *PluginCommentQuery {
	query := (&PluginCommentClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withParent = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Body string `json:"body,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.PluginComment.Query().
//		GroupBy(plugincomment.FieldBody).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *PluginCommentQuery) GroupBy(field string, fields ...string) *PluginCommentGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &PluginCommentGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = plugincomment.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Body string `json:"body,omitempty"`
//	}
//
//	client.PluginComment.Query().
//		Select(plugincomment.FieldBody).
//		Scan(ctx, &v)
func (_q *PluginCommentQuery) Select(fields ...string) *PluginCommentSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &PluginCommentSelect{PluginCommentQuery: _q}
	sbuild.label = plugincomment.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a PluginCommentSelect configured with the given aggregations.
func (_q *PluginCommentQuery) Aggregate(fns ...AggregateFunc) *PluginCommentSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *PluginCommentQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !plugincomment.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *PluginCommentQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*PluginComment, error) {
	var (
		nodes       = []*PluginComment{}
		_spec       = _q.querySpec()
		loadedTypes = [4]bool{
			_q.withUser != nil,
			_q.withPlugin != nil,
			_q.withReplies != nil,
			_q.withParent != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*PluginComment).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &PluginComment{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withUser; query != nil {
		if err := _q.loadUser(ctx, query, nodes, nil,
			func(n *PluginComment, e *User) { n.Edges.User = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withPlugin; query != nil {
		if err := _q.loadPlugin(ctx, query, nodes, nil,
			func(n *PluginComment, e *Plugin) { n.Edges.Plugin = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withReplies; query != nil {
		if err := _q.loadReplies(ctx, query, nodes,
			func(n *PluginComment) { n.Edges.Replies = []*PluginComment{} },
			func(n *PluginComment, e *PluginComment) { n.Edges.Replies = append(n.Edges.Replies, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withParent; query != nil {
		if err := _q.loadParent(ctx, query, nodes, nil,
			func(n *PluginComment, e *PluginComment) { n.Edges.Parent = e }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *PluginCommentQuery) loadUser(ctx context.Context, query *UserQuery, nodes []*PluginComment, init func(*PluginComment), assign func(*PluginComment, *User)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*PluginComment)
	for i := range nodes {
		fk := nodes[i].UserId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(user.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "userId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PluginCommentQuery) loadPlugin(ctx context.Context, query *PluginQuery, nodes []*PluginComment, init func(*PluginComment), assign func(*PluginComment, *Plugin)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*PluginComment)
	for i := range nodes {
		fk := nodes[i].PluginId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(plugin.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pluginId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *PluginCommentQuery) loadReplies(ctx context.Context, query *PluginCommentQuery, nodes []*PluginComment, init func(*PluginComment), assign func(*PluginComment, *PluginComment)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*PluginComment)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(plugincomment.FieldParentId)
	}
	query.Where(predicate.PluginComment(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(plugincomment.RepliesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.ParentId
		if fk == nil {
			return fmt.Errorf(`foreign-key "parentId" is nil for node %v`, n.ID)
		}
		node, ok := nodeids[*fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "parentId" returned %v for node %v`, *fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *PluginCommentQuery) loadParent(ctx context.Context, query *PluginCommentQuery, nodes []*PluginComment, init func(*PluginComment), assign func(*PluginComment, *PluginComment)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*PluginComment)
	for i := range nodes {
		if nodes[i].ParentId == nil {
			continue
		}
		fk := *nodes[i].ParentId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(plugincomment.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "parentId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}

func (_q *PluginCommentQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *PluginCommentQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(plugincomment.Table, plugincomment.Columns, sqlgraph.NewFieldSpec(plugincomment.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, plugincomment.FieldID)
		for i := range fields {
			if fields[i] != plugincomment.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withUser != nil {
			_spec.Node.AddColumnOnce(plugincomment.FieldUserId)
		}
		if _q.withPlugin != nil {
			_spec.Node.AddColumnOnce(plugincomment.FieldPluginId)
		}
		if _q.withParent != nil {
			_spec.Node.AddColumnOnce(plugincomment.FieldParentId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *PluginCommentQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(plugincomment.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = plugincomment.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// PluginCommentGroupBy is the group-by builder for PluginComment entities.
type PluginCommentGroupBy struct {
	selector
	build *PluginCommentQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *PluginCommentGroupBy) Aggregate(fns ...AggregateFunc) *PluginCommentGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *PluginCommentGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PluginCommentQuery, *PluginCommentGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *PluginCommentGroupBy) sqlScan(ctx context.Context, root *PluginCommentQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// PluginCommentSelect is the builder for selecting fields of PluginComment entities.
type PluginCommentSelect struct {
	*PluginCommentQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *PluginCommentSelect) Aggregate(fns ...AggregateFunc) *PluginCommentSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *PluginCommentSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*PluginCommentQuery, *PluginCommentSelect](ctx, _s.PluginCommentQuery, _s, _s.inters, v)
}

func (_s *PluginCommentSelect) sqlScan(ctx context.Context, root *PluginCommentQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
