// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/pluginanalytics"
)

// PluginAnalyticsCreate is the builder for creating a PluginAnalytics entity.
type PluginAnalyticsCreate struct {
	config
	mutation *PluginAnalyticsMutation
	hooks    []Hook
}

// SetPluginId sets the "pluginId" field.
func (_c *PluginAnalyticsCreate) SetPluginId(v string) *PluginAnalyticsCreate {
	_c.mutation.SetPluginId(v)
	return _c
}

// SetDate sets the "date" field.
func (_c *PluginAnalyticsCreate) SetDate(v time.Time) *PluginAnalyticsCreate {
	_c.mutation.SetDate(v)
	return _c
}

// SetDownloads sets the "downloads" field.
func (_c *PluginAnalyticsCreate) SetDownloads(v int) *PluginAnalyticsCreate {
	_c.mutation.SetDownloads(v)
	return _c
}

// SetNillableDownloads sets the "downloads" field if the given value is not nil.
func (_c *PluginAnalyticsCreate) SetNillableDownloads(v *int) *PluginAnalyticsCreate {
	if v != nil {
		_c.SetDownloads(*v)
	}
	return _c
}

// SetViews sets the "views" field.
func (_c *PluginAnalyticsCreate) SetViews(v int) *PluginAnalyticsCreate {
	_c.mutation.SetViews(v)
	return _c
}

// SetNillableViews sets the "views" field if the given value is not nil.
func (_c *PluginAnalyticsCreate) SetNillableViews(v *int) *PluginAnalyticsCreate {
	if v != nil {
		_c.SetViews(*v)
	}
	return _c
}

// SetID sets the "id" field.
func (_c *PluginAnalyticsCreate) SetID(v string) *PluginAnalyticsCreate {
	_c.mutation.SetID(v)
	return _c
}

// SetNillableID sets the "id" field if the given value is not nil.
func (_c *PluginAnalyticsCreate) SetNillableID(v *string) *PluginAnalyticsCreate {
	if v != nil {
		_c.SetID(*v)
	}
	return _c
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_c *PluginAnalyticsCreate) SetPluginID(id string) *PluginAnalyticsCreate {
	_c.mutation.SetPluginID(id)
	return _c
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_c *PluginAnalyticsCreate) SetPlugin(v *Plugin) *PluginAnalyticsCreate {
	return _c.SetPluginID(v.ID)
}

// Mutation returns the PluginAnalyticsMutation object of the builder.
func (_c *PluginAnalyticsCreate) Mutation() *PluginAnalyticsMutation {
	return _c.mutation
}

// Save creates the PluginAnalytics in the database.
func (_c *PluginAnalyticsCreate) Save(ctx context.Context) (*PluginAnalytics, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *PluginAnalyticsCreate) SaveX(ctx context.Context) *PluginAnalytics {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginAnalyticsCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginAnalyticsCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *PluginAnalyticsCreate) defaults() {
	if _, ok := _c.mutation.Downloads(); !ok {
		v := pluginanalytics.DefaultDownloads
		_c.mutation.SetDownloads(v)
	}
	if _, ok := _c.mutation.Views(); !ok {
		v := pluginanalytics.DefaultViews
		_c.mutation.SetViews(v)
	}
	if _, ok := _c.mutation.ID(); !ok {
		v := pluginanalytics.DefaultID()
		_c.mutation.SetID(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *PluginAnalyticsCreate) check() error {
	if _, ok := _c.mutation.PluginId(); !ok {
		return &ValidationError{Name: "pluginId", err: errors.New(`ent: missing required field "PluginAnalytics.pluginId"`)}
	}
	if _, ok := _c.mutation.Date(); !ok {
		return &ValidationError{Name: "date", err: errors.New(`ent: missing required field "PluginAnalytics.date"`)}
	}
	if _, ok := _c.mutation.Downloads(); !ok {
		return &ValidationError{Name: "downloads", err: errors.New(`ent: missing required field "PluginAnalytics.downloads"`)}
	}
	if _, ok := _c.mutation.Views(); !ok {
		return &ValidationError{Name: "views", err: errors.New(`ent: missing required field "PluginAnalytics.views"`)}
	}
	if len(_c.mutation.PluginIDs()) == 0 {
		return &ValidationError{Name: "plugin", err: errors.New(`ent: missing required edge "PluginAnalytics.plugin"`)}
	}
	return nil
}

func (_c *PluginAnalyticsCreate) sqlSave(ctx context.Context) (*PluginAnalytics, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	if _spec.ID.Value != nil {
		if id, ok := _spec.ID.Value.(string); ok {
			_node.ID = id
		} else {
			return nil, fmt.Errorf("unexpected PluginAnalytics.ID type: %T", _spec.ID.Value)
		}
	}
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *PluginAnalyticsCreate) createSpec() (*PluginAnalytics, *sqlgraph.CreateSpec) {
	var (
		_node = &PluginAnalytics{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(pluginanalytics.Table, sqlgraph.NewFieldSpec(pluginanalytics.FieldID, field.TypeString))
	)
	if id, ok := _c.mutation.ID(); ok {
		_node.ID = id
		_spec.ID.Value = id
	}
	if value, ok := _c.mutation.Date(); ok {
		_spec.SetField(pluginanalytics.FieldDate, field.TypeTime, value)
		_node.Date = value
	}
	if value, ok := _c.mutation.Downloads(); ok {
		_spec.SetField(pluginanalytics.FieldDownloads, field.TypeInt, value)
		_node.Downloads = value
	}
	if value, ok := _c.mutation.Views(); ok {
		_spec.SetField(pluginanalytics.FieldViews, field.TypeInt, value)
		_node.Views = value
	}
	if nodes := _c.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   pluginanalytics.PluginTable,
			Columns: []string{pluginanalytics.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.PluginId = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// PluginAnalyticsCreateBulk is the builder for creating many PluginAnalytics entities in bulk.
type PluginAnalyticsCreateBulk struct {
	config
	err      error
	builders []*PluginAnalyticsCreate
}

// Save creates the PluginAnalytics entities in the database.
func (_c *PluginAnalyticsCreateBulk) Save(ctx context.Context) ([]*PluginAnalytics, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*PluginAnalytics, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*PluginAnalyticsMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *PluginAnalyticsCreateBulk) SaveX(ctx context.Context) []*PluginAnalytics {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *PluginAnalyticsCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *PluginAnalyticsCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}
