// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/report"
	"github.com/EndGitHQ/endgit-core/ent/user"
)

// Report is the model entity for the Report schema.
type Report struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// Reason holds the value of the "reason" field.
	Reason report.Reason `json:"reason,omitempty"`
	// Details holds the value of the "details" field.
	Details *string `json:"details,omitempty"`
	// Resolved holds the value of the "resolved" field.
	Resolved bool `json:"resolved,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// ReporterId holds the value of the "reporterId" field.
	ReporterId string `json:"reporterId,omitempty"`
	// PluginId holds the value of the "pluginId" field.
	PluginId string `json:"pluginId,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the ReportQuery when eager-loading is set.
	Edges        ReportEdges `json:"edges"`
	selectValues sql.SelectValues
}

// ReportEdges holds the relations/edges for other nodes in the graph.
type ReportEdges struct {
	// Reporter holds the value of the reporter edge.
	Reporter *User `json:"reporter,omitempty"`
	// Plugin holds the value of the plugin edge.
	Plugin *Plugin `json:"plugin,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [2]bool
}

// ReporterOrErr returns the Reporter value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReportEdges) ReporterOrErr() (*User, error) {
	if e.Reporter != nil {
		return e.Reporter, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "reporter"}
}

// PluginOrErr returns the Plugin value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e ReportEdges) PluginOrErr() (*Plugin, error) {
	if e.Plugin != nil {
		return e.Plugin, nil
	} else if e.loadedTypes[1] {
		return nil, &NotFoundError{label: plugin.Label}
	}
	return nil, &NotLoadedError{edge: "plugin"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*Report) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case report.FieldResolved:
			values[i] = new(sql.NullBool)
		case report.FieldID, report.FieldReason, report.FieldDetails, report.FieldReporterId, report.FieldPluginId:
			values[i] = new(sql.NullString)
		case report.FieldCreatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the Report fields.
func (_m *Report) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case report.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case report.FieldReason:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reason", values[i])
			} else if value.Valid {
				_m.Reason = report.Reason(value.String)
			}
		case report.FieldDetails:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field details", values[i])
			} else if value.Valid {
				_m.Details = new(string)
				*_m.Details = value.String
			}
		case report.FieldResolved:
			if value, ok := values[i].(*sql.NullBool); !ok {
				return fmt.Errorf("unexpected type %T for field resolved", values[i])
			} else if value.Valid {
				_m.Resolved = value.Bool
			}
		case report.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case report.FieldReporterId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field reporterId", values[i])
			} else if value.Valid {
				_m.ReporterId = value.String
			}
		case report.FieldPluginId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field pluginId", values[i])
			} else if value.Valid {
				_m.PluginId = value.String
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the Report.
// This includes values selected through modifiers, order, etc.
func (_m *Report) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryReporter queries the "reporter" edge of the Report entity.
func (_m *Report) QueryReporter() *UserQuery {
	return NewReportClient(_m.config).QueryReporter(_m)
}

// QueryPlugin queries the "plugin" edge of the Report entity.
func (_m *Report) QueryPlugin() *PluginQuery {
	return NewReportClient(_m.config).QueryPlugin(_m)
}

// Update returns a builder for updating this Report.
// Note that you need to call Report.Unwrap() before calling this method if this Report
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *Report) Update() *ReportUpdateOne {
	return NewReportClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the Report entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *Report) Unwrap() *Report {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: Report is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *Report) String() string {
	var builder strings.Builder
	builder.WriteString("Report(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("reason=")
	builder.WriteString(fmt.Sprintf("%v", _m.Reason))
	builder.WriteString(", ")
	if v := _m.Details; v != nil {
		builder.WriteString("details=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("resolved=")
	builder.WriteString(fmt.Sprintf("%v", _m.Resolved))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("reporterId=")
	builder.WriteString(_m.ReporterId)
	builder.WriteString(", ")
	builder.WriteString("pluginId=")
	builder.WriteString(_m.PluginId)
	builder.WriteByte(')')
	return builder.String()
}

// Reports is a parsable slice of Report.
type Reports []*Report
