// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
	"github.com/EndGitHQ/endgit-core/ent/report"
	"github.com/EndGitHQ/endgit-core/ent/user"
)

// ReportUpdate is the builder for updating Report entities.
type ReportUpdate struct {
	config
	hooks    []Hook
	mutation *ReportMutation
}

// Where appends a list predicates to the ReportUpdate builder.
func (_u *ReportUpdate) Where(ps ...predicate.Report) *ReportUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetReason sets the "reason" field.
func (_u *ReportUpdate) SetReason(v report.Reason) *ReportUpdate {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableReason(v *report.Reason) *ReportUpdate {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *ReportUpdate) SetDetails(v string) *ReportUpdate {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableDetails(v *string) *ReportUpdate {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *ReportUpdate) ClearDetails() *ReportUpdate {
	_u.mutation.ClearDetails()
	return _u
}

// SetResolved sets the "resolved" field.
func (_u *ReportUpdate) SetResolved(v bool) *ReportUpdate {
	_u.mutation.SetResolved(v)
	return _u
}

// SetNillableResolved sets the "resolved" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableResolved(v *bool) *ReportUpdate {
	if v != nil {
		_u.SetResolved(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *ReportUpdate) SetCreatedAt(v time.Time) *ReportUpdate {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableCreatedAt(v *time.Time) *ReportUpdate {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReporterId sets the "reporterId" field.
func (_u *ReportUpdate) SetReporterId(v string) *ReportUpdate {
	_u.mutation.SetReporterId(v)
	return _u
}

// SetNillableReporterId sets the "reporterId" field if the given value is not nil.
func (_u *ReportUpdate) SetNillableReporterId(v *string) *ReportUpdate {
	if v != nil {
		_u.SetReporterId(*v)
	}
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *ReportUpdate) SetPluginId(v string) *ReportUpdate {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *ReportUpdate) SetNillablePluginId(v *string) *ReportUpdate {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// SetReporterID sets the "reporter" edge to the User entity by ID.
func (_u *ReportUpdate) SetReporterID(id string) *ReportUpdate {
	_u.mutation.SetReporterID(id)
	return _u
}

// SetReporter sets the "reporter" edge to the User entity.
func (_u *ReportUpdate) SetReporter(v *User) *ReportUpdate {
	return _u.SetReporterID(v.ID)
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *ReportUpdate) SetPluginID(id string) *ReportUpdate {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *ReportUpdate) SetPlugin(v *Plugin) *ReportUpdate {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the ReportMutation object of the builder.
func (_u *ReportUpdate) Mutation() *ReportMutation {
	return _u.mutation
}

// ClearReporter clears the "reporter" edge to the User entity.
func (_u *ReportUpdate) ClearReporter() *ReportUpdate {
	_u.mutation.ClearReporter()
	return _u
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *ReportUpdate) ClearPlugin() *ReportUpdate {
	_u.mutation.ClearPlugin()
	return _u
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *ReportUpdate) Save(ctx context.Context) (int, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *ReportUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportUpdate) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	if _u.mutation.ReporterCleared() && len(_u.mutation.ReporterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Report.reporter"`)
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Report.plugin"`)
	}
	return nil
}

func (_u *ReportUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeString))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(report.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(report.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.Resolved(); ok {
		_spec.SetField(report.FieldResolved, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(report.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReporterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.ReporterTable,
			Columns: []string{report.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.ReporterTable,
			Columns: []string{report.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.PluginTable,
			Columns: []string{report.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.PluginTable,
			Columns: []string{report.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// ReportUpdateOne is the builder for updating a single Report entity.
type ReportUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *ReportMutation
}

// SetReason sets the "reason" field.
func (_u *ReportUpdateOne) SetReason(v report.Reason) *ReportUpdateOne {
	_u.mutation.SetReason(v)
	return _u
}

// SetNillableReason sets the "reason" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableReason(v *report.Reason) *ReportUpdateOne {
	if v != nil {
		_u.SetReason(*v)
	}
	return _u
}

// SetDetails sets the "details" field.
func (_u *ReportUpdateOne) SetDetails(v string) *ReportUpdateOne {
	_u.mutation.SetDetails(v)
	return _u
}

// SetNillableDetails sets the "details" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableDetails(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetDetails(*v)
	}
	return _u
}

// ClearDetails clears the value of the "details" field.
func (_u *ReportUpdateOne) ClearDetails() *ReportUpdateOne {
	_u.mutation.ClearDetails()
	return _u
}

// SetResolved sets the "resolved" field.
func (_u *ReportUpdateOne) SetResolved(v bool) *ReportUpdateOne {
	_u.mutation.SetResolved(v)
	return _u
}

// SetNillableResolved sets the "resolved" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableResolved(v *bool) *ReportUpdateOne {
	if v != nil {
		_u.SetResolved(*v)
	}
	return _u
}

// SetCreatedAt sets the "createdAt" field.
func (_u *ReportUpdateOne) SetCreatedAt(v time.Time) *ReportUpdateOne {
	_u.mutation.SetCreatedAt(v)
	return _u
}

// SetNillableCreatedAt sets the "createdAt" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableCreatedAt(v *time.Time) *ReportUpdateOne {
	if v != nil {
		_u.SetCreatedAt(*v)
	}
	return _u
}

// SetReporterId sets the "reporterId" field.
func (_u *ReportUpdateOne) SetReporterId(v string) *ReportUpdateOne {
	_u.mutation.SetReporterId(v)
	return _u
}

// SetNillableReporterId sets the "reporterId" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillableReporterId(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetReporterId(*v)
	}
	return _u
}

// SetPluginId sets the "pluginId" field.
func (_u *ReportUpdateOne) SetPluginId(v string) *ReportUpdateOne {
	_u.mutation.SetPluginId(v)
	return _u
}

// SetNillablePluginId sets the "pluginId" field if the given value is not nil.
func (_u *ReportUpdateOne) SetNillablePluginId(v *string) *ReportUpdateOne {
	if v != nil {
		_u.SetPluginId(*v)
	}
	return _u
}

// SetReporterID sets the "reporter" edge to the User entity by ID.
func (_u *ReportUpdateOne) SetReporterID(id string) *ReportUpdateOne {
	_u.mutation.SetReporterID(id)
	return _u
}

// SetReporter sets the "reporter" edge to the User entity.
func (_u *ReportUpdateOne) SetReporter(v *User) *ReportUpdateOne {
	return _u.SetReporterID(v.ID)
}

// SetPluginID sets the "plugin" edge to the Plugin entity by ID.
func (_u *ReportUpdateOne) SetPluginID(id string) *ReportUpdateOne {
	_u.mutation.SetPluginID(id)
	return _u
}

// SetPlugin sets the "plugin" edge to the Plugin entity.
func (_u *ReportUpdateOne) SetPlugin(v *Plugin) *ReportUpdateOne {
	return _u.SetPluginID(v.ID)
}

// Mutation returns the ReportMutation object of the builder.
func (_u *ReportUpdateOne) Mutation() *ReportMutation {
	return _u.mutation
}

// ClearReporter clears the "reporter" edge to the User entity.
func (_u *ReportUpdateOne) ClearReporter() *ReportUpdateOne {
	_u.mutation.ClearReporter()
	return _u
}

// ClearPlugin clears the "plugin" edge to the Plugin entity.
func (_u *ReportUpdateOne) ClearPlugin() *ReportUpdateOne {
	_u.mutation.ClearPlugin()
	return _u
}

// Where appends a list predicates to the ReportUpdate builder.
func (_u *ReportUpdateOne) Where(ps ...predicate.Report) *ReportUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *ReportUpdateOne) Select(field string, fields ...string) *ReportUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated Report entity.
func (_u *ReportUpdateOne) Save(ctx context.Context) (*Report, error) {
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *ReportUpdateOne) SaveX(ctx context.Context) *Report {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *ReportUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *ReportUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *ReportUpdateOne) check() error {
	if v, ok := _u.mutation.Reason(); ok {
		if err := report.ReasonValidator(v); err != nil {
			return &ValidationError{Name: "reason", err: fmt.Errorf(`ent: validator failed for field "Report.reason": %w`, err)}
		}
	}
	if _u.mutation.ReporterCleared() && len(_u.mutation.ReporterIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Report.reporter"`)
	}
	if _u.mutation.PluginCleared() && len(_u.mutation.PluginIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "Report.plugin"`)
	}
	return nil
}

func (_u *ReportUpdateOne) sqlSave(ctx context.Context) (_node *Report, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(report.Table, report.Columns, sqlgraph.NewFieldSpec(report.FieldID, field.TypeString))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "Report.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, report.FieldID)
		for _, f := range fields {
			if !report.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != report.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.Reason(); ok {
		_spec.SetField(report.FieldReason, field.TypeEnum, value)
	}
	if value, ok := _u.mutation.Details(); ok {
		_spec.SetField(report.FieldDetails, field.TypeString, value)
	}
	if _u.mutation.DetailsCleared() {
		_spec.ClearField(report.FieldDetails, field.TypeString)
	}
	if value, ok := _u.mutation.Resolved(); ok {
		_spec.SetField(report.FieldResolved, field.TypeBool, value)
	}
	if value, ok := _u.mutation.CreatedAt(); ok {
		_spec.SetField(report.FieldCreatedAt, field.TypeTime, value)
	}
	if _u.mutation.ReporterCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.ReporterTable,
			Columns: []string{report.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.ReporterIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.ReporterTable,
			Columns: []string{report.ReporterColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.PluginCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.PluginTable,
			Columns: []string{report.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.PluginIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.M2O,
			Inverse: false,
			Table:   report.PluginTable,
			Columns: []string{report.PluginColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(plugin.FieldID, field.TypeString),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &Report{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{report.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
