// Code generated by ent, DO NOT EDIT.

package ent

import (
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/EndGitHQ/endgit-core/ent/user"
)

// User is the model entity for the User schema.
type User struct {
	config `json:"-"`
	// ID of the ent.
	ID string `json:"id,omitempty"`
	// GithubId holds the value of the "githubId" field.
	GithubId string `json:"githubId,omitempty"`
	// Username holds the value of the "username" field.
	Username string `json:"username,omitempty"`
	// DisplayName holds the value of the "displayName" field.
	DisplayName *string `json:"displayName,omitempty"`
	// Email holds the value of the "email" field.
	Email *string `json:"email,omitempty"`
	// AvatarUrl holds the value of the "avatarUrl" field.
	AvatarUrl *string `json:"avatarUrl,omitempty"`
	// Bio holds the value of the "bio" field.
	Bio *string `json:"bio,omitempty"`
	// TrustLevel holds the value of the "trustLevel" field.
	TrustLevel user.TrustLevel `json:"trustLevel,omitempty"`
	// TrustScore holds the value of the "trustScore" field.
	TrustScore int `json:"trustScore,omitempty"`
	// WeeklyBuildQuota holds the value of the "weeklyBuildQuota" field.
	WeeklyBuildQuota int `json:"weeklyBuildQuota,omitempty"`
	// WeeklyBuildCount holds the value of the "weeklyBuildCount" field.
	WeeklyBuildCount int `json:"weeklyBuildCount,omitempty"`
	// QuotaResetAt holds the value of the "quotaResetAt" field.
	QuotaResetAt time.Time `json:"quotaResetAt,omitempty"`
	// CreatedAt holds the value of the "createdAt" field.
	CreatedAt time.Time `json:"createdAt,omitempty"`
	// UpdatedAt holds the value of the "updatedAt" field.
	UpdatedAt time.Time `json:"updatedAt,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the UserQuery when eager-loading is set.
	Edges        UserEdges `json:"edges"`
	selectValues sql.SelectValues
}

// UserEdges holds the relations/edges for other nodes in the graph.
type UserEdges struct {
	// Plugins holds the value of the plugins edge.
	Plugins []*Plugin `json:"plugins,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// Sessions holds the value of the sessions edge.
	Sessions []*Session `json:"sessions,omitempty"`
	// Reviews holds the value of the reviews edge.
	Reviews []*Review `json:"reviews,omitempty"`
	// Reports holds the value of the reports edge.
	Reports []*Report `json:"reports,omitempty"`
	// Ratings holds the value of the ratings edge.
	Ratings []*Rating `json:"ratings,omitempty"`
	// PluginComments holds the value of the pluginComments edge.
	PluginComments []*PluginComment `json:"pluginComments,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [7]bool
}

// PluginsOrErr returns the Plugins value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) PluginsOrErr() ([]*Plugin, error) {
	if e.loadedTypes[0] {
		return e.Plugins, nil
	}
	return nil, &NotLoadedError{edge: "plugins"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[1] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// SessionsOrErr returns the Sessions value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) SessionsOrErr() ([]*Session, error) {
	if e.loadedTypes[2] {
		return e.Sessions, nil
	}
	return nil, &NotLoadedError{edge: "sessions"}
}

// ReviewsOrErr returns the Reviews value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ReviewsOrErr() ([]*Review, error) {
	if e.loadedTypes[3] {
		return e.Reviews, nil
	}
	return nil, &NotLoadedError{edge: "reviews"}
}

// ReportsOrErr returns the Reports value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) ReportsOrErr() ([]*Report, error) {
	if e.loadedTypes[4] {
		return e.Reports, nil
	}
	return nil, &NotLoadedError{edge: "reports"}
}

// RatingsOrErr returns the Ratings value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) RatingsOrErr() ([]*Rating, error) {
	if e.loadedTypes[5] {
		return e.Ratings, nil
	}
	return nil, &NotLoadedError{edge: "ratings"}
}

// PluginCommentsOrErr returns the PluginComments value or an error if the edge
// was not loaded in eager-loading.
func (e UserEdges) PluginCommentsOrErr() ([]*PluginComment, error) {
	if e.loadedTypes[6] {
		return e.PluginComments, nil
	}
	return nil, &NotLoadedError{edge: "pluginComments"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*User) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case user.FieldTrustScore, user.FieldWeeklyBuildQuota, user.FieldWeeklyBuildCount:
			values[i] = new(sql.NullInt64)
		case user.FieldID, user.FieldGithubId, user.FieldUsername, user.FieldDisplayName, user.FieldEmail, user.FieldAvatarUrl, user.FieldBio, user.FieldTrustLevel:
			values[i] = new(sql.NullString)
		case user.FieldQuotaResetAt, user.FieldCreatedAt, user.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the User fields.
func (_m *User) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case user.FieldID:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field id", values[i])
			} else if value.Valid {
				_m.ID = value.String
			}
		case user.FieldGithubId:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field githubId", values[i])
			} else if value.Valid {
				_m.GithubId = value.String
			}
		case user.FieldUsername:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field username", values[i])
			} else if value.Valid {
				_m.Username = value.String
			}
		case user.FieldDisplayName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field displayName", values[i])
			} else if value.Valid {
				_m.DisplayName = new(string)
				*_m.DisplayName = value.String
			}
		case user.FieldEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field email", values[i])
			} else if value.Valid {
				_m.Email = new(string)
				*_m.Email = value.String
			}
		case user.FieldAvatarUrl:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field avatarUrl", values[i])
			} else if value.Valid {
				_m.AvatarUrl = new(string)
				*_m.AvatarUrl = value.String
			}
		case user.FieldBio:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field bio", values[i])
			} else if value.Valid {
				_m.Bio = new(string)
				*_m.Bio = value.String
			}
		case user.FieldTrustLevel:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field trustLevel", values[i])
			} else if value.Valid {
				_m.TrustLevel = user.TrustLevel(value.String)
			}
		case user.FieldTrustScore:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field trustScore", values[i])
			} else if value.Valid {
				_m.TrustScore = int(value.Int64)
			}
		case user.FieldWeeklyBuildQuota:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weeklyBuildQuota", values[i])
			} else if value.Valid {
				_m.WeeklyBuildQuota = int(value.Int64)
			}
		case user.FieldWeeklyBuildCount:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field weeklyBuildCount", values[i])
			} else if value.Valid {
				_m.WeeklyBuildCount = int(value.Int64)
			}
		case user.FieldQuotaResetAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field quotaResetAt", values[i])
			} else if value.Valid {
				_m.QuotaResetAt = value.Time
			}
		case user.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field createdAt", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case user.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updatedAt", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the User.
// This includes values selected through modifiers, order, etc.
func (_m *User) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryPlugins queries the "plugins" edge of the User entity.
func (_m *User) QueryPlugins() *PluginQuery {
	return NewUserClient(_m.config).QueryPlugins(_m)
}

// QueryAccounts queries the "accounts" edge of the User entity.
func (_m *User) QueryAccounts() *AccountQuery {
	return NewUserClient(_m.config).QueryAccounts(_m)
}

// QuerySessions queries the "sessions" edge of the User entity.
func (_m *User) QuerySessions() *SessionQuery {
	return NewUserClient(_m.config).QuerySessions(_m)
}

// QueryReviews queries the "reviews" edge of the User entity.
func (_m *User) QueryReviews() *ReviewQuery {
	return NewUserClient(_m.config).QueryReviews(_m)
}

// QueryReports queries the "reports" edge of the User entity.
func (_m *User) QueryReports() *ReportQuery {
	return NewUserClient(_m.config).QueryReports(_m)
}

// QueryRatings queries the "ratings" edge of the User entity.
func (_m *User) QueryRatings() *RatingQuery {
	return NewUserClient(_m.config).QueryRatings(_m)
}

// QueryPluginComments queries the "pluginComments" edge of the User entity.
func (_m *User) QueryPluginComments() *PluginCommentQuery {
	return NewUserClient(_m.config).QueryPluginComments(_m)
}

// Update returns a builder for updating this User.
// Note that you need to call User.Unwrap() before calling this method if this User
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *User) Update() *UserUpdateOne {
	return NewUserClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the User entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *User) Unwrap() *User {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: User is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *User) String() string {
	var builder strings.Builder
	builder.WriteString("User(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("githubId=")
	builder.WriteString(_m.GithubId)
	builder.WriteString(", ")
	builder.WriteString("username=")
	builder.WriteString(_m.Username)
	builder.WriteString(", ")
	if v := _m.DisplayName; v != nil {
		builder.WriteString("displayName=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Email; v != nil {
		builder.WriteString("email=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.AvatarUrl; v != nil {
		builder.WriteString("avatarUrl=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	if v := _m.Bio; v != nil {
		builder.WriteString("bio=")
		builder.WriteString(*v)
	}
	builder.WriteString(", ")
	builder.WriteString("trustLevel=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrustLevel))
	builder.WriteString(", ")
	builder.WriteString("trustScore=")
	builder.WriteString(fmt.Sprintf("%v", _m.TrustScore))
	builder.WriteString(", ")
	builder.WriteString("weeklyBuildQuota=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyBuildQuota))
	builder.WriteString(", ")
	builder.WriteString("weeklyBuildCount=")
	builder.WriteString(fmt.Sprintf("%v", _m.WeeklyBuildCount))
	builder.WriteString(", ")
	builder.WriteString("quotaResetAt=")
	builder.WriteString(_m.QuotaResetAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("createdAt=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updatedAt=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// Users is a parsable slice of User.
type Users []*User
