// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"database/sql/driver"
	"fmt"
	"math"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/EndGitHQ/endgit-core/ent/dependency"
	"github.com/EndGitHQ/endgit-core/ent/plugin"
	"github.com/EndGitHQ/endgit-core/ent/predicate"
	"github.com/EndGitHQ/endgit-core/ent/producer"
	"github.com/EndGitHQ/endgit-core/ent/version"
)

// VersionQuery is the builder for querying Version entities.
type VersionQuery struct {
	config
	ctx              *QueryContext
	order            []version.OrderOption
	inters           []Interceptor
	predicates       []predicate.Version
	withPlugin       *PluginQuery
	withDependencies *DependencyQuery
	withProducers    *ProducerQuery
	// intermediate query (i.e. traversal path).
	sql  *sql.Selector
	path func(context.Context) (*sql.Selector, error)
}

// Where adds a new predicate for the VersionQuery builder.
func (_q *VersionQuery) Where(ps ...predicate.Version) *VersionQuery {
	_q.predicates = append(_q.predicates, ps...)
	return _q
}

// Limit the number of records to be returned by this query.
func (_q *VersionQuery) Limit(limit int) *VersionQuery {
	_q.ctx.Limit = &limit
	return _q
}

// Offset to start from.
func (_q *VersionQuery) Offset(offset int) *VersionQuery {
	_q.ctx.Offset = &offset
	return _q
}

// Unique configures the query builder to filter duplicate records on query.
// By default, unique is set to true, and can be disabled using this method.
func (_q *VersionQuery) Unique(unique bool) *VersionQuery {
	_q.ctx.Unique = &unique
	return _q
}

// Order specifies how the records should be ordered.
func (_q *VersionQuery) Order(o ...version.OrderOption) *VersionQuery {
	_q.order = append(_q.order, o...)
	return _q
}

// QueryPlugin chains the current query on the "plugin" edge.
func (_q *VersionQuery) QueryPlugin() *PluginQuery {
	query := (&PluginClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(version.Table, version.FieldID, selector),
			sqlgraph.To(plugin.Table, plugin.FieldID),
			sqlgraph.Edge(sqlgraph.M2O, false, version.PluginTable, version.PluginColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryDependencies chains the current query on the "dependencies" edge.
func (_q *VersionQuery) QueryDependencies() *DependencyQuery {
	query := (&DependencyClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(version.Table, version.FieldID, selector),
			sqlgraph.To(dependency.Table, dependency.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, version.DependenciesTable, version.DependenciesColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// QueryProducers chains the current query on the "producers" edge.
func (_q *VersionQuery) QueryProducers() *ProducerQuery {
	query := (&ProducerClient{config: _q.config}).Query()
	query.path = func(ctx context.Context) (fromU *sql.Selector, err error) {
		if err := _q.prepareQuery(ctx); err != nil {
			return nil, err
		}
		selector := _q.sqlQuery(ctx)
		if err := selector.Err(); err != nil {
			return nil, err
		}
		step := sqlgraph.NewStep(
			sqlgraph.From(version.Table, version.FieldID, selector),
			sqlgraph.To(producer.Table, producer.FieldID),
			sqlgraph.Edge(sqlgraph.O2M, true, version.ProducersTable, version.ProducersColumn),
		)
		fromU = sqlgraph.SetNeighbors(_q.driver.Dialect(), step)
		return fromU, nil
	}
	return query
}

// First returns the first Version entity from the query.
// Returns a *NotFoundError when no Version was found.
func (_q *VersionQuery) First(ctx context.Context) (*Version, error) {
	nodes, err := _q.Limit(1).All(setContextOp(ctx, _q.ctx, ent.OpQueryFirst))
	if err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nil, &NotFoundError{version.Label}
	}
	return nodes[0], nil
}

// FirstX is like First, but panics if an error occurs.
func (_q *VersionQuery) FirstX(ctx context.Context) *Version {
	node, err := _q.First(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return node
}

// FirstID returns the first Version ID from the query.
// Returns a *NotFoundError when no Version ID was found.
func (_q *VersionQuery) FirstID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(1).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryFirstID)); err != nil {
		return
	}
	if len(ids) == 0 {
		err = &NotFoundError{version.Label}
		return
	}
	return ids[0], nil
}

// FirstIDX is like FirstID, but panics if an error occurs.
func (_q *VersionQuery) FirstIDX(ctx context.Context) string {
	id, err := _q.FirstID(ctx)
	if err != nil && !IsNotFound(err) {
		panic(err)
	}
	return id
}

// Only returns a single Version entity found by the query, ensuring it only returns one.
// Returns a *NotSingularError when more than one Version entity is found.
// Returns a *NotFoundError when no Version entities are found.
func (_q *VersionQuery) Only(ctx context.Context) (*Version, error) {
	nodes, err := _q.Limit(2).All(setContextOp(ctx, _q.ctx, ent.OpQueryOnly))
	if err != nil {
		return nil, err
	}
	switch len(nodes) {
	case 1:
		return nodes[0], nil
	case 0:
		return nil, &NotFoundError{version.Label}
	default:
		return nil, &NotSingularError{version.Label}
	}
}

// OnlyX is like Only, but panics if an error occurs.
func (_q *VersionQuery) OnlyX(ctx context.Context) *Version {
	node, err := _q.Only(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// OnlyID is like Only, but returns the only Version ID in the query.
// Returns a *NotSingularError when more than one Version ID is found.
// Returns a *NotFoundError when no entities are found.
func (_q *VersionQuery) OnlyID(ctx context.Context) (id string, err error) {
	var ids []string
	if ids, err = _q.Limit(2).IDs(setContextOp(ctx, _q.ctx, ent.OpQueryOnlyID)); err != nil {
		return
	}
	switch len(ids) {
	case 1:
		id = ids[0]
	case 0:
		err = &NotFoundError{version.Label}
	default:
		err = &NotSingularError{version.Label}
	}
	return
}

// OnlyIDX is like OnlyID, but panics if an error occurs.
func (_q *VersionQuery) OnlyIDX(ctx context.Context) string {
	id, err := _q.OnlyID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// All executes the query and returns a list of Versions.
func (_q *VersionQuery) All(ctx context.Context) ([]*Version, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryAll)
	if err := _q.prepareQuery(ctx); err != nil {
		return nil, err
	}
	qr := querierAll[[]*Version, *VersionQuery]()
	return withInterceptors[[]*Version](ctx, _q, qr, _q.inters)
}

// AllX is like All, but panics if an error occurs.
func (_q *VersionQuery) AllX(ctx context.Context) []*Version {
	nodes, err := _q.All(ctx)
	if err != nil {
		panic(err)
	}
	return nodes
}

// IDs executes the query and returns a list of Version IDs.
func (_q *VersionQuery) IDs(ctx context.Context) (ids []string, err error) {
	if _q.ctx.Unique == nil && _q.path != nil {
		_q.Unique(true)
	}
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryIDs)
	if err = _q.Select(version.FieldID).Scan(ctx, &ids); err != nil {
		return nil, err
	}
	return ids, nil
}

// IDsX is like IDs, but panics if an error occurs.
func (_q *VersionQuery) IDsX(ctx context.Context) []string {
	ids, err := _q.IDs(ctx)
	if err != nil {
		panic(err)
	}
	return ids
}

// Count returns the count of the given query.
func (_q *VersionQuery) Count(ctx context.Context) (int, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryCount)
	if err := _q.prepareQuery(ctx); err != nil {
		return 0, err
	}
	return withInterceptors[int](ctx, _q, querierCount[*VersionQuery](), _q.inters)
}

// CountX is like Count, but panics if an error occurs.
func (_q *VersionQuery) CountX(ctx context.Context) int {
	count, err := _q.Count(ctx)
	if err != nil {
		panic(err)
	}
	return count
}

// Exist returns true if the query has elements in the graph.
func (_q *VersionQuery) Exist(ctx context.Context) (bool, error) {
	ctx = setContextOp(ctx, _q.ctx, ent.OpQueryExist)
	switch _, err := _q.FirstID(ctx); {
	case IsNotFound(err):
		return false, nil
	case err != nil:
		return false, fmt.Errorf("ent: check existence: %w", err)
	default:
		return true, nil
	}
}

// ExistX is like Exist, but panics if an error occurs.
func (_q *VersionQuery) ExistX(ctx context.Context) bool {
	exist, err := _q.Exist(ctx)
	if err != nil {
		panic(err)
	}
	return exist
}

// Clone returns a duplicate of the VersionQuery builder, including all associated steps. It can be
// used to prepare common query builders and use them differently after the clone is made.
func (_q *VersionQuery) Clone() *VersionQuery {
	if _q == nil {
		return nil
	}
	return &VersionQuery{
		config:           _q.config,
		ctx:              _q.ctx.Clone(),
		order:            append([]version.OrderOption{}, _q.order...),
		inters:           append([]Interceptor{}, _q.inters...),
		predicates:       append([]predicate.Version{}, _q.predicates...),
		withPlugin:       _q.withPlugin.Clone(),
		withDependencies: _q.withDependencies.Clone(),
		withProducers:    _q.withProducers.Clone(),
		// clone intermediate query.
		sql:  _q.sql.Clone(),
		path: _q.path,
	}
}

// WithPlugin tells the query-builder to eager-load the nodes that are connected to
// the "plugin" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VersionQuery) WithPlugin(opts ...func(*PluginQuery)) *VersionQuery {
	query := (&PluginClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withPlugin = query
	return _q
}

// WithDependencies tells the query-builder to eager-load the nodes that are connected to
// the "dependencies" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VersionQuery) WithDependencies(opts ...func(*DependencyQuery)) *VersionQuery {
	query := (&DependencyClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withDependencies = query
	return _q
}

// WithProducers tells the query-builder to eager-load the nodes that are connected to
// the "producers" edge. The optional arguments are used to configure the query builder of the edge.
func (_q *VersionQuery) WithProducers(opts ...func(*ProducerQuery)) *VersionQuery {
	query := (&ProducerClient{config: _q.config}).Query()
	for _, opt := range opts {
		opt(query)
	}
	_q.withProducers = query
	return _q
}

// GroupBy is used to group vertices by one or more fields/columns.
// It is often used with aggregate functions, like: count, max, mean, min, sum.
//
// Example:
//
//	var v []struct {
//		Version string `json:"version,omitempty"`
//		Count int `json:"count,omitempty"`
//	}
//
//	client.Version.Query().
//		GroupBy(version.FieldVersion).
//		Aggregate(ent.Count()).
//		Scan(ctx, &v)
func (_q *VersionQuery) GroupBy(field string, fields ...string) *VersionGroupBy {
	_q.ctx.Fields = append([]string{field}, fields...)
	grbuild := &VersionGroupBy{build: _q}
	grbuild.flds = &_q.ctx.Fields
	grbuild.label = version.Label
	grbuild.scan = grbuild.Scan
	return grbuild
}

// Select allows the selection one or more fields/columns for the given query,
// instead of selecting all fields in the entity.
//
// Example:
//
//	var v []struct {
//		Version string `json:"version,omitempty"`
//	}
//
//	client.Version.Query().
//		Select(version.FieldVersion).
//		Scan(ctx, &v)
func (_q *VersionQuery) Select(fields ...string) *VersionSelect {
	_q.ctx.Fields = append(_q.ctx.Fields, fields...)
	sbuild := &VersionSelect{VersionQuery: _q}
	sbuild.label = version.Label
	sbuild.flds, sbuild.scan = &_q.ctx.Fields, sbuild.Scan
	return sbuild
}

// Aggregate returns a VersionSelect configured with the given aggregations.
func (_q *VersionQuery) Aggregate(fns ...AggregateFunc) *VersionSelect {
	return _q.Select().Aggregate(fns...)
}

func (_q *VersionQuery) prepareQuery(ctx context.Context) error {
	for _, inter := range _q.inters {
		if inter == nil {
			return fmt.Errorf("ent: uninitialized interceptor (forgotten import ent/runtime?)")
		}
		if trv, ok := inter.(Traverser); ok {
			if err := trv.Traverse(ctx, _q); err != nil {
				return err
			}
		}
	}
	for _, f := range _q.ctx.Fields {
		if !version.ValidColumn(f) {
			return &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
		}
	}
	if _q.path != nil {
		prev, err := _q.path(ctx)
		if err != nil {
			return err
		}
		_q.sql = prev
	}
	return nil
}

func (_q *VersionQuery) sqlAll(ctx context.Context, hooks ...queryHook) ([]*Version, error) {
	var (
		nodes       = []*Version{}
		_spec       = _q.querySpec()
		loadedTypes = [3]bool{
			_q.withPlugin != nil,
			_q.withDependencies != nil,
			_q.withProducers != nil,
		}
	)
	_spec.ScanValues = func(columns []string) ([]any, error) {
		return (*Version).scanValues(nil, columns)
	}
	_spec.Assign = func(columns []string, values []any) error {
		node := &Version{config: _q.config}
		nodes = append(nodes, node)
		node.Edges.loadedTypes = loadedTypes
		return node.assignValues(columns, values)
	}
	for i := range hooks {
		hooks[i](ctx, _spec)
	}
	if err := sqlgraph.QueryNodes(ctx, _q.driver, _spec); err != nil {
		return nil, err
	}
	if len(nodes) == 0 {
		return nodes, nil
	}
	if query := _q.withPlugin; query != nil {
		if err := _q.loadPlugin(ctx, query, nodes, nil,
			func(n *Version, e *Plugin) { n.Edges.Plugin = e }); err != nil {
			return nil, err
		}
	}
	if query := _q.withDependencies; query != nil {
		if err := _q.loadDependencies(ctx, query, nodes,
			func(n *Version) { n.Edges.Dependencies = []*Dependency{} },
			func(n *Version, e *Dependency) { n.Edges.Dependencies = append(n.Edges.Dependencies, e) }); err != nil {
			return nil, err
		}
	}
	if query := _q.withProducers; query != nil {
		if err := _q.loadProducers(ctx, query, nodes,
			func(n *Version) { n.Edges.Producers = []*Producer{} },
			func(n *Version, e *Producer) { n.Edges.Producers = append(n.Edges.Producers, e) }); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

func (_q *VersionQuery) loadPlugin(ctx context.Context, query *PluginQuery, nodes []*Version, init func(*Version), assign func(*Version, *Plugin)) error {
	ids := make([]string, 0, len(nodes))
	nodeids := make(map[string][]*Version)
	for i := range nodes {
		fk := nodes[i].PluginId
		if _, ok := nodeids[fk]; !ok {
			ids = append(ids, fk)
		}
		nodeids[fk] = append(nodeids[fk], nodes[i])
	}
	if len(ids) == 0 {
		return nil
	}
	query.Where(plugin.IDIn(ids...))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		nodes, ok := nodeids[n.ID]
		if !ok {
			return fmt.Errorf(`unexpected foreign-key "pluginId" returned %v`, n.ID)
		}
		for i := range nodes {
			assign(nodes[i], n)
		}
	}
	return nil
}
func (_q *VersionQuery) loadDependencies(ctx context.Context, query *DependencyQuery, nodes []*Version, init func(*Version), assign func(*Version, *Dependency)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Version)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(dependency.FieldVersionId)
	}
	query.Where(predicate.Dependency(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(version.DependenciesColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VersionId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "versionId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}
func (_q *VersionQuery) loadProducers(ctx context.Context, query *ProducerQuery, nodes []*Version, init func(*Version), assign func(*Version, *Producer)) error {
	fks := make([]driver.Value, 0, len(nodes))
	nodeids := make(map[string]*Version)
	for i := range nodes {
		fks = append(fks, nodes[i].ID)
		nodeids[nodes[i].ID] = nodes[i]
		if init != nil {
			init(nodes[i])
		}
	}
	if len(query.ctx.Fields) > 0 {
		query.ctx.AppendFieldOnce(producer.FieldVersionId)
	}
	query.Where(predicate.Producer(func(s *sql.Selector) {
		s.Where(sql.InValues(s.C(version.ProducersColumn), fks...))
	}))
	neighbors, err := query.All(ctx)
	if err != nil {
		return err
	}
	for _, n := range neighbors {
		fk := n.VersionId
		node, ok := nodeids[fk]
		if !ok {
			return fmt.Errorf(`unexpected referenced foreign-key "versionId" returned %v for node %v`, fk, n.ID)
		}
		assign(node, n)
	}
	return nil
}

func (_q *VersionQuery) sqlCount(ctx context.Context) (int, error) {
	_spec := _q.querySpec()
	_spec.Node.Columns = _q.ctx.Fields
	if len(_q.ctx.Fields) > 0 {
		_spec.Unique = _q.ctx.Unique != nil && *_q.ctx.Unique
	}
	return sqlgraph.CountNodes(ctx, _q.driver, _spec)
}

func (_q *VersionQuery) querySpec() *sqlgraph.QuerySpec {
	_spec := sqlgraph.NewQuerySpec(version.Table, version.Columns, sqlgraph.NewFieldSpec(version.FieldID, field.TypeString))
	_spec.From = _q.sql
	if unique := _q.ctx.Unique; unique != nil {
		_spec.Unique = *unique
	} else if _q.path != nil {
		_spec.Unique = true
	}
	if fields := _q.ctx.Fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, version.FieldID)
		for i := range fields {
			if fields[i] != version.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, fields[i])
			}
		}
		if _q.withPlugin != nil {
			_spec.Node.AddColumnOnce(version.FieldPluginId)
		}
	}
	if ps := _q.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if limit := _q.ctx.Limit; limit != nil {
		_spec.Limit = *limit
	}
	if offset := _q.ctx.Offset; offset != nil {
		_spec.Offset = *offset
	}
	if ps := _q.order; len(ps) > 0 {
		_spec.Order = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	return _spec
}

func (_q *VersionQuery) sqlQuery(ctx context.Context) *sql.Selector {
	builder := sql.Dialect(_q.driver.Dialect())
	t1 := builder.Table(version.Table)
	columns := _q.ctx.Fields
	if len(columns) == 0 {
		columns = version.Columns
	}
	selector := builder.Select(t1.Columns(columns...)...).From(t1)
	if _q.sql != nil {
		selector = _q.sql
		selector.Select(selector.Columns(columns...)...)
	}
	if _q.ctx.Unique != nil && *_q.ctx.Unique {
		selector.Distinct()
	}
	for _, p := range _q.predicates {
		p(selector)
	}
	for _, p := range _q.order {
		p(selector)
	}
	if offset := _q.ctx.Offset; offset != nil {
		// limit is mandatory for offset clause. We start
		// with default value, and override it below if needed.
		selector.Offset(*offset).Limit(math.MaxInt32)
	}
	if limit := _q.ctx.Limit; limit != nil {
		selector.Limit(*limit)
	}
	return selector
}

// VersionGroupBy is the group-by builder for Version entities.
type VersionGroupBy struct {
	selector
	build *VersionQuery
}

// Aggregate adds the given aggregation functions to the group-by query.
func (_g *VersionGroupBy) Aggregate(fns ...AggregateFunc) *VersionGroupBy {
	_g.fns = append(_g.fns, fns...)
	return _g
}

// Scan applies the selector query and scans the result into the given value.
func (_g *VersionGroupBy) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _g.build.ctx, ent.OpQueryGroupBy)
	if err := _g.build.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VersionQuery, *VersionGroupBy](ctx, _g.build, _g, _g.build.inters, v)
}

func (_g *VersionGroupBy) sqlScan(ctx context.Context, root *VersionQuery, v any) error {
	selector := root.sqlQuery(ctx).Select()
	aggregation := make([]string, 0, len(_g.fns))
	for _, fn := range _g.fns {
		aggregation = append(aggregation, fn(selector))
	}
	if len(selector.SelectedColumns()) == 0 {
		columns := make([]string, 0, len(*_g.flds)+len(_g.fns))
		for _, f := range *_g.flds {
			columns = append(columns, selector.C(f))
		}
		columns = append(columns, aggregation...)
		selector.Select(columns...)
	}
	selector.GroupBy(selector.Columns(*_g.flds...)...)
	if err := selector.Err(); err != nil {
		return err
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _g.build.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}

// VersionSelect is the builder for selecting fields of Version entities.
type VersionSelect struct {
	*VersionQuery
	selector
}

// Aggregate adds the given aggregation functions to the selector query.
func (_s *VersionSelect) Aggregate(fns ...AggregateFunc) *VersionSelect {
	_s.fns = append(_s.fns, fns...)
	return _s
}

// Scan applies the selector query and scans the result into the given value.
func (_s *VersionSelect) Scan(ctx context.Context, v any) error {
	ctx = setContextOp(ctx, _s.ctx, ent.OpQuerySelect)
	if err := _s.prepareQuery(ctx); err != nil {
		return err
	}
	return scanWithInterceptors[*VersionQuery, *VersionSelect](ctx, _s.VersionQuery, _s, _s.inters, v)
}

func (_s *VersionSelect) sqlScan(ctx context.Context, root *VersionQuery, v any) error {
	selector := root.sqlQuery(ctx)
	aggregation := make([]string, 0, len(_s.fns))
	for _, fn := range _s.fns {
		aggregation = append(aggregation, fn(selector))
	}
	switch n := len(*_s.selector.flds); {
	case n == 0 && len(aggregation) > 0:
		selector.Select(aggregation...)
	case n != 0 && len(aggregation) > 0:
		selector.AppendSelect(aggregation...)
	}
	rows := &sql.Rows{}
	query, args := selector.Query()
	if err := _s.driver.Query(ctx, query, args, rows); err != nil {
		return err
	}
	defer rows.Close()
	return sql.ScanSlice(rows, v)
}
