// Code generated by ent, DO NOT EDIT.

package producer

import (
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the producer type in the database.
	Label = "producer"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGithubUser holds the string denoting the githubuser field in the database.
	FieldGithubUser = "github_user"
	// FieldRole holds the string denoting the role field in the database.
	FieldRole = "role"
	// FieldVersionId holds the string denoting the versionid field in the database.
	FieldVersionId = "version_id"
	// EdgeVersion holds the string denoting the version edge name in mutations.
	EdgeVersion = "version"
	// Table holds the table name of the producer in the database.
	Table = "producers"
	// VersionTable is the table that holds the version relation/edge.
	VersionTable = "producers"
	// VersionInverseTable is the table name for the Version entity.
	// It exists in this package in order to avoid circular dependency with the "version" package.
	VersionInverseTable = "versions"
	// VersionColumn is the table column denoting the version relation/edge.
	VersionColumn = "version_id"
)

// Columns holds all SQL columns for producer fields.
var Columns = []string{
	FieldID,
	FieldGithubUser,
	FieldRole,
	FieldVersionId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// Role defines the type for the "role" enum field.
type Role string

// Role values.
const (
	RoleCOLLABORATOR Role = "COLLABORATOR"
	RoleCONTRIBUTOR  Role = "CONTRIBUTOR"
	RoleTRANSLATOR   Role = "TRANSLATOR"
	RoleREQUESTER    Role = "REQUESTER"
)

func (r Role) String() string {
	return string(r)
}

// RoleValidator is a validator for the "role" field enum values. It is called by the builders before save.
func RoleValidator(r Role) error {
	switch r {
	case RoleCOLLABORATOR, RoleCONTRIBUTOR, RoleTRANSLATOR, RoleREQUESTER:
		return nil
	default:
		return fmt.Errorf("producer: invalid enum value for role field: %q", r)
	}
}

// OrderOption defines the ordering options for the Producer queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGithubUser orders the results by the githubUser field.
func ByGithubUser(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubUser, opts...).ToFunc()
}

// ByRole orders the results by the role field.
func ByRole(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldRole, opts...).ToFunc()
}

// ByVersionId orders the results by the versionId field.
func ByVersionId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionId, opts...).ToFunc()
}

// ByVersionField orders the results by version field.
func ByVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newVersionStep(), sql.OrderByField(field, opts...))
	}
}
func newVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(VersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, VersionTable, VersionColumn),
	)
}
