// Code generated by ent, DO NOT EDIT.

package user

import (
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the user type in the database.
	Label = "user"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldGithubId holds the string denoting the githubid field in the database.
	FieldGithubId = "github_id"
	// FieldUsername holds the string denoting the username field in the database.
	FieldUsername = "username"
	// FieldDisplayName holds the string denoting the displayname field in the database.
	FieldDisplayName = "display_name"
	// FieldEmail holds the string denoting the email field in the database.
	FieldEmail = "email"
	// FieldAvatarUrl holds the string denoting the avatarurl field in the database.
	FieldAvatarUrl = "avatar_url"
	// FieldBio holds the string denoting the bio field in the database.
	FieldBio = "bio"
	// FieldTrustLevel holds the string denoting the trustlevel field in the database.
	FieldTrustLevel = "trust_level"
	// FieldTrustScore holds the string denoting the trustscore field in the database.
	FieldTrustScore = "trust_score"
	// FieldWeeklyBuildQuota holds the string denoting the weeklybuildquota field in the database.
	FieldWeeklyBuildQuota = "weekly_build_quota"
	// FieldWeeklyBuildCount holds the string denoting the weeklybuildcount field in the database.
	FieldWeeklyBuildCount = "weekly_build_count"
	// FieldQuotaResetAt holds the string denoting the quotaresetat field in the database.
	FieldQuotaResetAt = "quota_reset_at"
	// FieldCreatedAt holds the string denoting the createdat field in the database.
	FieldCreatedAt = "created_at"
	// FieldUpdatedAt holds the string denoting the updatedat field in the database.
	FieldUpdatedAt = "updated_at"
	// EdgePlugins holds the string denoting the plugins edge name in mutations.
	EdgePlugins = "plugins"
	// EdgeAccounts holds the string denoting the accounts edge name in mutations.
	EdgeAccounts = "accounts"
	// EdgeSessions holds the string denoting the sessions edge name in mutations.
	EdgeSessions = "sessions"
	// EdgeReviews holds the string denoting the reviews edge name in mutations.
	EdgeReviews = "reviews"
	// EdgeReports holds the string denoting the reports edge name in mutations.
	EdgeReports = "reports"
	// EdgeRatings holds the string denoting the ratings edge name in mutations.
	EdgeRatings = "ratings"
	// EdgePluginComments holds the string denoting the plugincomments edge name in mutations.
	EdgePluginComments = "pluginComments"
	// Table holds the table name of the user in the database.
	Table = "users"
	// PluginsTable is the table that holds the plugins relation/edge.
	PluginsTable = "plugins"
	// PluginsInverseTable is the table name for the Plugin entity.
	// It exists in this package in order to avoid circular dependency with the "plugin" package.
	PluginsInverseTable = "plugins"
	// PluginsColumn is the table column denoting the plugins relation/edge.
	PluginsColumn = "author_id"
	// AccountsTable is the table that holds the accounts relation/edge.
	AccountsTable = "accounts"
	// AccountsInverseTable is the table name for the Account entity.
	// It exists in this package in order to avoid circular dependency with the "account" package.
	AccountsInverseTable = "accounts"
	// AccountsColumn is the table column denoting the accounts relation/edge.
	AccountsColumn = "user_id"
	// SessionsTable is the table that holds the sessions relation/edge.
	SessionsTable = "sessions"
	// SessionsInverseTable is the table name for the Session entity.
	// It exists in this package in order to avoid circular dependency with the "session" package.
	SessionsInverseTable = "sessions"
	// SessionsColumn is the table column denoting the sessions relation/edge.
	SessionsColumn = "user_id"
	// ReviewsTable is the table that holds the reviews relation/edge.
	ReviewsTable = "reviews"
	// ReviewsInverseTable is the table name for the Review entity.
	// It exists in this package in order to avoid circular dependency with the "review" package.
	ReviewsInverseTable = "reviews"
	// ReviewsColumn is the table column denoting the reviews relation/edge.
	ReviewsColumn = "reviewer_id"
	// ReportsTable is the table that holds the reports relation/edge.
	ReportsTable = "reports"
	// ReportsInverseTable is the table name for the Report entity.
	// It exists in this package in order to avoid circular dependency with the "report" package.
	ReportsInverseTable = "reports"
	// ReportsColumn is the table column denoting the reports relation/edge.
	ReportsColumn = "reporter_id"
	// RatingsTable is the table that holds the ratings relation/edge.
	RatingsTable = "ratings"
	// RatingsInverseTable is the table name for the Rating entity.
	// It exists in this package in order to avoid circular dependency with the "rating" package.
	RatingsInverseTable = "ratings"
	// RatingsColumn is the table column denoting the ratings relation/edge.
	RatingsColumn = "user_id"
	// PluginCommentsTable is the table that holds the pluginComments relation/edge.
	PluginCommentsTable = "plugin_comments"
	// PluginCommentsInverseTable is the table name for the PluginComment entity.
	// It exists in this package in order to avoid circular dependency with the "plugincomment" package.
	PluginCommentsInverseTable = "plugin_comments"
	// PluginCommentsColumn is the table column denoting the pluginComments relation/edge.
	PluginCommentsColumn = "user_id"
)

// Columns holds all SQL columns for user fields.
var Columns = []string{
	FieldID,
	FieldGithubId,
	FieldUsername,
	FieldDisplayName,
	FieldEmail,
	FieldAvatarUrl,
	FieldBio,
	FieldTrustLevel,
	FieldTrustScore,
	FieldWeeklyBuildQuota,
	FieldWeeklyBuildCount,
	FieldQuotaResetAt,
	FieldCreatedAt,
	FieldUpdatedAt,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultTrustScore holds the default value on creation for the "trustScore" field.
	DefaultTrustScore int
	// DefaultWeeklyBuildQuota holds the default value on creation for the "weeklyBuildQuota" field.
	DefaultWeeklyBuildQuota int
	// DefaultWeeklyBuildCount holds the default value on creation for the "weeklyBuildCount" field.
	DefaultWeeklyBuildCount int
	// DefaultQuotaResetAt holds the default value on creation for the "quotaResetAt" field.
	DefaultQuotaResetAt func() time.Time
	// DefaultCreatedAt holds the default value on creation for the "createdAt" field.
	DefaultCreatedAt func() time.Time
	// DefaultUpdatedAt holds the default value on creation for the "updatedAt" field.
	DefaultUpdatedAt func() time.Time
	// UpdateDefaultUpdatedAt holds the default value on update for the "updatedAt" field.
	UpdateDefaultUpdatedAt func() time.Time
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// TrustLevel defines the type for the "trustLevel" enum field.
type TrustLevel string

// TrustLevelNEW is the default value of the TrustLevel enum.
const DefaultTrustLevel = TrustLevelNEW

// TrustLevel values.
const (
	TrustLevelNEW        TrustLevel = "NEW"
	TrustLevelTRUSTED    TrustLevel = "TRUSTED"
	TrustLevelMAINTAINER TrustLevel = "MAINTAINER"
	TrustLevelADMIN      TrustLevel = "ADMIN"
)

func (tl TrustLevel) String() string {
	return string(tl)
}

// TrustLevelValidator is a validator for the "trustLevel" field enum values. It is called by the builders before save.
func TrustLevelValidator(tl TrustLevel) error {
	switch tl {
	case TrustLevelNEW, TrustLevelTRUSTED, TrustLevelMAINTAINER, TrustLevelADMIN:
		return nil
	default:
		return fmt.Errorf("user: invalid enum value for trustLevel field: %q", tl)
	}
}

// OrderOption defines the ordering options for the User queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByGithubId orders the results by the githubId field.
func ByGithubId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldGithubId, opts...).ToFunc()
}

// ByUsername orders the results by the username field.
func ByUsername(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUsername, opts...).ToFunc()
}

// ByDisplayName orders the results by the displayName field.
func ByDisplayName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldDisplayName, opts...).ToFunc()
}

// ByEmail orders the results by the email field.
func ByEmail(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldEmail, opts...).ToFunc()
}

// ByAvatarUrl orders the results by the avatarUrl field.
func ByAvatarUrl(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldAvatarUrl, opts...).ToFunc()
}

// ByBio orders the results by the bio field.
func ByBio(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldBio, opts...).ToFunc()
}

// ByTrustLevel orders the results by the trustLevel field.
func ByTrustLevel(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrustLevel, opts...).ToFunc()
}

// ByTrustScore orders the results by the trustScore field.
func ByTrustScore(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldTrustScore, opts...).ToFunc()
}

// ByWeeklyBuildQuota orders the results by the weeklyBuildQuota field.
func ByWeeklyBuildQuota(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyBuildQuota, opts...).ToFunc()
}

// ByWeeklyBuildCount orders the results by the weeklyBuildCount field.
func ByWeeklyBuildCount(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldWeeklyBuildCount, opts...).ToFunc()
}

// ByQuotaResetAt orders the results by the quotaResetAt field.
func ByQuotaResetAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldQuotaResetAt, opts...).ToFunc()
}

// ByCreatedAt orders the results by the createdAt field.
func ByCreatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldCreatedAt, opts...).ToFunc()
}

// ByUpdatedAt orders the results by the updatedAt field.
func ByUpdatedAt(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldUpdatedAt, opts...).ToFunc()
}

// ByPluginsCount orders the results by plugins count.
func ByPluginsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPluginsStep(), opts...)
	}
}

// ByPlugins orders the results by plugins terms.
func ByPlugins(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPluginsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByAccountsCount orders the results by accounts count.
func ByAccountsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newAccountsStep(), opts...)
	}
}

// ByAccounts orders the results by accounts terms.
func ByAccounts(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newAccountsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// BySessionsCount orders the results by sessions count.
func BySessionsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newSessionsStep(), opts...)
	}
}

// BySessions orders the results by sessions terms.
func BySessions(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newSessionsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReviewsCount orders the results by reviews count.
func ByReviewsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReviewsStep(), opts...)
	}
}

// ByReviews orders the results by reviews terms.
func ByReviews(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReviewsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByReportsCount orders the results by reports count.
func ByReportsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newReportsStep(), opts...)
	}
}

// ByReports orders the results by reports terms.
func ByReports(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newReportsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByRatingsCount orders the results by ratings count.
func ByRatingsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newRatingsStep(), opts...)
	}
}

// ByRatings orders the results by ratings terms.
func ByRatings(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newRatingsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}

// ByPluginCommentsCount orders the results by pluginComments count.
func ByPluginCommentsCount(opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborsCount(s, newPluginCommentsStep(), opts...)
	}
}

// ByPluginComments orders the results by pluginComments terms.
func ByPluginComments(term sql.OrderTerm, terms ...sql.OrderTerm) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newPluginCommentsStep(), append([]sql.OrderTerm{term}, terms...)...)
	}
}
func newPluginsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PluginsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, PluginsTable, PluginsColumn),
	)
}
func newAccountsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(AccountsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, AccountsTable, AccountsColumn),
	)
}
func newSessionsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(SessionsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, SessionsTable, SessionsColumn),
	)
}
func newReviewsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReviewsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ReviewsTable, ReviewsColumn),
	)
}
func newReportsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ReportsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, ReportsTable, ReportsColumn),
	)
}
func newRatingsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(RatingsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, RatingsTable, RatingsColumn),
	)
}
func newPluginCommentsStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(PluginCommentsInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.O2M, true, PluginCommentsTable, PluginCommentsColumn),
	)
}
