// Code generated by ent, DO NOT EDIT.

package dependency

import (
	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
)

const (
	// Label holds the string label denoting the dependency type in the database.
	Label = "dependency"
	// FieldID holds the string denoting the id field in the database.
	FieldID = "id"
	// FieldName holds the string denoting the name field in the database.
	FieldName = "name"
	// FieldVersion holds the string denoting the version field in the database.
	FieldVersion = "version"
	// FieldVersionId holds the string denoting the versionid field in the database.
	FieldVersionId = "version_id"
	// EdgeParentVersion holds the string denoting the parentversion edge name in mutations.
	EdgeParentVersion = "parentVersion"
	// Table holds the table name of the dependency in the database.
	Table = "dependencies"
	// ParentVersionTable is the table that holds the parentVersion relation/edge.
	ParentVersionTable = "dependencies"
	// ParentVersionInverseTable is the table name for the Version entity.
	// It exists in this package in order to avoid circular dependency with the "version" package.
	ParentVersionInverseTable = "versions"
	// ParentVersionColumn is the table column denoting the parentVersion relation/edge.
	ParentVersionColumn = "version_id"
)

// Columns holds all SQL columns for dependency fields.
var Columns = []string{
	FieldID,
	FieldName,
	FieldVersion,
	FieldVersionId,
}

// ValidColumn reports if the column name is valid (part of the table columns).
func ValidColumn(column string) bool {
	for i := range Columns {
		if column == Columns[i] {
			return true
		}
	}
	return false
}

var (
	// DefaultID holds the default value on creation for the "id" field.
	DefaultID func() string
)

// OrderOption defines the ordering options for the Dependency queries.
type OrderOption func(*sql.Selector)

// ByID orders the results by the id field.
func ByID(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldID, opts...).ToFunc()
}

// ByName orders the results by the name field.
func ByName(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldName, opts...).ToFunc()
}

// ByVersion orders the results by the version field.
func ByVersion(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersion, opts...).ToFunc()
}

// ByVersionId orders the results by the versionId field.
func ByVersionId(opts ...sql.OrderTermOption) OrderOption {
	return sql.OrderByField(FieldVersionId, opts...).ToFunc()
}

// ByParentVersionField orders the results by parentVersion field.
func ByParentVersionField(field string, opts ...sql.OrderTermOption) OrderOption {
	return func(s *sql.Selector) {
		sqlgraph.OrderByNeighborTerms(s, newParentVersionStep(), sql.OrderByField(field, opts...))
	}
}
func newParentVersionStep() *sqlgraph.Step {
	return sqlgraph.NewStep(
		sqlgraph.From(Table, FieldID),
		sqlgraph.To(ParentVersionInverseTable, FieldID),
		sqlgraph.Edge(sqlgraph.M2O, false, ParentVersionTable, ParentVersionColumn),
	)
}
